### ISSUE TITLE
请问可以去掉最后的按键确认吗？

### ISSUE THREAD

**Issue by felixding** [XIU2/CloudflareSpeedTest#1]
程序运行结束时，用户必须按键确认才能退出，这样如果我希望自动化整个过程，就必须要在程序中模拟用户的行为，增加了复杂性。请问是否可以结束时直接退出？

**Comment by christan-duplicate** [comment]
试下把
``
var pause int
fmt.Scanln(&pause)
``
注释了

**Comment by XIU2** [comment]
emmm ，才发现这个 Issues，上个月有段时间老是收不到 Github 的通知邮件。  

这个问题我考虑到了，启动参数加上 -p -1 后运行完就不会显示结果，直接退出。

**Comment by XIU2** [comment]
v1.3.5 优化了下，现在只有 Windows 系统下运行**才需要按下** 回车键 或 Ctrl+C 退出。
