### ISSUE TITLE
能否支持 ipv6？

### ISSUE THREAD

**Issue by huyz-git** [XIU2/CloudflareSpeedTest#10]
目前版本好像不支持测 cloudflare ipv6 的速度或延迟。
如果把较大的 ipv6 range 输进 `ip.txt` 里的话，则程序会卡很久，并且在不断的消耗内存，一段 /64 的 ipv6 程度占用了近 20G 的内存都还没有终止的迹象。
如果把较小的 ipv6 range 输进 `ip.txt` 里的话，比如一段 /110，则程序瞬间（0.2 秒内）完成，并输出：
```
# XIU2/CloudflareSpeedTest 

开始延迟测速（模式：TCP，端口：443）：
4096 / 4096 [-------------------------------------------------------------------------------------------------------] 100.00%

[信息] IP数量为 0，跳过下载测速。

[信息] IP数量为 0，跳过输出结果。
```

**Comment by XIU2** [comment]
目前并不支持 IPv6 TCPing。  
我这边也没有环境测试，而且我本身就是临时学的半吊子技术。。。

**Comment by XIU2** [comment]
而且目前还支持解析 IPv4 的 IP 段。

**Comment by XIU2** [comment]
稍微研究了下，目前解决了 IPv6 的延迟测速（TCPing）、下载测速问题。  
正在研究如何更好的解析 IPv6 IP段，主要是 IPv6 太特么多了。。。导致解析效率极低。

**Comment by XIU2** [comment]
集中转到一个 Issues 里吧。
#12

**Comment by XIU2** [comment]
## v1.3.6
1. **新增** IPv6 支持（延迟测速+下载测速）。  
`因为 IPv6 IP 太多了（约 294 亿），而且 Cloudflare CDN 目前只用了极小一部分（约 400 万），所以目前是采用 IP 段子网随机测速。`
`因为 Cloudflare 没有提供当前正在使用的 IPv6 IP段（绝大部分为闲置状态），所以 ipv6.txt 文件内并不是全部 IP 段，但也差不多了。`
