### ISSUE TITLE
大佬，win系统咋筛选IPV6啊，你前边那个指定ipv6文本介绍没看懂。。

### ISSUE THREAD

**Issue by cha7777** [XIU2/CloudflareSpeedTest#102]
emm小白，，大佬尽量说的直白点。详细点。谢谢啊。。你里边那个IPV6文本 咋指定啊。。

**Comment by XIU2** [comment]
使用示例中不是写了吗？
https://github.com/XIU2/CloudflareSpeedTest#-ipv4ipv6

```
# 指定 IPv6 数据文件( ipv6.txt )，需要加上 -ipv6 参数
CloudflareST.exe -f ipv6.txt -ipv6
```

这样就行了，加上 -ipv6 并指定 IP 数据文件为 ipv6.txt

**Comment by cha7777** [comment]
OK了。已经解决了。。
