### ISSUE TITLE
下载测速地址失效

### ISSUE THREAD

**Issue by WGzeyu** [XIU2/CloudflareSpeedTest#103]
https://github.com/XIU2/CloudflareSpeedTest/blob/180097b044b76978dbd98f6e1e96ee89720631a0/main.go#L110
![](https://wgzeyu.gtxcn.com/img/QQ%E6%88%AA%E5%9B%BE20210523140509.png)

**Comment by XIU2** [comment]
没有失效，因为我设置的就是只能我的软件內调用，浏览器直接打开就提示这个。

你说失效前，应该先试一下 CloudflareST。。。
