### ISSUE TITLE
测速时是否应该挂着梯子测试？

### ISSUE THREAD

**Issue by inbogota** [XIU2/CloudflareSpeedTest#105]
请教一哈，cdn只是用来伪装梯子的，那么优选ip的时候，应不应该挂着梯子测？

**Comment by XIU2** [comment]
不能挂任何梯子，**只有直连测试才最准确**。

对于使用 CDN 来做梯子的用户，其链接是这样的：
<kbd>你 <=> Cloudflare CDN <=> 源服务器 <=> 目标网站</kbd>

你直连测速就是让第一个环节速度最大化，第二个环节 Cloudflare 会通过离你源服务器最近的 CDN 节点去回源，当然这第二个、第三个环节你都是无法控制的，你只能控制第一个环节。

****

如果你挂梯子测速，链接就会变成这样：
<kbd>你 <=> Cloudflare CDN <=> 源服务器 <=> Cloudflare CDN</kbd>

速度就会完全不准确了。

**Comment by inbogota** [comment]
感谢解答，总算搞明白一些
另求教一下cdn的原理，这cloudflare代理梯子之后，怎样实现的本地端与vps的连接的
1，类似DNS解析，只是把域名重新解析寻址，本地与vps的数据还是直连的？
2，还是说，类似frp一样，cloudflare提供一个中转服务器，把所有数据中转代理？

因为国内用cloudflare，一律给解析到美国，那如果所有的流量数据都通过cloudflare代理的话，应该选择一个美国的vps
如果只是帮助伪装ip的话，那还是可以用香港日本的vps的，只不过域名寻址的时候多了点延迟而已

搞明白cdn原理后就会选vps，谢谢您拨冗解答

**Comment by XIU2** [comment]
CDN 本质就是反向代理，你的代理软件伪装成 HTTPS 或 WSS 对 CDN 来说就是一个网站。
你访问 CDN 节点，CDN 会把你的请求原封不动的发给源服务器，源服务器再去访问目标网站并依次返回。

CDN 承担一个中转的作用，因为 CDN 只能处理 HTTP/HTTPS/WS/WSS 流量，所以代理软件必须伪装后才能搭配 CDN 使用。

**Comment by inbogota** [comment]
基本明白了，CF原理就是一个只拥有1台vps的反向代理

我的梯子在香港，如果能把Anycast IP定在香港的话，速度应该不会太慢（比起直连还是有损耗的）
不过我用您的软件测出来的最快的ip，还是美西的……
大概对于北方联通用户，还是美西带宽充足吧，看来我以后再购入梯子要换地区了
