### ISSUE TITLE
测速结果下载速度为0

### ISSUE THREAD

**Issue by HeXis-YS** [XIU2/CloudflareSpeedTest#106]
我已经充分查阅已有issue，该问题可以100%复现。
使用参数`-allip -sl 2 -n 1000`
已经确认测速时没有开代理，并且在没有代理的情况下可以直接访问CF官网和使用CF的网站。
测试于昨天（6月8日）晚上12点左右
![图片](https://user-images.githubusercontent.com/40174982/121277391-163b4500-c903-11eb-9e97-28cff2fcb764.png)
测试于今日（6月9日）早上9点左右
![图片](https://user-images.githubusercontent.com/40174982/121277845-0708c700-c904-11eb-8833-a4500a10f2b2.png)

**Comment by HeXis-YS** [comment]
我是远程桌面连接的主机。刚刚又试了一下，延迟测试大概到7000左右的时候会掉线，直到最后测试结束后才恢复。如果禁用下载测试，只测延迟，会一直掉线。
最近没时间亲自测试，只能用远程桌面访问。目测可能是网卡或者驱动的问题，因为在虚拟机里测试也是同样的结果。

**Comment by XIU2** [comment]
抱歉，最近一个星期没在线，今天上来一看堆积了一堆 Issues...

你的意思是只有使用 `-allip -sl 2 -n 1000` 参数时，才会出现这种情况？
你本地用这个参数是否正常？

**Comment by HeXis-YS** [comment]
即使是并发降低到100，也会出现同样的情况，在延迟测试到7000左右时会断线。
测试机器是连在一个百兆路由器，再连接到学校网络上。直连学校WiFi测试没有问题。初步怀疑是路由器的问题。

**Comment by XIU2** [comment]
这应该是路由器有什么限制导致的，或者是性能问题。

我平时后台测速的时候，也会降低速度（连接数太多会堵塞路由器），避免影响我前台浏览网页什么的。
