### ISSUE TITLE
无法检测IPv6地址

### ISSUE THREAD

**Issue by Tokisaki-Galaxy** [XIU2/CloudflareSpeedTest#107]
ipconfig显示有ipv6地址，在这个软件使用ipv6测速失败，显示ipv4的地址
![](https://files.catbox.moe/ciijtk.png)

**Comment by XIU2** [comment]
抱歉，最近一个星期没在线，今天上来一看堆积了一堆 Issues...

你这个一看就是没有去看我写的使用说明。。。

[https://github.com/XIU2/CloudflareSpeedTest#-ipv4ipv6](https://github.com/XIU2/CloudflareSpeedTest#-ipv4ipv6)

```
# 指定 IPv4 数据文件（-f 默认值就是 ip.txt，所以该参数可以省略）
CloudflareST.exe -f ip.txt

# 指定 IPv6 数据文件( ipv6.txt )，需要加上 -ipv6 参数
CloudflareST.exe -f ipv6.txt -ipv6
```

你只加上了` -ipv6 `参数，却没有指定` -f ipv6.txt `数据文件。
