### ISSUE TITLE
有办法在开着梯子的情况下测速吗

### ISSUE THREAD

**Issue by uminoai** [XIU2/CloudflareSpeedTest#109]
因为梯子一直是开着的，设置cron 测速替换host的时候梯子也没法关掉，有什么办法，让测速的时候不走代理吗

**Comment by XIU2** [comment]
我已经回复过你了： https://github.com/XIU2/CloudflareSpeedTest/issues/42#issuecomment-880287529
你需要自己去找关闭路由器代理的命令并添加到脚本中。
或者把所有 Cloudflare IP 段及 `cf.xiu2.xyz` 加到代理白名单中（暂不确定，自己试试）。

**Comment by uminoai** [comment]
> 我已经回复过你了： [#42 (comment)](https://github.com/XIU2/CloudflareSpeedTest/issues/42#issuecomment-880287529)
> 你需要自己去找关闭路由器代理的命令并添加到脚本中。
> 或者把所有 Cloudflare IP 段及 `cf.xiu2.xyz` 加到代理白名单中（暂不确定，自己试试）。

好的，我试一下。

**Comment by uminoai** [comment]
service bypass stop
我在脚本的check前写了这个命令(bypass是梯子服务)，可是提示service command not found.

但是我进入ssh，直接输这个命令是可以的。可以请教下应该怎么解决不。

**Comment by uminoai** [comment]
自己已经搞定了，感谢！

**Comment by XIU2** [comment]
OK~
既然文件解决了，那就关闭该 Issues 吧，当然有问题可以继续讨论~
