### ISSUE TITLE
如遇到 `延迟异常低 (几十 ms)` 且不可用的测速结果，请加上 `-tll` 参数过滤 `假蔷 IP` ！

### ISSUE THREAD

**Issue by XIU2** [XIU2/CloudflareSpeedTest#111]
因为很多人被假蔷勒索，然后它们套 Cloudflare 来抵御假蔷，结果就是 Cloudflare 大量 IP 被假蔷。
虽然被假蔷的 IP 很快就会解封，但是因为假蔷勒索泛滥，导致一直有新的 Cloudflare IP 被假蔷。

最近发现 Cloudflare 被假蔷的 IP 似乎越来越多了，因此在大家的建议下加了个 `[平均延迟下限]` 参数~

## \# 区分假蔷

- **假蔷 IP 的表现特征：**
_Ping 延迟**正常**，TCPing 延迟**异常的低**，下载速度为 ` 0.00 `（或约等于 0，即不可用）。_
_`即 TCPing 延迟远低于 Ping 延迟。`_

****

### \# 电信/联通用户

因为**除了移动**(直连香港) 外，电信/联通几乎不存在 TCPing 延迟低于 100ms 的 IP，因此低于 100ms 的 IP 可以确定为被假蔷了。

> 具体 TCPing 延迟多少往往取决于你到国际网络出口处（北京、上海、广州）多远，因为蔷是在出口处进行 TCP 劫持的。

``` bash
# 平均延迟下限：100 ms 
./CloudflareST -tll 100
CloudflareST.exe -tll 100

# 平均延迟上限：300 ms，平均延迟下限：100 ms 
./CloudflareST -tl 300 -tll 100
CloudflareST.exe -tl 300 -tll 100

# 平均延迟下限和其他的上下限参数一样，都可以单独使用、互相搭配使用！
```

****

### \# 移动用户

因为**移动直连香港**的原因，测出来的香港节点的 IP 延迟也很低，和 TCPing 延迟很低的假蔷 IP **混在一起难以区分**，不能简单通过延迟下限来过滤了，因此需要加上 ` -sl ` 参数(**下载速度下限**) 来过滤掉同样延迟低但实际不可用的假蔷 IP。

``` bash
# 下载速度下限：1 MB/s
./CloudflareST -sl 1
CloudflareST.exe -sl 1

# 平均延迟上限：300 ms，下载速度下限：1 MB/s
./CloudflareST -tl 300 -sl 1
CloudflareST.exe -tl 300 -sl 1

# 移动用户注意不要使用 -tll 参数（延迟下限），除非你不想要香港节点~
# 被假蔷的 IP 下载速度基本为 0.00（或 0.0X 忽略不计），所以可以用下载速度来过滤掉不可用的假蔷 IP
```

**Comment by 10362227** [comment]
我刷出的ip大多数是50ms以内，而且可用。移动用户

**Comment by XIU2** [comment]
@10362227 所以我说了一句 “除了移动直连香港外” ~
电信联通的话正常情况下几乎不可能碰到延迟 100ms 以下的 IP。

**Comment by China-Huanghe** [comment]
就一直提醒我更新，但是我已经更新到1.5了，测速的时候还是没用
![image](https://user-images.githubusercontent.com/77739994/130560558-d1b17793-754c-435a-8b98-fc111f07646f.png)
![image](https://user-images.githubusercontent.com/77739994/130560572-fda0e6c2-0a8c-4437-8176-45643a9f46d1.png)

**Comment by XIU2** [comment]
@China-Huanghe 我这边测试了下，没有提示更新。
用 -v 参数主动检测更新也正常显示为： `当前为最新版本 [v1.5.0]！`

**Comment by China-Huanghe** [comment]
![image](https://user-images.githubusercontent.com/77739994/130616214-36979d41-0492-4066-a232-6af88fedce4c.png)
就是显示这个

**Comment by XIU2** [comment]
@China-Huanghe 
这个好像是 Cloudflare 的页面。。。
你浏览器能打开 https://api.xiuer.pw/ver/cloudflarespeedtest.txt 这个最新版本号的地址吗？

**Comment by XIU2** [comment]
@China-Huanghe 我这个最新版本号地址托管在 Cloudflare 中，我刚刚把版本号的 URL 加到防火墙例外中了，应该不会再出现这种问题了。

**Comment by China-Huanghe** [comment]
能打开这个地址，看到版本号是1.5，但是还是不能使用测速功能，

**Comment by China-Huanghe** [comment]
# XIU2/CloudflareSpeedTest v1.5.0

开始延迟测速（模式：TCP IPv4，端口：443，平均延迟上限：9999.00 ms，平均延迟下限：0.00 ms）：
17236 / 17236 [-----------------------------------------------------------------------------------------------] 100.00%
开始下载测速（下载速度下限：0.00 MB/s，下载测速数量：20，下载测速队列：20）：
20 / 20 [-----------------------------------------------------------------------------------------------------] 100.00%
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
104.16.160.161    4       4       0.00    14.25     0.00
104.27.16.79      4       4       0.00    145.65    0.00
104.18.97.57      4       4       0.00    145.70    0.00
104.17.77.74      4       4       0.00    146.04    0.00
104.17.179.90     4       4       0.00    147.17    0.00
104.17.159.115    4       4       0.00    147.38    0.00
104.17.181.27     4       4       0.00    147.59    0.00
104.16.189.7      4       4       0.00    147.64    0.00
104.17.146.29     4       4       0.00    148.30    0.00
104.17.248.220    4       4       0.00    148.41    0.00
104.27.3.75       4       4       0.00    148.73    0.00
104.18.22.55      4       4       0.00    148.75    0.00
104.17.72.79      4       4       0.00    148.95    0.00
104.18.78.47      4       4       0.00    149.43    0.00
104.16.194.62     4       4       0.00    149.60    0.00
104.16.145.219    4       4       0.00    149.74    0.00
104.18.84.246     4       4       0.00    150.21    0.00
104.16.49.106     4       4       0.00    150.38    0.00
104.16.212.17     4       4       0.00    150.57    0.00
104.16.122.9      4       4       0.00    150.62    0.00

*** 发现新版本 [<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>

<title>Please Wait... | Cloudflare</title>

<meta name="captcha-bypass" id="captcha-bypass" />
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>



<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>




    <script type="text/javascript">
    //<![CDATA[
    (function(){
      window._cf_chl_opt={
        cvId: "2",
        cType: "managed",
        cNounce: "55988",
        cRay: "683cabc82a363157",
        cHash: "f26901855c452af",
        cFPWv: "b",
        cTTimeMs: "1000",
        cLt: "n",
        cRq: {
          ru: "aHR0cHM6Ly9hcGkueGl1ZXIucHcvdmVyL2Nsb3VkZmxhcmVzcGVlZHRlc3QudHh0",
          ra: "R28taHR0cC1jbGllbnQvMi4w",
          rm: "R0VU",
          d: "SfMXJUU0U8Ye9DmjjcqcfMOUKWs0kWy0vTRoAccqblj+vwIZbfFT20mbqVDb+ay+X/AitEd1l56ATsZ98Vl6t2xI5Lx5kL+/xKj65crVza1pbAP22MFzWSDlXk//z9sAsT61e9EkEHZUArEAAN7P0w+DvAP9977tcE38MFxZbbf5c97q7I2POvdYqt42hHyKknXn347MinSdSpPmBLebFdlVy37t5jAAyWeu7G5VUY/yVB5K1Jgd1J4X3ZzH1OsFA6mQFWkG8Vb8ywRMpR87CLb6iA1D2Mq/mhPSNERLpGMWZw8Tfq2vlNkgnHREJhsuPHm+98tpaSbZGk5IUrz8f3sjLX4DrVntlmZof6KmaFunXnhiSWSRmb9Alp+BltsGs3wifyfFgPuGUL4PIrc62w9ZWitIjmcPUmOyB+xXcWBXt8aZwD1eRKZljhPUEK5wkarye+p2NtPuwiV6biFqgn3YmoUKEeZZeI5DC0wc2nzezIeAOUgN69LG5lOzeWYFu+5LymF8lNh5oxBiiaBxkxt920GKJMJUACceNCx4BK1RqnCQkguVk/LGWkAzbIC1gK3nRRuotLKPZiQlfd9ndK4uyDUZuvI1yM8uobpLLW5RYog0h8VvXUFgX12+jkz20T4POtRI+BSi/Z1DBsSA1bJtQKIRe3th0X2ekRZ/deU6nMTeQ84knzQIVBiidxDLZeWfP96P8Ej5g3Yv30x182vjGrjVsE7wo0Bsp2b2F/UoNieTHswScNMZVGt2ZhEGuufG5KlZwkovLsrbhwwCnK7dJZntvYyzN0DypB7L494M3VpGB9s+oks+wr872/3H+5nXU5Htk+3uLYCwxV2Jag==",
          t: "MTYyOTgwOTA1Ni4wMjYwMDA=",
          m: "nhHH/PQnBOaY0XlRByydWs3oAKdaiGk8U4ISYolWp/M=",
          i1: "+0JNQV3yPB3izYJQRpUjYg==",
          i2: "n7NpMohdcXdDKhmFyJ4acw==",
          zh: "j+5aDZ/jZsTEsi34w1+ULNOf25MJnQqx+GbGcSziOzM=",
          uh: "AN+5vvENMpdOACvuRa1plLx7uNq9y3wYG+zurIv4jHM=",
          hh: "E7jHG+2OlZa8kHBrpj82uiN7p3nmrQdjaQzuAk7H49Y=",
        }
      };
    }());
    //]]>
    </script>


<style type="text/css">
  #cf-wrapper #spinner {width:69px; margin:  auto;}
  #cf-wrapper #cf-please-wait{text-align:center}
  .attribution {margin-top: 32px;}
  .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
  #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
  #cf-hcaptcha-container { text-align:center;}
  #cf-hcaptcha-container iframe { display: inline-block;}
  @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
  #cf-wrapper #cf-bubbles { width:69px; }
  @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
  #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
  #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
  #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
</style>
</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">

        <h1 data-translate="managed_challenge_headline">Please wait...</h1>
        <h2 class="cf-subheadline"><span data-translate="managed_checking_msg">We are checking your browser...</span> api.xiuer.pw</h2>

      </div>
      <div style="display: none;"><a href="https://derchris.net/fungoidintensity.php?page=2">table</a></div>
      <div class="cf-section cf-highlight cf-captcha-container">
        <div class="cf-wrapper">
          <div class="cf-columns two">
            <div class="cf-column">

              <div class="cf-highlight-inverse cf-form-stacked">
                <form class="challenge-form managed-form" id="challenge-form" action="/ver/cloudflarespeedtest.txt?__cf_chl_managed_tk__=pmd_qbI6b96w78HGvPJCp0V6wGY6aaADMsJKWPsRWwaV7gA-1629809056-0-gqNtZGzNAtCjcnBszQZ9" method="POST" enctype="application/x-www-form-urlencoded">

    <div id='cf-please-wait'>
      <div id='spinner'>
        <div id="cf-bubbles">
            <div class="bubbles"></div>
            <div class="bubbles"></div>
            <div class="bubbles"></div>
        </div>
      </div>
      <p data-translate="please_wait" id="cf-spinner-please-wait">Please stand by, while we are checking your browser...</p>
      <p data-translate="redirecting" id="cf-spinner-redirecting" style="display:none">Redirecting...</p>
      </div>

  <input type="hidden" name="md" value="62u45K4Ft.IZx14lOQ7nWRt3C6N0jyPSXDf7ltUCK_0-1629809056-0-Aa55xKuQ_WYV1z9qu32rJK7jcRs5D5iv5xr7vagsmnvYXeO7Xc2Yw4HKkX_pvFpJMEyj-OQRpF_meDGnihg1qDyqYjuLpK3M_6kO5Cuawlg2A97_spliuvGEHfL6g4ye9w6WZDsA2PfCyE2h_VbgKvunq0fW5Xdk5xN_Q4tPPXmCZzG_7wsrb_BNbOxc2cw409pgYvf-dkWQyzIwjCSXsDSrtPzEh7bRaxSh_ixId7I7dPPRCxJj_mKgDCpyjHTai8yA82lvKd7Kg76nKZYpsxOjWg-iPjXK92vdIwF8c4B5Fg9t5K9pRHjYeqqyhIPjWQb5n2c-V7UDQXQI9PNZgp4yLzyIAww8CaqXCPLW1J-dvXyLSteBhKeWRC_Bm8MqMbYVk3DQvlqBrO90xXeIlN0SPCPif5JxOcUwhpy4c9qKKpRsCJKEv3oMD9VWdwJZCZwKEGRFfCBiIdDatAsAeq0jI3cwim9mAgfWpPSM7zxptjyzOguntPmpTGrrrDigeRE21OFYEt2pc5TEKRHiBqZ43IuVSU6fYF19RaKbbzEauKyJU1IAJAobh4bNPdfoLmTaKwOtnaRlCJ46TDcb32sG16ip2LxlTQsZ88_X2uSvrEeforU8yIkqmHPclOXvcO4MeGb7dlWgJXLJx2kIiqY" />
  <input type="hidden" name="r" value="7GjBPgq7SGkvSScpZ5z6ESmHgXHX3qEiQStlylNAyto-1629809056-0-ARom55gtQU+TqyCbb1WRsOoUopcGP/cLY5vee3tYXRdzZ4xk2HbWzBykAef268FCZhp3668deo35WsMY4e6DY/JrqxRi+bjHmRYFqnKG3O3B+grssbsehGHcrjXHmRZpMAOzkVIsgkR9Gbmhpmu46XOzuwsgZmqubLmo19FDQkKdGha0FskAx1GdC/lP4a+Lqez4jY9xJwPF9ubZ41/qH5nZncpYIYtMU2uH2bZmI/3YEyqHpPw1myeMHTK9gpIvbC89OxVuZahsax9MbOn84CU330ejeBbgBtVT4vWB5jIX+HyYtalfnB83cSsV7Au6jLOA4tlXRVR+j8w4WikHGc2IC9WRfx/6mSzUQSxjKD6aMWkARcPjSMtHvlm+e8MPktS6EEkOolznPk22U08vwriOM7MhSFmlJ/BnZSfpsJvXTFyQGqnxWXMHME6IxsuXj62kuC7vGRqmALyf97d5Y4o7w71tjUqdksVRwbVMW8zt7dvDRPEJy3wMlH6Z0CdRpPr9GvpxfoyY8Nu5o/v3Fp6qI9rtxfEWODLo7VMAHvW/w3w9VbP/QSYZjMhf/Ztj6XXEH3eXGO0139Og9xq53uOnIWky8W4htLGuF3zGIER9XFnA6MDYs7RPBU1mdXHEuV2m4AsHkOTlejVYc9z3yVFp73nV2n2Rv/D83mr8Ze7Q/pA2wVn+s1XTgeMwMtXpbcBzL0GPZYKZFcA3epFCa7EZhs7CIbJOOznmuNhRk7gmd7DCpNslSmH4JLUZYpGZIj/t4q2Dy6y35S9IDkIc266nTPDjKx0x6KC5mDoagwF9vg59spxY94H4yQCEgLO/kbUa570zQrv+pRAD6+DjPf1JNc1hNL3xQG52S6GHILk2D9xFC5ZmInD58L44RvbC80ELVejnWyo2QxDQHfi2nBdCslQJwptkBMS98bMBW9Xa+OXsa6Kx6Oi7B1yxOwbcVchy+eIqpAWPE109Uyis2HwcHvQaWyIDA7U0H9gxhKG7L0TRvHW7HLtGzCOYVT8foca7kFYLHRLKxLfdnwLE8tjoFvHNKsQzK/tXhHMAoBM1LSxLeJm5ZUlkSV7ys47wKzg+Cebgq1eiKDrXvBQD9R0pkzXOZQFYmhdZdEu5TEoS0VdA+byn6Xi3wDgtgV7u5KDHwp4OyoviapRyolx2OXnDVq3Bpkm3iOKWpRUawadZDIU5oeQpblYNOuhgE5ucGrihkK3TvBfrHTgeQ/Ljfr4PvmHEnNsK51bl1Ol5aUQANaVXzEwCylrv+ML3woV/37q3jKvd5ZR2FUEHCaIT2hNneHjrm15zxnKSyBUoSLidNkNwrV8zz23PV7yZhjCEjGhN4cZftmTu9fNb+1yquFc6run2d48bhAwyRY1zBLKUOQfunawL9CgrcvGp05K6DnMfgqpBx+xdSiPdYR8W7eD+wurTsWevE9SRtZtf83MK5x9uetr3TGc15FGoIzG8kSmn0mXdjlykfcd8bj17FUAAjUhIMe98bSDrF43NY4S7IV6Y0eH8tPp9wiGvl4B9ARqJOz3mm9i+T2OQkPZ/PJZMkWJzRR5EHbLvSNVqto1pttkHuZM7sowk+V5s8jh9mw==">
  <input type="hidden" name="cf_captcha_kind" value="h">
  <input type="hidden" name="vc" value="ab3578519850bde96ee5a6c811f5b60d">

  <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
  <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
    <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
    </div>
  <script type="text/javascript">
  //<![CDATA[
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
      b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
      b(function(){
        var cookiesEnabled=(navigator.cookieEnabled)? true : false;
        if(!cookiesEnabled){
          var q = document.getElementById('no-cookie-warning');q.style.display = 'block';
        }
      });
  //]]>
  </script>
  <div id="trk_captcha_js" style="background-image:url('/cdn-cgi/images/trace/captcha/nojs/h/transparent.gif?ray=683cabc82a363157')"></div>
</form>

  <script type="text/javascript">
    //<![CDATA[
    (function(){
        var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent);
        var trkjs = isIE ? new Image() : document.createElement('img');
        trkjs.setAttribute("src", "/cdn-cgi/images/trace/managed/js/transparent.gif?ray=683cabc82a363157");
        trkjs.id = "trk_managed_js";
        trkjs.setAttribute("alt", "");
        document.body.appendChild(trkjs);
        var cpo=document.createElement('script');
        cpo.type='text/javascript';
        cpo.src="/cdn-cgi/challenge-platform/h/b/orchestrate/managed/v1?ray=683cabc82a363157";
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
    //]]>
    </script>



              </div>
            </div>

            <div class="cf-column">
              <div class="cf-screenshot-container">

                <span class="cf-no-screenshot"></span>

              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>

            <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>


            <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>

            <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>



          </div>
        </div>
      </div>


      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">683cabc82a363157</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 59.53.221.132</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
</div>


    </div>
  </div>

  <script type="text/javascript">
  window._cf_translation = {};


</script>


</body>
</html>
]！请前往 [https://github.com/XIU2/CloudflareSpeedTest] 更新！ ***

完整测速结果已写入 result.csv 文件，请使用记事本/表格软件查看。
按下 回车键 或 Ctrl+C 退出。

**Comment by China-Huanghe** [comment]
就显示这些东西

**Comment by XIU2** [comment]
这是 Cloudflare 的质询，即 Cloudflare 怀疑是机器人，需要真人验证。
你重新拨号换个 IP 试试。

另外不需要每次都去测速一遍，可以使用 `-v` 参数来主动检查更新。
```
CloudflareST.exe -v
```

**Comment by XIU2** [comment]
我又改了下 Cloudflare 的防火墙规则，你重新拨号后再试试~

**Comment by China-Huanghe** [comment]
不是很清楚怎么重新拨号，公司的网络，

**Comment by XIU2** [comment]
那你就重新检测一下版本。

另外不需要每次都去测速一遍，可以使用 `-v` 参数来主动检查更新。
```
CloudflareST.exe -v
```

**Comment by 2832167832** [comment]
我是广电的网，把tll设为100那么延迟就会在100，我怀疑也是假的

**Comment by XIU2** [comment]
@2832167832 那就继续调高，或者加上 `-sl 1` 参数来排除下载速度低于 1 MB/s 的 IP。

**Comment by cxw620** [comment]
> 因为很多人被假蔷勒索，然后它们套 Cloudflare 来抵御假蔷，结果就是 Cloudflare 大量 IP 被假蔷。 虽然被假蔷的 IP 很快就会解封，但是因为假蔷勒索泛滥，导致一直有新的 Cloudflare IP 被假蔷。
> 
> 最近发现 Cloudflare 被假蔷的 IP 似乎越来越多了，因此在大家的建议下加了个 `[平均延迟下限]` 参数~
> 
> ## # 区分假蔷
> * **假蔷 IP 的表现特征：**
>   _Ping 延迟**正常**，TCPing 延迟**异常的低**，下载速度为 `0.00`（或约等于 0，即不可用）。_
>   _`即 TCPing 延迟远低于 Ping 延迟。`_
> 
> ## # 使用方法
> ### # 电信/联通用户
> 因为**除了移动**(直连香港) 外，电信/联通几乎不存在 TCPing 延迟低于 100ms 的 IP，因此低于 100ms 的 IP 可以确定为被假蔷了。
> 
> > 具体 TCPing 延迟多少往往取决于你到国际网络出口处（北京、上海、广州）多远，因为蔷是在出口处进行 TCP 劫持的。
> 
> ```shell
> # 平均延迟下限：100 ms 
> ./CloudflareST -tll 100
> CloudflareST.exe -tll 100
> 
> # 平均延迟上限：300 ms，平均延迟下限：100 ms 
> ./CloudflareST -tl 300 -tll 100
> CloudflareST.exe -tl 300 -tll 100
> 
> # 平均延迟下限和其他的上下限参数一样，都可以单独使用、互相搭配使用！
> ```
> 
> ### # 移动用户
> 因为**移动直连香港**的原因，测出来的香港节点的 IP 延迟也很低，和 TCPing 延迟很低的假蔷 IP **混在一起难以区分**，不能简单通过延迟下限来过滤了，因此需要加上 `-sl` 参数(**下载速度下限**) 来过滤掉同样延迟低但实际不可用的假蔷 IP。
> 
> ```shell
> # 下载速度下限：1 MB/s
> ./CloudflareST -sl 1
> CloudflareST.exe -sl 1
> 
> # 平均延迟上限：300 ms，下载速度下限：1 MB/s
> ./CloudflareST -tl 300 -sl 1
> CloudflareST.exe -tl 300 -sl 1
> 
> # 移动用户注意不要使用 -tll 参数（延迟下限），除非你不想要香港节点~
> # 被假蔷的 IP 下载速度基本为 0.00（或 0.0X 忽略不计），所以可以用下载速度来过滤掉不可用的假蔷 IP
> ```

提供个参考数据: cf香港节点正常没有Re-routed的时候, 移动实测都是四五十ms, 坐标粤西, 测速时间一般是凌晨, 移动300M家宽.

**Comment by XIU2** [comment]
去年墙就已经修复 “假墙” 漏洞了，这个 Issues 忘记关了。。。
