### ISSUE TITLE
能够增加一个 DNSPOD API 自动更新域名解析的功能么

### ISSUE THREAD

**Issue by 91270** [XIU2/CloudflareSpeedTest#112]
想实现 同一个域名 电信 联通 移动 三种线路定时选用最快速度的 IP

**Comment by XIU2** [comment]
这个软件只负责测速并输出结果。
对于这种需求，都由独立的脚本去完成（就像我写的其他脚本一样）。

不过我没有 DNSPOD 账号（也不想去实名注册什么的），所以没有去写 DNSPOD API 的脚本。
