### ISSUE TITLE
初步筛选的时候是不是没找对ip段

### ISSUE THREAD

**Issue by fredericky123** [XIU2/CloudflareSpeedTest#114]
我用better-cloud-ip 找的结果延迟大概都在50ms左右，可惜一次只能找一个，
这个工具能一次找20个满足需求，可是找出来的延迟偏高，所以在初步筛选的时候是不是没找对ip段
![image](https://user-images.githubusercontent.com/13982749/131212041-be1954f3-0050-424b-984e-17d91393fa88.png)

**Comment by XIU2** [comment]
我这软件是针对所有 Cloudflare CDN IP 段，对每个 IP 段的最后一段进行随机（x.x.x.0-255），所以每次测速结果都不相同。

不过，我筛选掉了一些回源 IP（这类 IP 是专门访问源站的），你可以尝试把 `ip.txt` 里的 IP 段替换为完整 IP 段：

```
1.1.1.0/24
1.0.0.0/24
1.1.1.1/32
1.0.0.1/32
103.21.244.0/22
103.22.200.0/22
103.31.4.0/22
104.16.0.0/13
104.24.0.0/14
108.162.192.0/18
131.0.72.0/22
141.101.64.0/18
162.158.0.0/15
172.64.0.0/13
173.245.48.0/20
188.114.96.0/20
190.93.240.0/20
197.234.240.0/22
198.41.128.0/17
```

**Comment by fredericky123** [comment]
> 我这软件是针对所有 Cloudflare CDN IP 段，对每个 IP 段的最后一段进行随机（x.x.x.0-255），所以每次测速结果都不相同。
> 
> 不过，我筛选掉了一些回源 IP（这类 IP 是专门访问源站的），你可以尝试把 `ip.txt` 里的 IP 段替换为完整 IP 段：
> 
> ```
> 1.1.1.0/24
> 1.0.0.0/24
> 1.1.1.1/32
> 1.0.0.1/32
> 103.21.244.0/22
> 103.22.200.0/22
> 103.31.4.0/22
> 104.16.0.0/13
> 104.24.0.0/14
> 108.162.192.0/18
> 131.0.72.0/22
> 141.101.64.0/18
> 162.158.0.0/15
> 172.64.0.0/13
> 173.245.48.0/20
> 188.114.96.0/20
> 190.93.240.0/20
> 197.234.240.0/22
> 198.41.128.0/17
> ```
> 
> > 这些就是 Cloudflare 公开的所有 IP 段了。

明白了，所以测速的时候是随机选的ip，better cloud ip会默认记录大家的位置信息，所以可能基于人人为我我为人人的方式会快点

**Comment by XIU2** [comment]
因为 CDN IP 太多，不可能全部测速一遍~
所以选择的是对每个 IP 段随机一个，这样等于说要测速的数量降低了 255 倍。

我简单看过 better cloud ip，它好像是每次测速完，都会上传记录你的信息到数据库中，然后下一个同地区的人去测速就会在一定 IP 范围内去测速，这样会快点，但是很多人可能对隐私比较敏感，而且设计后端什么的总体挺麻烦的~

****

另外，你是移动吗？只有移动才有低延迟的 Cloudflare CDN IP（直连香港线路，电信联通都绕道）。
你把你说的 50ms 的 IP 发给我看看。

你也可以把你的这个 IP 段（`x.x.x.x/24`）单独写入 `1.txt` 文件中，然后测速的适合指定该 IP 段试试：
```
CloudflareST.exe -f 1.txt
```

**Comment by fredericky123** [comment]
哦哦 指定ip段倒是个方法
我是教育网
104.19...这一段很友好

**Comment by XIU2** [comment]
嗯，我这个软件是先按丢包率排序的，再按延迟排序的，然后按照延迟从低到高顺序去下载测速，最后按下载速度排序的。

因此我也遇到过一些延迟很低，但是伴随着丢包的 IP 段（日本），因此平时都被排序到后面去了（当然因为丢包的原因，下载速度就一般了），不过这个日本 IP 段我公开后，每过两个月就被 Cloudflare 限制使用了。。。

后来我也找到过其他延迟低一点的 IP 段，干脆就直接另起个文件专门记录这些 IP 段，随后我测速时都是指定这个 IP 段文件的。

不过同一个 IP 不同运营商天差地别，基本上没有参考价值，找别人测试过后，就只是自用了。。。

****

注意两个段的要这样写 `104.19.0.0/16` ，三个的是这样 `104.19.xxx.0/24` 。
如果是 /24 的 IP 段，还可以选择加上 `-allip` 来测速该 IP 段的全部 IP。

**Comment by fredericky123** [comment]
好的，感谢！确实得每人自备一个IP段~

**Comment by XIU2** [comment]
总之长期使用下，总会发现一些对自己相对友好的 IP 段，这些 IP 段都很有局限性，别的运营商就算了，别的地区的人用可能根本感觉不出来哪里好。

所以慢慢的，收藏几个对自己友好的 IP 段还是很有必要的~

****

没其他问题的话，这个 Issues 就先关闭了，如果后续有其他问题可以继续在下面回复~

**Comment by fredericky123** [comment]
您好，再问下哈，我平时筛选出来的ip有这几个：104.19.203.217、104.19.196.192、104.19.197.76、 104.19.196.197，所以这个ip段应该怎么写哈

**Comment by XIU2** [comment]
@fredericky123 
```
104.19.196.0/24
104.19.197.0/24
104.19.203.0/24
```
> 只有这三个 IP 段的话，默认是每个 IP 段随机一个 IP（共 3 个），太少了点。。。
> 因此建议加上 `-allip` 参数来测速这三个 IP 段的全部 IP（即 256 * 3 = 768 个 IP）

或者容错率高一点，选择更高一级的 IP 段：
```
104.19.0.0/16
```

**Comment by fredericky123** [comment]
好嘞，感谢感谢！
