### ISSUE TITLE
建议增加检查指定域名的可用性

### ISSUE THREAD

**Issue by BugKun** [XIU2/CloudflareSpeedTest#117]
使用该工具筛选出来的ip服务器并不能覆盖全部的cloudflare服务。
例如：`www.example.com`使用cloudflare加速，但是实际上cloudflare只分配了部分服务器来给该网站加速，这导致如果筛选出来的ip刚好不支持该网站的加速的话，反而会造成无法使用。
虽然可以使用`-url`测速参数来进行筛选，但如果这个网站没有足够大的文件来测速的话，那么测速功能就没用了。
建议新增个检查指定域名的可用性的功能

**Comment by XIU2** [comment]
我没有遇到过你说的情况，请举个实际的例子（域名 及 可用/不可用的 IP）。

**Comment by XIU2** [comment]
另外，**如果**确实有这种情况。
那么你是为了给**自己的域名**自选 IP 的话，也可以在自己的网站下**放个大文件**呀。
```
cd 进入你要存放大文件的目录下，然后执行下面的代码就能生成一个 500MB 的文件，但不会实际占用硬盘大小。
dd if=/dev/zero of=file bs=1M count=0 seek=500
```
还是说你想要给**别人的域名**做自选 IP？这是为了什么？加速访问别人的网站？
****
我平时都是依靠 [3Proxy](https://github.com/XIU2/CloudflareSpeedTest/discussions/71) 来实现访问任意使用 Cloudflare CDN 的网站都会被**重定向到自选 IP**，来达到加速访问的目的。
> 所有访问 Cloudflare CDN IP 的 TCP 链接都会被 3Proxy 重定向到自选 IP。
我用了这么长时间，平时访问使用 Cloudflare CDN 的网站**没有一千也有好几百个**了，从来没有遇到过哪个网站无法通过该**自选 IP** 访问的情况。

**Comment by BugKun** [comment]
没有特意去记录是什么IP。我是想优化别人网站的访问速度，以前我还是用[better-cloudflare-ip](https://github.com/badafans/better-cloudflare-ip)时遇到过筛选出来的部分ip服务无法用于`notion.so`。问题的现象是，访问的是`https://www.notion.so`，但实际出现的确实别的网站

**Comment by BugKun** [comment]
感觉像是cloudflare的某些ip服务是部分网站专享的

**Comment by XIU2** [comment]
我用自选 IP 访问 notion 这个网站正常，我看左上角的网站 LOGO 确实是 notion。
没有实际例子的话，我无法确定你说的情况是否存在。

**Comment by BugKun** [comment]
或者等遇到了，我再来开issue吧，我先关掉这个。
