### ISSUE TITLE
当测速结果 IP 数量为 0 时，脚本应该退出

### ISSUE THREAD

**Issue by 10362227** [XIU2/CloudflareSpeedTest#119]
[信息] 延迟测速结果 IP 数量为 0，跳过下载测速。
[信息] 完整测速结果 IP 数量为 0，跳过输出结果。

旧 IP 为 104.17.245.69
新 IP 为 

开始备份 Hosts 文件（hosts_backup）...
开始替换...
完成...`

因为网络抽风或者其他不明原因，某次运行延迟测速结果IP数量为 0，这样导致为新ip为空，然后这个空内容替换掉了旧ip，这样hosts里面就只有域名了，nowip.txt也是空的了，下次再运行时永远都没法替换到新ip了

**Comment by XIU2** [comment]
更新脚本了，做了个是否为空的判断。

不过蓝奏云后台登录挂了导致暂时无法更新，其他地方都更新了（Releases、脚本地址）。
