### ISSUE TITLE
希望能增加cloudflare ipv6 cdn的测速

### ISSUE THREAD

**Issue by miaopasimiao** [XIU2/CloudflareSpeedTest#12]

**Comment by XIU2** [comment]
目前并不支持 IPv6 的 IP 段解析及 TCPing。

我这边也没有环境测试，再加上我也只是产生需求后自己临时学的半吊子技术。

所以短时间是不会添加支持 IPv6 的，抱歉。如果哪天支持了，我会告诉你的。

**Comment by XIU2** [comment]
稍微研究了下，目前解决了 IPv6 的延迟测速（TCPing）、下载测速问题。
正在研究如何更好的解析 IPv6 IP段，主要是 IPv6 太特么多了。。。导致解析效率极低。

**Comment by XIU2** [comment]
比如 `2606:4700::/32` 就有 42 亿个 IP
比 IPv4 多太多了，这我就不知道该如何选择一个合适的数量。。。

**Comment by XIU2** [comment]
另外我还发现，Cloudflare IPv6 也不是所有都能用的，还有很多根本是空置的。

**Comment by XIU2** [comment]
## v1.3.6
1. **新增** IPv6 支持（延迟测速+下载测速）。  
`因为 IPv6 IP 太多了（约 294 亿），而且 Cloudflare CDN 目前只用了极小一部分（约 400 万），所以目前是采用 IP 段子网随机测速。`
`因为 Cloudflare 没有提供当前正在使用的 IPv6 IP段（绝大部分为闲置状态），所以 ipv6.txt 文件内并不是全部 IP 段，但也差不多了。`

**Comment by XIU2** [comment]
@miaopasimiao @huyz-git 
如果没什么问题的话，就关闭该 Issues 吧。

**Comment by miaopasimiao** [comment]
感谢大佬！！！ ！！！！！
