### ISSUE TITLE
报个bug

### ISSUE THREAD

**Issue by yaott2020-666** [XIU2/CloudflareSpeedTest#123]
当使用 ./CloudflareST -ipv6 -f ips-v6 时，测速延迟测试完成结果ip为0

当使用 ./CloudflareST -f ips-v6 -ipv6 时 一切正常

**Comment by XIU2** [comment]
你用的 ipv6 数据文件是我提供的 ipv6.txt 内容吗？
如果不是的话，就很容易出现**测速延迟测试完成结果 IP 为 0** 的情况。
原因我在这里说过了： #120
