### ISSUE TITLE
WIN11 下无法测速，结果都是0MB

### ISSUE THREAD

**Issue by idragonet** [XIU2/CloudflareSpeedTest#127]
相同的命令之前Win10下好好的，而且界面也不显示测试限制速度。

**Comment by idragonet** [comment]
# XIU2/CloudflareSpeedTest v1.5.1

CloudflareST.exe -tll 100 -tl 200 -sl 5 -dn 10

开始延迟测速（模式：TCP IPv4，端口：443，平均延迟上限：200.00 ms，平均延迟下限：100.00 ms）：
19740 / 19740 [-----------------------------------------------------------------------------------------------] 100.00%
开始下载测速（下载速度下限：5.00 MB/s，下载测速数量：1，下载测速队列：1）：
0 / 1 [_________________________________________________________________________________________________________] 0.00%
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
104.26.15.150     4       4       0.00    164.02    0.00

完整测速结果已写入 result.csv 文件，请使用记事本/表格软件查看。
按下 回车键 或 Ctrl+C 退出。

**Comment by idragonet** [comment]
CloudflareST.exe -tl 180 -tll 100

测试完毕延迟直接退出。

**Comment by XIU2** [comment]
你提供的信息中看起来都很正常。

2L 说的，下载测速如果没有一个满足速度条件的，会直接输出了结果。

3L 说的，可能是你把延迟上限设置的太低了？找不到满足条件的 IP 就会输出 0 个直接退出。

**Comment by idragonet** [comment]
> 你提供的信息中看起来都很正常。
> 
> 2L，延迟测速后只有 1 个 IP 满足延迟条件，然后下载测速如果没有一个满足速度条件的，会直接输出结果。
> 
> 3L，可能是你把延迟上限设置的太低了？找不到满足条件的 IP 就会输出 0 个直接退出。

看来似的，想不到晚上CF线路这么糟糕了。

**Comment by XIU2** [comment]
既然不是 BUG 的话，那我就关闭该问题啦。
