### ISSUE TITLE
请问手机上新建的CloudflareST文件夹在哪能找到

### ISSUE THREAD

**Issue by gcphym** [XIU2/CloudflareSpeedTest#128]
mkdir CloudflareST之后在手机上用文件管理器找不到

**Comment by XIU2** [comment]
如果你看的是我写的那个教程，那么你是不可能再手机文件管理器里找到的。
因为文件都在虚拟机中。

**Comment by gcphym** [comment]
> 如果你看的是我写的那个教程，那么你是不可能再手机文件管理器里找到的。 因为文件都在虚拟机中。

原来如此 明白了 那可以在手机存储里运行吗 我刚刚 termux-setup-storage 挂载手机存储后 创建storage/shared/termux/CloudflareST 运行脚本提示permission denied

**Comment by XIU2** [comment]
没有权限就赋予权限呗。

不过我对你说的这些操作不熟，那个教程我写完就没在手机上用过了（没这个需求）。。。

**Comment by gcphym** [comment]
> 没有权限就赋予权限呗。
> 
> 不过我对你说的这些操作不熟，那个教程我写完就没在手机上用过了（没这个需求）。。。

谢谢
