### ISSUE TITLE
win10-64 指定参数运行报错

### ISSUE THREAD

**Issue by cnp2nx** [XIU2/CloudflareSpeedTest#129]
C:\Users\lih\Desktop\CloudflareST_1.5.1>CloudflareST.exe -f ip1.txt
2021/11/11 23:37:45 invalid CIDR address: /32

先感谢作者提供这么好用的工具让我的垃圾vps可以起飞！使用了快一个月，之前一直可以指定参数运行，昨天开始突然不行了，很奇怪。另外不加参数是可以正常运行的。

**Comment by XIU2** [comment]
应该是你的 ip1.txt 的格式问题，把内容贴出来我看看。

**Comment by cnp2nx** [comment]
感谢您的回复！我找到问题了，是txt文件的格式问题，下面不能有空行，我之前是隔几天选一个最快的手工输入到ip1.txt文件里，后来测速有好几个速度快的，就打开csv文件复制粘贴到txt文件，然后就出问题了。另外我移动宽带选出来的都是香港的ip，联通手机选出来的大多是洛杉矶的，有时候是欧洲的。

**Comment by XIU2** [comment]
因为只有移动直连 Cloudflare 的香港节点，其他运营商都绕道。
而联通的话，确实会分配到美西或德国（可能是因为德国是直连的）。
