### ISSUE TITLE
IPV4出来的下载速度基本都是0，IPV6速度也没有上个版本快，联通宽带

### ISSUE THREAD

**Issue by fschenkun22** [XIU2/CloudflareSpeedTest#133]
![image](https://user-images.githubusercontent.com/13625213/142242122-6a3ae027-d8f6-4a9f-9913-4b48749c34cb.png)

**Comment by silver-gin** [comment]
延迟下限改成100试试

**Comment by XIU2** [comment]
你遇到的是被假蔷的 IP，这些 IP 都在出口处被 TCP 劫持了，所以延迟异常的低（延迟=你到出口处的距离）。
如楼上所说及 #111 ，我当初特意加上平均延迟下限就是为了过滤假蔷。
你加上 `-tll 100` 参数试试。

**Comment by fschenkun22** [comment]
加上 ~~~ -tll 100确实好使了，但是感觉没有以前的IP质量好 ，感谢 ，我再试试

**Comment by XIU2** [comment]
Cloudflare 质量好坏就不是我能控制的啦~

质量下降的主要原因之一，就是最近泛滥的**假蔷**。
很多站长被假蔷勒索，选择套免费的 Cloudflare CDN 轮询抵御，结果就是 Cloudflare 的 IP 大量被假蔷，虽然过段时间会自动解封的，但是解封速度不足以抵消假蔷速度。。。
源源不断 CDN IP 的被假蔷，代表始终有一部分 CDN IP 是不可用的状态。
