### ISSUE TITLE
请增加一个http-header命令选项，在测试下载时能发送指定http header

### ISSUE THREAD

**Issue by karma-sun** [XIU2/CloudflareSpeedTest#134]
请增加一个http-header命令选项，在测试下载时能发送指定http header

**Comment by XIU2** [comment]
不是很有必要~

**Comment by silver-gin** [comment]
自己自定义一个下载地址应该就行了

**Comment by ljxfstorm** [comment]
虽然有点偏离主题，不过把下载地址提出一个配置文件可以自定义确实是个不错的主意。
这样只要定制ip.txt、ipv6.txt和下载地址，就可以适用于其他CDN的测速了，完全不用限定于Cloudflare。
进一步说，将测试下载URL、CDN IPv4、IPv6地址段列表，整合成一个资源文件，就是一个泛用的CDN测速优选工具了。
不过这里面涉及测试下载URL对应内容的一个约束，需要是一个适合用于测速场景的文件。

**Comment by XIU2** [comment]
@ljxfstorm 然而并不是所有 CDN 都像 Cloudflare 这样域名可以指向任意 CDN IP 去访问。
比如亚马逊的 CDN 你就不能乱指向其他 CDN IP。

而且你这种需求，不需要修改 CloudflareST，当前就可以完全实现。
你说的这些（下载测速地址、IP 数据）都有相应的参数可以指定。

**Comment by silver-gin** [comment]
> 

你这一个快捷方式定好参数就可以搞定了

**Comment by ljxfstorm** [comment]
> @ljxfstorm 然而并不是所有 CDN 都像 Cloudflare 这样域名可以指向任意 CDN IP 去访问。 比如亚马逊的 CDN 你就不能乱指向其他节点的 IP。
> 
> 而且你这种需求，不需要修改 CloudflareST，当前就可以实现。 你说的这些（下载测速地址、IP 数据等）都有相应的参数可以指定。
> 
> 简单的就直接把这些内容写到各个文件里，然后指定参数去运行。 复杂点就自己写个脚本，来自动化处理（就像你说的配置文件方式）。
> 
> CloudflareST 是一个测速工具，**也只会是一个测速工具**，很多需求我是不会将其加到 CloudflareST 里的，因为对于命令行程序来说，完全可以和任意软件/脚本进行**对接、扩展、增强、配合**等等。

嗯，我们的理解其实没有分歧。
我主要想表达的是，将URL、IP List这些作为资源文件剥离出去维护，成为一个泛用工具，而不是把CloudflareSpeedTest通过命令行参数Override成一个其他SpeedTest。
不过其实最后达成的效果其实是一样的。

**Comment by XIU2** [comment]
@ljxfstorm 
emmm **URL、IP List 这些资源文件** 不是本来就是剥离出去维护的吗？又没有写死在程序里。。。
