### ISSUE TITLE
都是测下载的，有测速上传的吗？

### ISSUE THREAD

**Issue by f4nff** [XIU2/CloudflareSpeedTest#137]
post指定文件，测速上行速度？
支持一下？

**Comment by XIU2** [comment]
测速上传的话，我的服务器顶不住流量消耗。
目前下载测速的话，99.9% 的流量都被 Cloudflare 缓存了，所以我的服务器没什么感觉，但是上传的话就没办法缓存了。

**Comment by f4nff** [comment]
测速上行很简单

POST http://api.cloudflare.com/cdn-cgi/trace

即可。

**Comment by XIU2** [comment]
这个需求比较窄，我不是很感兴趣，最主要是添加这个功能需要改的地方挺多的，工作量还挺大。。。
