### ISSUE TITLE
为什么用ipv6测试模式测试出来的是ipv4的ip？

### ISSUE THREAD

**Issue by Lemonawa** [XIU2/CloudflareSpeedTest#138]
![图片](https://user-images.githubusercontent.com/69106050/144704682-9342da8f-337d-44eb-ae4f-fba1664386b5.png)

**Comment by XIU2** [comment]
因为你没有按照我给的使用姿势去做。。。
```
-ipv6
        IPv6测速模式；确保 IP 段数据文件内只包含 IPv6 IP段，软件不支持同时测速 IPv4+IPv6；(默认 IPv4)
```
https://github.com/XIU2/CloudflareSpeedTest#-ipv4ipv6
```
# 测速 IPv6 时，需要指定 IPv6 数据文件( ipv6.txt )，需要加上 -ipv6 参数
CloudflareST.exe -f ipv6.txt -ipv6
```
