### ISSUE TITLE
最近的2.02版本每次测试都是差不多的结果000

### ISSUE THREAD

**Issue by zhe1253** [XIU2/CloudflareSpeedTest#139]
开始延迟测速（模式：TCP IPv4，端口：443，平均延迟上限：9999 ms，平均延迟下限：0 ms)
4935 / 4935 [-------------------------------------------------------------------------------------------------] 100.00%
开始下载测速（下载速度下限：0.00 MB/s，下载测速数量：10，下载测速队列：10）：
10 / 10 [-----------------------------------------------------------------------------------------------------] 100.00%
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
104.21.19.46      4       4       0.00    19.42     0.00
104.19.192.250    4       4       0.00    20.18     0.00
104.17.37.54      4       4       0.00    20.42     0.00
104.17.170.172    4       4       0.00    20.80     0.00
104.16.150.203    4       4       0.00    21.73     0.00
162.159.218.5     4       4       0.00    21.97     0.00
104.18.246.144    4       4       0.00    22.54     0.00
104.19.165.159    4       4       0.00    22.88     0.00
172.64.85.29      4       4       0.00    23.91     0.00
104.21.21.231     4       4       0.00    24.25     0.00

**Comment by XIU2** [comment]
你是移动吗？（移动直连香港节点）
如果不是，那这些都是被假蔷的 IP。

**Comment by XIU2** [comment]
看一下 #111

**Comment by zqhGeek** [comment]
我的是

> 看一下 #111 这个置顶的 Issues（我都置顶了都还看不到么，心累。。。
> 
> 项目介绍 - 快速使用中也写了。 `# 如果延迟很低 (几十ms)，且你也不是移动 (香港直连)，那么你就是遇到假墙 IP 了，记得加上 -tll 参数。`

我的是广东联通，使用参数后是没有IP，不使用参数后，拿到的IP不可用
