### ISSUE TITLE
Supports homebrew installation

### ISSUE THREAD

**Issue by YeungKC** [XIU2/CloudflareSpeedTest#14]

**Comment by XIU2** [comment]
Please describe it clearly, I don't understand. . .

**Comment by YeungKC** [comment]
I hope to install this project on homebrew.
Related documents: https://brew.sh/index_zh-cn

**Comment by YeungKC** [comment]
It would be very convenient to use GitHub action to publish to homebrew.

Related article: https://extrawurst.medium.com/github-actions-homebrew-%EF%B8%8F-2789ae5023fd

**Comment by XIU2** [comment]
The project is written in Go language, and the compiled binary executable file is a separate file without any dependencies.  
It can be used directly after downloading and decompressing.  
It seems that it is not necessary to add it to the package manager.

**Comment by YeungKC** [comment]
If you are simply using it now, it may not be necessary to support homebrew installation.

But tracking updates, or managing environment variables, or package management, support for homebrew will improve the user experience considerably.

**Comment by XIU2** [comment]
Because I don't have MAC system equipment, I don't know much about MAC system.  
Although I have released the MAC version, I have not actually tested it under the MAC system (only tested under the Windows and Linux environments). Although I saw some people downloaded the MAC version...

**Comment by XIU2** [comment]
After simple statistics, the proportion of users of the MAC system version is only 7-8%.  
Sorry, I'm lazy~  
The demand is too small and I don’t have enough motivation to do it~

**Comment by Mrered** [comment]
我做了一个，纯小白水平，目前只支持 `arm64` 版，有时间了做 `amd64` 。
I made new one! But only support `arm64/Apple Silicon` instead `amd64/Intel`. When I have time, I will make an `amd64/Intel` version support.

安装方式：
How to install:

```shell
brew install mrered/cloudflarest/cfstarm64
```

**Comment by Mrered** [comment]
#372
