### ISSUE TITLE
测试结果下载速度2万M/s!!!

### ISSUE THREAD

**Issue by defeatd** [XIU2/CloudflareSpeedTest#141]
win11系统，移动宽带，测试结果如图，第一个下载速递24436.29M/s
![585e14a5bf426007782fa003c2c325c](https://user-images.githubusercontent.com/65989699/145723443-c2e2bbd5-750c-4d54-8754-b1597d8c40ca.png)

**Comment by XIU2** [comment]
能稳定复现吗？

**Comment by XIU2** [comment]
已更新 v2.2.1 版本，修复 一些情况下下载测速数值过大的问题，有兴趣的话你可以试试。
https://github.com/XIU2/CloudflareSpeedTest/releases/tag/v2.2.1
