### ISSUE TITLE
Excel表格头乱码

### ISSUE THREAD

**Issue by willaytoun** [XIU2/CloudflareSpeedTest#142]
![image](https://user-images.githubusercontent.com/43229736/145746290-6cf47627-34a9-453a-a0c8-742ccb80061b.png)

**Comment by XIU2** [comment]
软件默认是以 UTF-8 通用格式输出结果文件的。
乱码说明你用的表格程序不支持 UTF-8 通用格式，或者说识别有问题。
你用记事本打开就会发现显示正常。
