### ISSUE TITLE
cloudflare优质ip会不会像谷歌ip那样被耗尽

### ISSUE THREAD

**Issue by dgfrwx** [XIU2/CloudflareSpeedTest#145]
会不会再过段时间就没有好ip了越来越卡了，就像以前goagent和xxnet那样

**Comment by XIU2** [comment]
Cloudflare 的都是 Anycast IP，每个 IP 的实际路由、归属地都不是固定的，会动态变化。
自选只是为了找到当前最适合自己的 IP，但这个 IP 也仅仅适合于当前网络下，对其他地区、其他运营商的用户而言质量就一般了。

**Comment by tec1987** [comment]
Google IP从来没有耗尽过。。。只不过技术更新后很少有人通过Google代理过墙了

**Comment by qnxsgwy** [comment]
Google IP从来没有耗尽+1，只要你有钱用GCP优质线路，网速依旧快到飞起
