### ISSUE TITLE
软路由openwrt上解压总报错 

### ISSUE THREAD

**Issue by rockmetalcn** [XIU2/CloudflareSpeedTest#148]
wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.0.2/CloudflareST_linux_arm64.tar.gz
root@OpenWrt:/CloudflareST# tar -zxf CloudflareST_linux_arm64.tar.gz
tar: invalid tar magic

在软路由上解压总报错 压缩格式问题 帮忙看一下啊 谢谢！

**Comment by XIU2** [comment]
我在我的 Linux 服务器上面运行解压命令测试正常。

**Comment by XIU2** [comment]
不排除是你 OpenWrt 上的 tar 解压缩工具的问题。

**Comment by rockmetalcn** [comment]
感谢回复 我试试看

**Comment by XIU2** [comment]
提醒一下：国内下载的话，建议把上面 URL 中的 `github.com` 替换为 `download.fastgit.org` 以避免下载失败~

**Comment by rockmetalcn** [comment]
谢谢 已解决 
opkg upgarde tar
果然是tar工具的问题
