### ISSUE TITLE
扫描结果不准确

### ISSUE THREAD

**Issue by zhezhe168** [XIU2/CloudflareSpeedTest#15]
cloudflare使用的ssl协议在部分电脑上不支持，软件就扫不出来，希望改进通过https的证书来识别cloudflare，结果更精确

**Comment by XIU2** [comment]
这要是多老的电脑才不支持？

**Comment by zhezhe168** [comment]
和电脑没关系，应该是系统环境问题

**Comment by XIU2** [comment]
没有见过这种问题，请提供相关复现步骤，或者相关系统环境。  
如果只是小众环境，那就算了。

**Comment by XIU2** [comment]
另外，我无法理解你说的：通过https的证书来识别cloudflare 是什么意思。

**Comment by XIU2** [comment]
看了下，目前 Cloudflare 用的是 `TLS 1.3` ，属于目前主流且推荐的 TLS 协议版本。  
基本上除了古老的系统外，都支持 `TLS 1.3`，所以软件并不会去特意支持这种古老的系统。  

目前软件的下载测速是对**测速地址域名指定 IP 访问下载文件**，使用低版本的 TLS 协议可能会无法连接，而且不符合安全规范。

**Comment by zhezhe168** [comment]
比如这个ip 35.200.109.86 ，实测速度很快，结果不在扫描结果中

**Comment by XIU2** [comment]
我前面说了，软件是先测速延迟，再根据延迟排序（从低到高），然后再根据延迟排序结果从低到高去下载测速。  
延迟低的不一定速度快，但是延迟低的出现速度快的概率更高。  

你说的这种情况，可以通过启动参数设置条件来解决。
```
# 启动参数中加入这三个参数，分别是 200ms、5MB/s、10个。
# 只有同时满足这三个条件的 IP 才会显示出来
# 即这个 IP 延迟要低于 200ms，下载速度高于 5MB/s，凑够 10 个才会结束。
-tl 200 -sl 5 -dn 10
```

**Comment by zhezhe168** [comment]
不是的，你可以试试在ip.txt只添加这一个ip段，202.81.235.92/25，中间的ip 202.81.235.92这个是实测过的，而且80和443端口都开着，但软件扫不到

**Comment by XIU2** [comment]
你这两个 IP 是从来找的？Cloudflare 公开的所有 IP 段里并没有这两个 IP。

https://www.cloudflare.com/ips/

**Comment by zhezhe168** [comment]
cloudflare与运营商有合作，有些ip是运营商的cdn分发，速度也很快，你是不是这个设置了排除cf官方ip段了？

**Comment by XIU2** [comment]
我都不知道有这玩意，怎么可能会特意去排除。

**Comment by XIU2** [comment]
目前软件是只支持 IP 最后一段为 0 的 IP 段，因为最后一位是要随机的。
所以你用这个 202.81.235.92/25 实际上测速时，并不是 .92 而是随机的一个（1~255），所以延迟测速失败。

**Comment by zhezhe168** [comment]
懂了，有没有考虑过逐个ip依次查询

**Comment by XIU2** [comment]
我给改改，改成如果最后一段不是 0，那么就不随机了，保留最后一段。

**Comment by zhezhe168** [comment]
好的，可以在脚本中设置随机扫描或者逐个扫描，实测过程中个别ip其实有运营商加成作用（个别地区移动把这些ip通过内网连到香港移动落地，所以同一个段有时个别ip可以满速而其他ip速度一般）

**Comment by XIU2** [comment]
逐个扫描的话，可能会因为 IP 太多而变得很慢。

**Comment by zhezhe168** [comment]
这个问题不大，我限定ip范围就行，反正比较好的ip1-2个就行

**Comment by XIU2** [comment]
你下载这个试试。
新加了一个 -allip 参数，带上该参数将会测速全部 IP（不带就是每个 IP 段随机一个）。
不带这个参数时，使用 202.81.235.92/25 时将指定为 .92
带这个参数时，使用 202.81.235.92/25 时将指定为 .1~.126

不带这个参数时，如果要每个 IP 段随机一个，则要使用 202.81.235.0/25 

[CloudflareST.zip](https://github.com/XIU2/CloudflareSpeedTest/files/5646641/CloudflareST.zip)

**Comment by zhezhe168** [comment]
不错，试了下，没问题

**Comment by zhezhe168** [comment]
感谢大佬

**Comment by XIU2** [comment]
等我写好检测更新功能就会发布。

> 如果有新版本则会在运行结束时提示，或者使用 -v 来主动检查更新。

**Comment by zhezhe168** [comment]
好的，发现个问题，
由于采用了all ip扫描，有些不支持cf的ip显示速度为0，此时程序根据延迟排序，导致结果有偏差，延迟低的速度为0也就是不支持cf的ip

**Comment by zhezhe168** [comment]
比如，
IP 地址,已发送,已接收,丢包率,平均延迟,下载速度 (MB/s)
109.166.37.113,4,4,0.00,159.65,0.00
109.166.37.30,4,4,0.00,159.65,0.00
109.166.37.123,4,4,0.00,164.05,0.00
109.166.37.71,4,4,0.00,164.05,0.00
109.166.37.18,4,4,0.00,167.45,0.00
109.166.37.111,4,4,0.00,168.45,0.00
109.166.37.15,4,4,0.00,176.25,0.00
109.166.37.37,4,4,0.00,180.90,0.00
109.166.37.27,4,4,0.00,180.90,0.00
109.166.37.4,4,4,0.00,180.90,0.00
109.166.37.118,4,4,0.00,188.95,0.00
109.166.37.124,4,4,0.00,188.95,0.00
109.166.37.98,4,4,0.00,210.20,0.00
109.166.37.29,4,4,0.00,214.10,0.00
109.166.37.63,4,4,0.00,222.15,0.00
109.166.37.73,4,4,0.00,222.15,0.00
109.166.37.75,4,4,0.00,245.80,0.00
109.166.37.79,4,4,0.00,264.40,0.00
109.166.37.112,4,3,0.25,152.80,0.00
109.166.37.21,4,3,0.25,160.20,0.00

要扫的ip结尾是37.88，实际出来上面这些没什么关系的ip

**Comment by zhezhe168** [comment]
建议加上-allip后直接根据速度排序，不考虑延迟，延迟只显示作参考

**Comment by XIU2** [comment]
我前面说了，你设置个过滤条件就能解决。
加个 `-sl 5` 参数，这样就过滤掉 5MB/s 一下的。

我前面说了：
不带这个参数时，使用 202.81.235.92/25 时将指定为 .92
带这个参数时，使用 202.81.235.92/25 时将指定为 .1~.126

**Comment by zhezhe168** [comment]
好的可以，谢谢

**Comment by zhezhe168** [comment]
还有个问题，测速发现如果ip.txt过大会导致内存臃肿，能否考虑逐行读取ip.txt

**Comment by XIU2** [comment]
那样会效率低。

**Comment by XIU2** [comment]
发布正式版本了。

## 更新内容
1. **新增** 测速全部 IP 参数 `-allip`。**#15**   
`带上该参数则会测速每个 IP 段的每个 IP，默认是每个 IP 段随机测速一个 IP。`
2. **新增** 检查版本更新 功能。
`如果有新版本，软件会在运行结束时提示，或者你可以用 -v 参数主动检查版本更新。`

**Comment by felixding** [comment]
> cloudflare与运营商有合作，有些ip是运营商的cdn分发，速度也很快，你是不是这个设置了排除cf官方ip段了？

请问怎么样找到这样的IP列表呢？

**Comment by XIU2** [comment]
@zhezhe168 同问。

如果想要继续帮助项目，希望可以提供这些 IP 段以加到 ip.txt 中~

**Comment by zhezhe168** [comment]
目前批量ip探测没有特别好的方法，还在研究中，个别ip可以，但还是比较费时

**Comment by XIU2** [comment]
@zhezhe168  描述具体点？

**Comment by XIU2** [comment]
@zhezhe168 就像前面说的，如果**不支持 Cloudflare，那么就无法下载测速**，所以你只需要把 IP 段都给加到 `ip.txt`，然后用 `-allip` 全部测速一遍，凡是下载测速 `0.00` 的都是不支持 Cloudflare 的 IP。  
这样就能过滤出来支持 Cloudflare 的 IP 了，这些 IP 往往都是连续的（组成一个 IP 段）。

**Comment by XIU2** [comment]
@zhezhe168 v1.4.4 版本已经完全支持 IP 段 /24~/32 的子网掩码解析了。  
所以如果要测速单个 IP，子网掩码需要是 /32 而不能随便写了。

**Comment by XIU2** [comment]
刚刚更新修复了一个 BUG，你如果在大量扫描 IP 的话，肯定遇到过，就是下载测速卡住的情况。  

修复这个 BUG 后，你再去大量扫描 IP 就会舒服很多了，不用担心卡住了。

****

## v1.4.6 更新内容
1. **修复** 下载测速时间不准确、卡住的问题。  
`意外的注意到下载测速时，可能会遇到实际测速时间超过 -dt 指定的时间，甚至可能会发生下载测速卡住的情况。`

**Comment by huanx9** [comment]
@zhezhe168 开一个TG群探讨一下

**Comment by zhezhe168** [comment]
@huanx9 最近比较忙，抽空我再研究下，目前在研究ws。。。
