### ISSUE TITLE
在 IOS 手机上运行 CloudflareST 的简单教程~

### ISSUE THREAD

**Issue by kanomahoro** [XIU2/CloudflareSpeedTest#151]
经过测试 CloudflareST 可以在 IOS 设备上正常使用。

> 在 **Android 手机**上独立运行 CloudflareST 的教程：#61、#202     

****

## \# 安装 iSH Shell (Linux 微型虚拟机)
在 App Store 中搜索并安装 ` iSH Shell ` App。

<img src="https://user-images.githubusercontent.com/88894099/147058962-d62831b1-a9a2-4887-8c75-21d8b3425405.jpg" width="40%">

下载安装后打开，这时候就会看到熟悉 Linux 系统！接下来就和 Linux 系统上的下载、运行步骤一样了。

****

## \# 安装 CloudflareST

``` yaml
# 下载 CloudflareST 压缩包（必须下载 i386 版本）
wget -N https://download.fastgit.org/XIU2/CloudflareSpeedTest/releases/download/v2.0.3/CloudflareST_linux_386.tar.gz
# 考虑到国内直接从 Github 下载速度很慢，这里替换为镜像站了，如果还是下载很慢/无法下载，那就试试下面这几个镜像：
# wget -N https://gh.xiu.workers.dev/https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.0.3/CloudflareST_linux_386.tar.gz
# wget -N https://ghproxy.com/https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.0.3/CloudflareST_linux_386.tar.gz
# 提示：wget 的 -N 参数是为了下载新版本时（文件名都一样），直接覆盖压缩包文件，避免被重命名加上 .1 后缀
# 如果下载失败的话，尝试删除 -N 参数（如果是为了更新，则记得提前删除旧压缩包 rm CloudflareST_linux_386.tar.gz ）

# 解压
tar -zxf CloudflareST_linux_386.tar.gz

# 赋予执行权限
chmod +x CloudflareST
```

<details>
<summary><strong><code>非必需的创建文件夹步骤...</code></strong></summary>

****

毕竟手机上打字不方便，所以我就**省略了创建文件夹的步骤**，大家有强迫症的可以在安装 CloudflareST **之前**先执行：

``` yaml
# 如果是第一次使用，则建议创建新文件夹（后续更新请跳过该步骤）
mkdir CloudflareST

# 进入文件夹（后续更新时，只需要进入文件夹，然后重复上面那几个下载、解压命令即可）
cd CloudflareST
```
</details>

****

## \# 运行 CloudflareST

``` yaml
# 运行（不带参数）
./CloudflareST

# 运行（带参数示例）
./CloudflareST -dd -tll 90
```
****

## \# 注意事项

- 注意 iSH Shell 这个 Linux 微型虚拟机底层是二进制转译 i686，因此只支持 linux 386 版本的 CloudflareST。
- 所有文件都是安装在虚拟机内的，因此不需要的时候，直接卸载 ` iSH Shell ` 即可，虚拟机内的所有文件也都会被一同删除。

**Comment by XIU2** [comment]
你这排版看着好别扭，我帮你优化下排版吧~

**Comment by pingshu** [comment]
ipad上运行显示I/O error

**Comment by 007xyz** [comment]
大佬，ios还是下载不了

**Comment by github-renhongli** [comment]
？？

**Comment by KAYZZ1** [comment]
为什么不能下载老大

**Comment by asiv580** [comment]
下载命令应该是wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.0.2/CloudflareST_linux_386.tar.gz

**Comment by XIU2** [comment]
@asiv580 没有错，wget 加上 ` -N ` 参数是为了实现**下载新版本时直接覆盖**。

比如你先下载一个 2.0.1 版本的，然后再去下载一个 2.0.2 版本的，不同版本的压缩包文件名都一样。

## \# 不加 ` -N ` 参数

如果不加 ` -N ` 参数，因为文件名一样，所以 wget 会在下载 2.0.2 版本时**重命名压缩包文件**（文件名后面加上 ` .1 `）。

因此还需要提前删除旧压缩包文件，或下载后再删除旧压缩包文件并重命名新压缩包文件。。。

``` bash
root@A:~/# wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.0.1/CloudflareST_linux_386.tar.gz
--2022-01-10 10:59:17--
... ...
Length: 2169371 (2.1M) [application/octet-stream]
Saving to: ‘CloudflareST_linux_386.tar.gz’

CloudflareST_linux_386.tar.gz 100%[=================================================>]   2.07M  --.-KB/s    in 0.06s

2022-01-10 10:59:18 (32.7 MB/s) - ‘CloudflareST_linux_386.tar.gz’ saved [2169371/2169371]



root@A:~/# wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.0.2/CloudflareST_linux_386.tar.gz
--2022-01-10 10:59:24--
... ...
Length: 2170442 (2.1M) [application/octet-stream]
Saving to: ‘CloudflareST_linux_386.tar.gz.1’

CloudflareST_linux_386.tar.gz 100%[=================================================>]   2.07M  --.-KB/s    in 0.05s

2022-01-10 10:59:24 (43.7 MB/s) - ‘CloudflareST_linux_386.tar.gz.1’ saved [2170442/2170442]
```

****

## \# 加上 ` -N ` 参数

如果加上 ` -N ` 参数，wget 会对比本地文件 与 远程文件的时间，如果要下载的文件更新一些，那么即使文件名一样，wget 也会在下载 2.0.2 版本时**直接覆盖**（如果时间一样的话则不会下载，毕竟这也没意义）。

这样就避免了提前删除旧压缩包文件的步骤（或下载后再去重命名的步骤）。

``` bash
root@A:~/# wget -N https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.0.1/CloudflareST_linux_386.tar.gz
--2022-01-10 10:56:23--
... ...
Length: 2169371 (2.1M) [application/octet-stream]
Saving to: ‘CloudflareST_linux_386.tar.gz’

CloudflareST_linux_386.tar.gz 100%[=================================================>]   2.07M  --.-KB/s    in 0.07s

2022-01-10 10:56:24 (30.3 MB/s) - ‘CloudflareST_linux_386.tar.gz’ saved [2169371/2169371]



root@A:~/# wget -N https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.0.2/CloudflareST_linux_386.tar.gz
--2022-01-10 10:56:32--
... ...
Length: 2170442 (2.1M) [application/octet-stream]
Saving to: ‘CloudflareST_linux_386.tar.gz’

CloudflareST_linux_386.tar.gz 100%[=================================================>]   2.07M  --.-KB/s    in 0.06s

2022-01-10 10:56:33 (32.4 MB/s) - ‘CloudflareST_linux_386.tar.gz’ saved [2170442/2170442]
```

**Comment by ventusoon** [comment]
![image](https://user-images.githubusercontent.com/14863512/149669248-ba6e8a0e-b92d-45f5-869e-a79988555ac9.png)
下载速度全是0是什么情况？

**Comment by XIU2** [comment]
@ventusoon 要么你禁用了下载测速（`-dd` 参数），要么你遇到了被假墙的 IP，如果你不是移动，那么请用 `-tll` 参数过滤低延迟的 IP（例如 `-tll 110` 即过滤低于 110ms 的 IP）。
移动直连香港，会遇到低延迟的香港 IP，而电信联通扫到最低延迟的 IP 普遍都是欧美的，延迟最低也不会低于 130ms。

**Comment by ventusoon** [comment]
![image](https://user-images.githubusercontent.com/14863512/149669463-76c051bc-14a2-4530-928a-593edc68e249.png)
关了代理速度还是0

**Comment by XIU2** [comment]
你重复发同一张图没有意义，看我前面说的话。

**Comment by tianchixia** [comment]
![A6AB2475-C460-4E84-883E-CFAAEA573426](https://user-images.githubusercontent.com/71068929/150881110-7b62cc51-4c24-42cb-baea-df3ea46ce003.png)

**Comment by tianchixia** [comment]
苹果手机📱上测试出来的ip速度每次都不到1mb/s，同一个网络下，电脑上测出来的能到10md/s
以上，这是为什么？

**Comment by tianchixia** [comment]
恩，那目前就先在电脑上优先吧，对了，有没有单独测试某一个节点的速度的方法？

**Comment by XIU2** [comment]
@tianchixia https://github.com/XIU2/CloudflareSpeedTest#-单独对一个或多个-ip-测速

**Comment by tgrocp** [comment]
大佬。mac系统怎么用啊

**Comment by XIU2** [comment]
@tgrocp 
和 Linux 差不多啊，下载、解压、赋予执行权限，然后 ./CloudflareST 执行就行了，经常用 MAC 的不应该不知道吧。。。
具体的话我也不清楚，我没有 MAC 设备。

**Comment by tgrocp** [comment]
真的不知道。半桶水啊我，能出个教程吗大神？

**Comment by LYOyoo** [comment]
为啥我下载了解压的时候提示no such file or directory

**Comment by XIU2** [comment]
@LYOyoo 这个报错是找不到压缩包文件，因此有两种可能：
1. 你文件下载失败了，所以找不到压缩包文件。
2. 你下载文件成功了，但是你的解压命令中的文件名写错了。

**Comment by LYOyoo** [comment]
下载失败了，-n去掉就好了

**Comment by 404user** [comment]
学习了，感谢啊。这样在手机上操作就方便多了。

**Comment by z10056** [comment]
> 苹果手机📱上测试出来的ip速度每次都不到1mb/s，同一个网络下，电脑上测出来的能到10md/s
> 以上，这是为什么？

我和你一样 电脑五百兆宽带 小米10和电脑能跑到四五十MB 在这上面只能跑到1MB

**Comment by z10056** [comment]
> Termux

安卓用的是Termux  iOS上除了ish之外找不到其他的Linux虚拟机了 付费的不知道 还有一个utm虚拟机 只不过得用电脑来安装 目前手头上没电脑  哎

**Comment by ElonWang8** [comment]
mkdir: can't create directory 'CloudflareST': File exists

**Comment by ElonWang8** [comment]
您好，我已经收到您发送的邮件。
如果有急事请电话联系，谢谢！
电话：15166611156

**Comment by xinyu2880** [comment]
IOS 怎么修改hosts呢 ？

**Comment by ElonWang8** [comment]
您好，我已经收到您发送的邮件。
如果有急事请电话联系，谢谢！
电话：15166611156

**Comment by fenghengwei** [comment]
ipad上运行显示I/O error

**Comment by TheKing1991** [comment]
苹果安装wget是apk add wget

**Comment by sunshowerstack** [comment]
iOS上测出来最快的ip是给电脑用还是手机用。给电脑用的话作用不大，电脑上直接运行就可以了。如果给流量下的手机用，那怎么写到手机上？在ish里写入/etc/hosts？感觉不靠谱啊

**Comment by Sunbangyan233** [comment]
> IOS 怎么修改hosts呢 ？

去App store下个<b>Stream</b>，首页就有hosts设置，添加后开抓包安装配置信任证书即可。
~~不过是不是有点歪楼了~~

**Comment by LeonLeeLi** [comment]
它提示权限不够
Permission denied

**Comment by LeonLeeLi** [comment]
[![zkcdfO.png](https://s1.ax1x.com/2022/11/14/zkcdfO.png)](https://imgse.com/i/zkcdfO)

**Comment by XIU2** [comment]
@LeonLeeLi 
你是不是漏了 赋予执行权限 的步骤？
```
chmod +x CloudflareST
```

**Comment by lanling175** [comment]
Ios15.4.1 ./CloudflareST 命令一执行就闪退
