### ISSUE TITLE
Mac环境下自动替换脚本报错 sed: 1: "/etc/hosts": extra characters at the end of h command

### ISSUE THREAD

**Issue by Milesians** [XIU2/CloudflareSpeedTest#157]
![image](https://user-images.githubusercontent.com/37968554/147955693-49cbad74-bd2c-4633-bf75-200129e5ae16.png)
查看脚本 是 mac下sed命令与linux环境下参数列表不同的原因
![image](https://user-images.githubusercontent.com/37968554/147955973-3f42f79c-6712-4e07-98e5-7da2504a7a72.png)
经测试 添加空串设置备份格式后就可以解决问题
![image](https://user-images.githubusercontent.com/37968554/147956028-78037c05-8bc8-4ed5-a10e-45e5b3885645.png)
没有看到脚本的source，直接发个issue看一下吧

**Comment by XIU2** [comment]
我没有 MAC 设备，只知道 MAC 命令行和 Linux 很像，就直接把 Linux 下用的 sh 脚本放到压缩包里了~
稍后我会更新一下 MAC 压缩包里的脚本的。
