### ISSUE TITLE
为什么测试得到所有的ip都不通? SSL HANDSHAKE FAIL

### ISSUE THREAD

**Issue by joshatt** [XIU2/CloudflareSpeedTest#159]
xui面板, vmess, ws, ssl, 套上cf cdn, 通的. 
然后优选ip扫了几个, 逐个替换v2ray客户端中的主机, 结果每一个都不通, SSL HANDSHAKE FAILURE 之类的

肯定是我什么地方弄错了?

**Comment by XIU2** [comment]
找个套了 Cloudflare 的网站（比如官网），hosts 将 IP 指向后，测试能不能访问网站（记得重启浏览器 + cmd 刷新 DNS 缓存 `ipconfig /flushdns`）。
如果可以访问，那么说明 IP 是没有问题的，不过一般也不是 IP 的问题（前提是该 IP 下载速度不为 0）。

**Comment by joshatt** [comment]
> 找个套了 Cloudflare 的网站（比如官网），hosts 将 IP 指向后，测试能不能访问网站（记得重启浏览器 + cmd 刷新 DNS 缓存 `ipconfig /flushdns`）。 如果可以访问，那么说明 IP 是没有问题的，不过一般也不是 IP 的问题（前提是该 IP 下载速度不为 0，只要有下载速度那这个 IP 就肯定能用，因为下载测速就是将我的域名指向 IP 去下载文件的）。

谢谢. 不是很理解, 但按此操作了. 先是指向百度, 说你访问的网页中cloudflare上, 所以错误1001. 后来尝试指向cloudflare主页, 这次能访问

**Comment by XIU2** [comment]
指向百度干嘛。。。百度又没有套 Cloudflare，当然无法访问啦。。。

**Comment by XIU2** [comment]
你扫的时候是否禁用了下载测速？
因为很多 Cloudflare IP 都被假墙了，这些 IP 看着延迟异常的低但实际不可用，可以通过 ` -tll 90 ` 参数过滤低于 90ms 延迟的 IP，或者依靠下载测速来过滤。

**假墙 IP 的特征：**
- ICMP Ping 延迟正常、TCP Ping 延迟异常的低
_因为是在出口处 TCP 劫持，所以劫持后的延迟就是你到出口处的距离。_
