### ISSUE TITLE
能否加入以下cf的ip段呢

### ISSUE THREAD

**Issue by Ecalose** [XIU2/CloudflareSpeedTest#16]
或许有的重复了（
108.162.236.1/24
172.64.32.1/24
104.16.160.1/24
172.64.0.0/24
104.20.157.0/24
104.28.14.0/24
104.23.240.0-104.23.243.254
162.159.208.4-162.159.208.103
162.159.209.4-162.159.209.103
162.159.210.4-162.159.210.103
162.159.211.4-162.159.211.103
104.20.157.2
104.18.62.2
141.101.115.3
104.16.160.3
162.159.211.4-103
103.21.244.0/22
103.22.200.0/22
103.31.4.0/22
104.16.0.0/12
108.162.192.0/18
131.0.72.0/22
141.101.64.0/18
162.158.0.0/15
172.64.0.0/13
173.245.48.0/20
188.114.96.0/20
190.93.240.0/20
197.234.240.0/22
198.41.128.0/17
104.23.240.*
172.64.32.*
104.16.160.*
108.162.236.*
162.158.133.*
198.41.214.*
198.41.212.*
198.41.208.*
198.41.209.*
172.64.32.*
141.101.115.*
172.64.0. *
172.64.16.*
104.18.48.0-104.18.63.255
104.24.112.0-104.24.127.255
104.27.128.0-104.27.143.255
104.28.0.0-104.28.15.255
104.28.16.0-31.255
104.27.144.0-243.254
104.23.240.0-243.254
1.0.0.0-254
1.1.1.0-254
104.16.0.0-79.255
104.16.96.0-175.254
104.16.192.0-207.255

**Comment by XIU2** [comment]
看了下，除了 `1.0.0.0/24、1.1.1.0/24` 外，你这些 IP 段都已包含在 Cloudflare 官方提供的 IP 段列表里了。  

而我项目里的 `ip.txt` 用的就是 Cloudflare 官方提供的 IP 段。
```
173.245.48.0/20
103.21.244.0/22
103.22.200.0/22
103.31.4.0/22
141.101.64.0/18
108.162.192.0/18
190.93.240.0/20
188.114.96.0/20
197.234.240.0/22
198.41.128.0/17
162.158.0.0/15
104.16.0.0/12
172.64.0.0/13
131.0.72.0/22
```

**Comment by XIU2** [comment]
你要需要的话，我可以把这两个加上：
```
1.0.0.0/24
1.1.1.0/24
```
但说实话，因为这两个 IP 被 Cloudflare 用作 DNS，所以导致被墙重点针对，所以速度也不怎么样。

**Comment by Ecalose** [comment]
> 你要需要的话，我可以把这两个加上：
> 
> ```
> 1.0.0.0/24
> 1.1.1.0/24
> ```
> 
> 但说实话，因为这两个 IP 被 Cloudflare 用作 DNS，所以导致被墙重点针对，所以速度也不怎么样。

那算了，作者辛苦了

**Comment by Ecalose** [comment]
> 你要需要的话，我可以把这两个加上：
> 
> ```
> 1.0.0.0/24
> 1.1.1.0/24
> ```
> 
> 但说实话，因为这两个 IP 被 Cloudflare 用作 DNS，所以导致被墙重点针对，所以速度也不怎么样。
