### ISSUE TITLE
现在使用只会提示2个0数据的返回内容，北方电信网络

### ISSUE THREAD

**Issue by xwgodxwgod** [XIU2/CloudflareSpeedTest#160]
[信息] 延迟测速结果 IP 数量为 0，跳过下载测速。
[信息] 完整测速结果 IP 数量为 0，跳过输出结果。

**Comment by XIU2** [comment]
这说明你参数指定的条件相比实际情况而言**太苛刻**，**没有一个满足条件**的。
这种情况请先**无参数**运行一遍，确认当前能找到最好的 IP 延迟、速度范围再去**合理**的设置条件参数。

**Comment by xwgodxwgod** [comment]
> 这说明你参数指定的条件相比实际情况而言**太苛刻**，**没有一个满足条件**的。 这种情况请先**无参数**运行一遍，确认当前能找到最好的 IP 延迟、速度范围再去**合理**的设置条件参数。

就是我们之前一个讨论贴的设置，-tl 250 -tll 90 -dn 3
上周五1月14日的时候还是好的，周末没打开，今天1月18日周一打开就出这个问题了
同一个网络环境

**Comment by XIU2** [comment]
那这属于你的网络变化，这种情况很常见，无需大惊小怪~

**Comment by xwgodxwgod** [comment]
@XIU2 网络供应商无变化，ISP那边修改了连接策略吗？

**Comment by XIU2** [comment]
这我又怎么会知道呢？。。。
我说了，这种情况很常见。

**Comment by xwgodxwgod** [comment]
> 那这属于你的网络变化导致的，这种情况很常见，无需大惊小怪~
> 
> 影响网络的因素有很多，可能是运营商的问题，也可能是 Cloudflare 的问题，也可能是某个路由节点故障/负荷的问题。

挂CDN的Cloudflare还能正常工作，但是之前找到的高速IP，实际使用YB测速效果极差

**Comment by XIU2** [comment]
这种网络环节问题我无法解决。

**Comment by xwgodxwgod** [comment]
> 这种网络环节问题我无法解决。

非常感谢关注，我先研究下

**Comment by denniszzg** [comment]
同北方电信宽带，前几周开始，用这个工具已经测不出快速的ip了，家庭网络环境没有变化。
现象是，1. 运行时间明显延长了很久，2. 筛出的ip都是下载速度很低的

测速1：
参数：-n 500 -tl 200 -tll 40 -sl 4 -url https://speed.cloudflare.com/__down?bytes=500000000
![1](https://user-images.githubusercontent.com/30626214/150668752-5995f6a8-fea1-415f-adca-6025de11d38e.png)

测速2：
参数：-n 500 -tl 240 -tll 80 -sl 4 -dn 3 -url https://speed.cloudflare.com/__down?bytes=500000000
![2](https://user-images.githubusercontent.com/30626214/150668789-02ab3617-8506-418a-a881-e89b974efc92.png)

测速3：基于测速2结果，指定ip测速
参数： -f 1.txt
![3](https://user-images.githubusercontent.com/30626214/150668815-4120321b-1d71-432e-b16d-855434530f29.png)

**Comment by XIU2** [comment]
@denniszzg 你没有变化，那么说明是 **运营商** 或 **Cloudflare** 产生了变化。
要判断是不是 Cloudflare 变化的话，需要先前留的有测速、路由追踪数据才好对比观察。。。
不过根据大家的反馈，我更倾向于是运营商调整了 QOS 导致的。

> **QOS**：动态拥塞控制策略，路是固定的宽度，QOS 就是调整不同流量的优先级，限制低优先级的速度，保证高优先级的速度。这也是为什么企业里的宽带与外网的链接那么快、那么稳定的主要原因，比较加个也不一样。

如果真是运营商调低家宽优先级了（也可能是细化只针对家宽链接 Cloudflare 的流量优先级），那么除非换运营商否则是无解的。

**Comment by denniszzg** [comment]
还有就是，测速后，再次指定-f 1.txt方式指定ip测速，结果统统都是0.xMB/s

**Comment by denniszzg** [comment]
> @denniszzg 你没有变化，那么说明是 **运营商** 或 **Cloudflare** 产生了变化。 要判断是不是 Cloudflare 变化的话，需要先前留的有测速、路由追踪数据才好对比观察。。。 不过根据大家的反馈，我更倾向于是运营商调整了 QOS 导致的。
> 
> > **QOS**：动态拥塞控制策略，路是固定的宽度，QOS 就是调整不同流量的优先级，限制低优先级的速度，保证高优先级的速度。这也是为什么企业里的宽带与外网的链接那么快、那么稳定的主要原因，比较加个也不一样。
> 
> 如果真是运营商调低家宽优先级了（也可能是细化只针对家宽链接 Cloudflare 的流量优先级），那么除非换运营商否则是无解的。

确实，感觉是CF调整策略了。不知道其他使用本软件（包括您），有没有发现此异常

**Comment by XIU2** [comment]
@denniszzg 归根结底还是不稳定，我看你上面发的，唯一快的**延迟还偏高、还丢包**，特别是丢包对速度、稳定性影响极大。

Cloudflare 本身国内链接就不稳定（用的低成本线路），同一个 IP 一直循环下载测速的话，会发现忽高忽低的，而且我这个软件下载测速是取的平均速度，这也就意味着，如果速度不稳定忽高忽低的话，再加上一开始的起步时间，最后得出的结果都偏低。

****

不太可能是 Cloudflare 干的，因为我印象中 Cloudflare 与国内的链接路由都是白嫖来的，没什么成本，当然质量也没保证，因此 Cloudflare 就算限速也不会显著节省成本。

****

我是联通，最近没什么感觉，反而因为前段时间联通北京出口扩容导致速度更好了点。。。

**Comment by denniszzg** [comment]
谢谢大佬解惑。国内上个网真难

**Comment by fscwkp** [comment]
> 谢谢大佬解惑。国内上个互联网真难

也是北方电信， 发现从1月6日开始    电信优选不行了   ，第一次优选  5m/s 的ip，再测一次就变成0.1m/s了

**Comment by XIU2** [comment]
@fscwkp 如果一个 IP 第一次测速很快，然后再去测速几次就速度明显下降了的话，且此时该 IP 的延迟/丢包无明显变化，那就很符合运营商 QOS 的特点了。

**Comment by ohmyivan** [comment]
山东电信，最近半个月晚高峰速度都在1m以下测不出告诉了。我又要kcp了

**Comment by jamqiang** [comment]
我是上海电信，看来电信是动了手脚了，为了不被蔷，只能硬着头皮上 CDN 分配的IP了。
