### ISSUE TITLE
ipv4延迟测速完成后，每次一到下载测速就自动断网，下载速度全0，ipv6则正常。福建电信

### ISSUE THREAD

**Issue by davidu205** [XIU2/CloudflareSpeedTest#161]
![屏幕截图 2022-01-18 020728](https://user-images.githubusercontent.com/95669150/149819549-9b25f062-9d46-48f4-8688-5dd24a9bb291.png)
![屏幕截图 2022-01-18 020651](https://user-images.githubusercontent.com/95669150/149819576-b7669919-6c3b-4d08-9923-141c5772ed12.png)

**Comment by XIU2** [comment]
试了下，我这边联通是可以正常下载测速的。
你依次这样做并**告诉我具体结果**：

1. 浏览器访问 https://cf.xiu2.xyz/Github/CloudflareSpeedTest.png 试试（正常情况下应该提示 1020 Access denied）
2. 加上 `-url https://speed.cloudflare.com/__down?bytes=500000000` 参数试试（这是官方的下载测速链接）。
3. 加上 `-sl 1 -dn 1` 参数试试，这是下载速度下限，如果没找到速度高于 1MB/s 的 IP 就会一直测速下去，看看能不能找到。
4. 你把你图里的那几个 IP 在 Hosts 文件中随便指定一个**套了 Cloudflare 的网站**去访问试试看能不能访问（记得重启浏览器 + CMD 刷新 DNS `ipconfig /flushdns` 避免 Hosts 没生效）。

****

![01](https://user-images.githubusercontent.com/54703944/149846357-3fa71fdf-fc52-408e-a1a2-dcbb8343096b.png)

**Comment by davidu205** [comment]
还是一样结果，一到下载测速就断网，用了一些参数还是如此，不知是否网络问题，我的是光猫桥接，路由拔号，换过光猫拔号也是下载测速断网

**Comment by davidu205** [comment]
浏览器访问 https://cf.xiu2.xyz/Github/CloudflareSpeedTest.png 试试（正常情况下应该提示 1020 Access denied）正常1020

**Comment by XIU2** [comment]
能访问 https://cf.xiu2.xyz/Github/CloudflareSpeedTest.png 说明下载链接没问题。
你说的断网是什么意思？整个宽带网络都断了？

**Comment by davidu205** [comment]
是的，整个宽带网络都断，下载测速开始就上不了网，下载测速结束一会后网络就恢复了。

**Comment by XIU2** [comment]
只有 IPv4 有这种问题，IPv6 正常，不管光猫拨号还是路由器拨号都一样。

那么问题多半出在运营商身上了。

你把下载测速地址换成 Cloudflare 官方的也是这样么？
```
-url https://speed.cloudflare.com/__down?bytes=500000000
```
如果也一样，那么多半是运营商在针对 Cloudflare 的 IPv4 地址？。。。

**Comment by XIU2** [comment]
对了，如果你手机流量充足的话，你可以手机 USB 分享网络给电脑（记得禁用电脑上原先网卡），然后再去测速试试看是否正常。

一般运营商的家庭宽带 与 手机流量都是分开独立管理的，往往存在差异。

**Comment by davidu205** [comment]
电脑直接连接光猫拔号反而可以测速

但想不明白的一点是，之前用光猫桥接-路由器（openwrt）拔号-电脑测速另一位大佬的都是正常的（better-cloudflare-ip），后来他的不能用后用您的就一直出现上面反馈的问题，实在想不通原因

**Comment by davidu205** [comment]
感谢您的耐心及积极回复！！！

**Comment by XIU2** [comment]
你前面不是刚说过 `我的是光猫桥接，路由拔号，换过光猫拔号也是下载测速断网` 么。。。

**Comment by XIU2** [comment]
是这样吗？
- 光猫**桥接**，路由**拨号**，电脑不行
- 光猫**拨号**，路由**桥接**，电脑不行
- 光猫**拨号**，电脑**直连**，行
你这看起来很像是路由器的问题。

那你试过，光猫**桥接**，电脑**拨号**么？

**Comment by davidu205** [comment]
是的，看来问题出在路由器上

**Comment by XIU2** [comment]
你用 CloudflareST 是一直都这样（IPv4 无法下载测速），还是突然有一天就这样了？

断网这种描述，让我想到了以前一些人的反馈，以前软件延迟测速的默认线程数量是 ` -n 500 `，但一些人设备/路由器**性能不足**，因此这个并发测速超负荷，导致临时断网。
后续我就直接砍半调低至 ` -n 200 ` 了（250 不好听~），虽然延迟测速需要的时间也慢了一倍，但再也没有人反馈类似问题了。

你能确定是一旦开始**下载测速**就会准时断网？
你尝试过**禁用下载测速**没有？加上 ` -dd ` 参数试试看看，观察一下延迟测速期间网络是否卡顿、缓慢。

**Comment by davidu205** [comment]
一直都是这样（ipv4测速下载）就断网
能确定是一旦开始下载测速就会准时断网。

刚测试禁用下载测速，网络明显的打开缓慢，延迟测速结束后网络也是直接断网，网页也打不开

**Comment by davidu205** [comment]
![屏幕截图 2022-01-18 131632](https://user-images.githubusercontent.com/95669150/149875160-7505476c-6ea3-42b4-b5fe-de35a0898e27.png)

**Comment by XIU2** [comment]
那应该就和下载测速没什么关系了。
因为下载测速是单线程的，路由器这不可能连这个都负载不起。。。

初步判断是你的路由器性能问题（或设置问题），那你就继续调低延迟测速线程吧，例如 ` -n 50 ` 试试效果。

**Comment by davidu205** [comment]
调低延迟线程后测速结果：
![屏幕截图 2022-01-18 131632](https://user-images.githubusercontent.com/95669150/149876010-7d3908c2-f8c6-4076-8cc9-20b0f21fd6a1.png)

**Comment by XIU2** [comment]
期间网络是否卡顿？断网？

**Comment by davidu205** [comment]
刚又测试了下，网页打开有明显缓慢，网络没有断开，下载速度为0
![屏幕截图 2022-01-18 131632](https://user-images.githubusercontent.com/95669150/149876585-14eb8bab-0d86-422a-bce6-575e9cd8c4d7.png)

**Comment by XIU2** [comment]
那这样，你随便从图里找 10 个 IP 复制出来放到 ip.txt 文件内。
然后再去运行 CloudflareST 看看就测速 10 个 IP 的话，是否正常。

**Comment by davidu205** [comment]
我再降低下线程数试下

**Comment by davidu205** [comment]
这是降低线程的测试

![屏幕截图 2022-01-18 131632](https://user-images.githubusercontent.com/95669150/149877601-c5a922fa-ef0c-45ff-9df1-5c9ea5ebdacb.png)

**Comment by davidu205** [comment]
这是测试的10个ip，没有加子网掩码

![屏幕截图 2022-01-18 134052](https://user-images.githubusercontent.com/95669150/149877674-68f0f181-3c1f-4706-852e-adebc669cd76.png)

**Comment by XIU2** [comment]
感觉就挺奇怪的，这 15 个 IP 总不会路由器还负载不了吧，而且下载测速就成功 1 个，看起来不像是巧合。

但是你不用路由器就正常，一用路由器就不正常。。。
根据排除法，显然是路由器的问题。

你去重启一下路由器，然后再重新测速这 15 个 IP 看看。

**Comment by davidu205** [comment]
这是重启路由器后的测试，还是那15个ip

![屏幕截图 2022-01-18 131632](https://user-images.githubusercontent.com/95669150/149879081-e2f3111e-1b74-4474-b77c-1add678b5ab7.png)

**Comment by davidu205** [comment]
我路由器是红米2100，官网买的，刷的openwrt，按理说这个路由器应该不会渣到如此啊

**Comment by XIU2** [comment]
准确来说，现在是个路由器也不可能性能差到这种程度，所以多半是哪里设置导致的问题。

****

测速期间是否网络卡顿？
从里面随便再找一个下载速度 0.00 的单独放到 ip.txt 文件中，去测速看看能不能下载测速。

**Comment by davidu205** [comment]
没能下载测速

![屏幕截图 2022-01-18 134052](https://user-images.githubusercontent.com/95669150/149879835-0d1bc4a9-821c-4b86-94f5-2eec4bc22edb.png)

**Comment by XIU2** [comment]
你指定 Cloudflare 官方下载测速地址再试试。
```
-url https://speed.cloudflare.com/__down?bytes=500000000
```

****

随后在 Hosts 文件中添加：
```
104.20.202.228 speed.cloudflare.com
```
然后重启浏览器后，访问 https://speed.cloudflare.com/__down?bytes=500000000 看是否能下载文件。

****

两者对比，看看是全都不行，还是一个不行一个行。

**Comment by XIU2** [comment]
另外再加上 ` -dt 30 ` 参数（下载测速时间）。

**Comment by davidu205** [comment]
![屏幕截图 2022-01-18 131632](https://user-images.githubusercontent.com/95669150/149880708-b6e21e0c-ab87-4626-b9cd-b3c3ab96f1c8.png)

**Comment by XIU2** [comment]
这样的话，那么你将 ip.txt 内的 IP 数量恢复到 10 个再去测速，对比一下。

**Comment by davidu205** [comment]
这是最后的测速结果 

![屏幕截图 2022-01-18 131632](https://user-images.githubusercontent.com/95669150/149881870-2927b1c5-1523-4850-860e-34a75d3a430c.png)

**Comment by XIU2** [comment]
再把 -url 参数去掉，即用默认的下载测速地址试试。
看看是不是下载测速地址的差异导致的。

**Comment by davidu205** [comment]
去掉url参数后下载速度又回到全是0的样子了

![屏幕截图 2022-01-18 134052](https://user-images.githubusercontent.com/95669150/149882238-da0b6f62-0a0e-48b5-9663-2ed88c33ee0b.png)

**Comment by XIU2** [comment]
奇怪，默认的下载测速地址，既然你能直接访问，也时不时能测速成功一两个，那就说明并不是被你当地运营商屏蔽了。

你用电脑直连光猫的时候，下载测速是正常的吧？

**Comment by davidu205** [comment]
换回下载包里自带的ip.txt地址文件测速后，再次出现反馈的断网问题及下载速度为0的情况

![屏幕截图 2022-01-18 134052](https://user-images.githubusercontent.com/95669150/149882759-805a8eb8-48ed-4474-82a2-22c702f5ff07.png)

**Comment by davidu205** [comment]
用电脑直连光猫测速是正常的，也有些是没有下载速度的

**Comment by XIU2** [comment]
你换回去完整的 ip.txt 别忘了降低线程 ` -n 50 `，你忘了前面的测试么。。。不降低线程数量就会断网，此时就是能下载测速也无法下载了呀。。。

**Comment by davidu205** [comment]
![屏幕截图 2022-01-18 134052](https://user-images.githubusercontent.com/95669150/149883697-d4ef3e2a-38f2-4d9c-b7d8-503c375b3b50.png)

**Comment by XIU2** [comment]
对了，我前面问了个问题，你没有回答：

> 你前面下载测速的时候，进度条是等个 10 秒超时后继续下一个，还是很快就继续下一个了？

**Comment by davidu205** [comment]
感觉不止10秒

**Comment by davidu205** [comment]
感觉不止10秒

**Comment by XIU2** [comment]
折腾半天，也没测试出一个所以然来。。。没有找到什么明显规律。

那就只能你去研究下路由器里到底是哪里的问题导致的了。

**Comment by davidu205** [comment]
问题应该在路由器上，我再研究下

谢谢！！！

**Comment by xwgodxwgod** [comment]
> 

better-cloudflare-ip的大佬页面已经404了，唉

**Comment by cnp2nx** [comment]
移动 香港cf节点绕美了，被玩废了，延迟200多，龟速

**Comment by XIU2** [comment]
@cnp2nx Cloudflare 香港节点维护，因此暂时停用，临时调整路由到美西等地，当然着不是第一次了，无需大惊小怪~
官方网络状态页可以看到：https://www.cloudflarestatus.com
