### ISSUE TITLE
请问近一个月北方电信是不是出什么问题了？

### ISSUE THREAD

**Issue by Visntse** [XIU2/CloudflareSpeedTest#162]
坐标陕西西安电信，公网IPV4，之前还挺正常。
但是最近一个月左右，白天时候测试，速度几乎都在5MB左右，不像以前随随便40~80M的一堆一堆的。
而且用起来感觉延迟很高很高……
而夜间甚至都是0.X的……
没有修改什么系统设置和路由器设置，但是好像是最近重新刷了路由器系统，电脑系统也重新装了……
路由器设置拨号时禁止获取IPV6……

想知道是我的问题还是最近北方电信炸了？

**Comment by XIU2** [comment]
不清楚，我是联通，延迟依然一如既往的保持稳定，甚至感觉比以前更稳了。。。
我目前用的 IP 还是上个月测速得来的，后来发现一直保持全天 155~175ms 之间，因此也就没有再去重新测速了。。。

你这种情况，
要么是某个出口炸了（路由追踪检查），
要么就是当地运营商改了 QOS 策略（动态拥塞控制），降低了流量优先级。
我记得前几天不是听说电信某个出口炸了么？不知道和你的情况是否有关

**Comment by Visntse** [comment]
路由追踪检查怎么做？我是openwrt的路由系统，个人网络这块不是很行，还请赐教。
另外有必要更改电信给的默认dns到别的第三方吗？是否会适当的有些解决？
电信口炸了这个也听说过……但是据说恢复了啊？

**Comment by XIU2** [comment]
路由追踪可以用这个可视化地图的软件：
https://cdn.ipip.net/17mon/besttrace.exe

DNS 只影响域名解析的 IP，不会影响实际网速。
你访问网站流程：
``` bash
输入域名回车 <=> 浏览器开始 DNS 解析 <=(DNS 只影响这个环节)=> 获得解析 IP <=> 浏览器访问该 IP <=> 你看到网页内容。
```

**Comment by Visntse** [comment]
![1](https://i.niupic.com/images/2022/01/18/9TyP.PNG)
![1](https://i.niupic.com/images/2022/01/18/9TyQ.PNG)

测试了，这个该怎么解读呢？

**Comment by XIU2** [comment]
你这延迟看起来还行呀，只是出口处第一条有些丢包（那个 * 号）。

**Comment by Visntse** [comment]
不过之前正常的时候，确实只有这个104.16.x.x开头的IP是速度最快的……
但就是最近这个，测试出来的延迟还是150左右，但是下载速度就只有3，4M左右了。
奇怪的用起来很难受……

这结论是没什么办法解决了吗？

**Comment by XIU2** [comment]
如果是运营商 QOS 限速的话，那么是无解的。
像这种延迟低，也不怎么丢包，但是速度异常慢，很有可能是运营商主动调整 QOS 限速导致的。。。

我这边路由追踪，也是北京出口，延迟和你几乎一样，但是我这个是旧金山，且跳数有 15 跳，且完全不丢包，我用起来速度还是挺不错的，可能是我个人要求不高吧~

**Comment by Visntse** [comment]
![2](https://i.niupic.com/images/2022/01/18/9TyS.PNG)

非常感谢……大概明白是什么意思了。
另外再多问一下，这是给我自己网站的一个测试。
首先，跳数指的就是前面#这一列经过的节点数对吧？
二来，这里那个10.222.43.1的ip查了下指的是内网？那它后面全都是*号，是不是说我路由器内部有问题？还是说从我本机（或者本地电信局？）至那个202.97的北京电信之间丢包很严重？

**Comment by XIU2** [comment]
对，就是前面的序号。
****
路由追踪是依靠 TLL （IP 生存时间）来探测经过的路由信息的。
每经过一个路由节点，TLL 就会 -1（即显示出来 1 跳），路由节点正常情况下会回应，如果 IP 处显示的是 *，则说明该节点**没有回应**，因此就不知道该路由节点的具体信息（比如 IP 是什么）。

那个 `10.224.43.1` 内网 IP 指的是运营商的内网，你是 `192.168.1.1` 这个 IP（路由器/光猫的 IP），往后的跳数都是出你家门了。

**Comment by Visntse** [comment]
喔！明白了，感谢大神，感谢大神！
多谢多谢！！！
