### ISSUE TITLE
ipv6测速 只能用443吗？用其他的如80直接没速度

### ISSUE THREAD

**Issue by ljm1447669873** [XIU2/CloudflareSpeedTest#163]
有延迟，但速度为0

**Comment by XIU2** [comment]
要测速 80 端口，需要手动指定 http:// 的下载测速地址，如：
```
-url http://cf.xiu2.xyz/Github/CloudflareSpeedTest.png
-url http://speed.cloudflare.com/__down?bytes=500000000
```

**Comment by ljm1447669873** [comment]
./CloudflareST -f ipv6.txt -ipv6 -tp 2096 -url https://speed.cloudflare.com/__down?bytes=500000000
# XIU2/CloudflareSpeedTest v2.0.2 

开始延迟测速（模式：TCP IPv6，端口：2096，平均延迟上限：9999 ms，平均延迟下限：0 ms)
17733 / 17733 [------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
开始下载测速（下载速度下限：0.00 MB/s，下载测速数量：10，下载测速队列：10）：
4 / 10 [----------------------------------------------------------------------------->____________________________________________________________________________________________________________________] 40.00%
IP 地址                                   已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
2606:4700:3001:5c:bdb3:6642:c27:37b9      4       4       0.00    1.43      0.00           
2606:4700:3004:0:4ffb:94ac:6e1f:a1fd      4       4       0.00    1.48      0.00           
2606:4700:130::af:c947                    4       4       0.00    1.48      0.00           
2606:4700:3004:0:c0ff:f93:594e:f6c3       4       4       0.00    1.49      0.00

**Comment by XIU2** [comment]
https:// 地址的只能指定 443 端口，除非该网站使用了其他非标准端口。

**Comment by ljm1447669873** [comment]
但是这个网址是开放2096的，为啥也不行
https://speed.cloudflare.com:2096/__down?bytes=500000000

**Comment by XIU2** [comment]
我测试了下，发现目前无法对 IPv6 进行下载测速，我研究下原因。

**Comment by XIU2** [comment]
经过排查，发现实际上软件正常下载测速 IPv6 了（网络下行可以看到），但是下载速度结果计算似乎出了什么问题导致显示为 0，我再去检查下原因是什么。。。

**Comment by XIU2** [comment]
测试了下，又发现似乎不是 IPv6 的原因。
因为我是在服务器 Linux 上面测试 IPv6 的，结果发现 IPv4 测速后下载速度也是显示 0 。
但是在 Windows 下 IPv4 测试是正常的。。。

这给我搞懵了，同一个库，不同系统下怎么还不一样。。。

**Comment by ljm1447669873** [comment]
ipv4的443是正常的

**Comment by XIU2** [comment]
我发现我这边 Linux 下如果用 Cloudflare 的下载测速链接，无论是 IPv4 还是 IPv6 都无法显示下载速度。
而如果用自带的下载测速地址（就是我的那个）发现不管是 IPv4 还是 IPv6 都正常。。。

**Comment by XIU2** [comment]
你指的是，你那边用 Cloudflare 的下载测速链接，IPv4 正常么？只有 IPv6 不正常？
用自带的下载测速链接 443 端口 IPv6 也不正常？

**Comment by ljm1447669873** [comment]
就是不指定url吗？ipv6除了443都出不来

**Comment by XIU2** [comment]
那是正常的，用自带的下载测速链接，仅支持 443 端口。
我主要问的是用 Cloudflare 的下载测速链接时，IPv4 IPv6 的情况。
