### ISSUE TITLE
河南移动PING突然涨到200ms!麻烦更新IP段。

### ISSUE THREAD

**Issue by yanhuasanyuexyz** [XIU2/CloudflareSpeedTest#164]
最近有什么大的动作吗？之前好好的，都是香港可用，今天都是绕美，试了许多次了，根本搜不到IP，我该怎么办？谢谢！

**Comment by XIU2** [comment]
Cloudflare 香港节点维护，因此临时调整到美西路由，当然着不是第一次了，无需大惊小怪~
官方网络状态页可以看到：https://www.cloudflarestatus.com
