### ISSUE TITLE
最快IP，可以直接通过改hosts使用吗？我改了之后网页打不开了。

### ISSUE THREAD

**Issue by UchihaYuki** [XIU2/CloudflareSpeedTest#165]
我nslook我的网站是分了三个美国IP，我测速后，hosts指向最快香港IP（我是移动用户），但是操作之后，网站就打不开了。
连接错误：503 server unavailable

**Comment by XIU2** [comment]
所有 IP 都不行，还是只有香港的 IP 不行？

**Comment by UchihaYuki** [comment]
> 当然是可以直接改 Hosts 用，我以前一直都是这么干的。 所有 IP 都不行，还是只有香港的 IP 不行？

试了一下，都不可以，我看youtube上自选IP都要托管到第三方，可能现在不行了？

**Comment by XIU2** [comment]
如果你是为了给自己的网站加速才自选 IP 的，那么现在想要实现就很麻烦了。

**Comment by UchihaYuki** [comment]
> 如果你是为了给自己的网站加速才自选 IP 的，那么现在想要实现就很麻烦了。 CFP 现在不能直接 CNAME 接入了，也就无法自选了。
> 
> 但这并不影响本地 Hosts 方式指定自选 IP 访问。 你换个其他套了 Cloudflare 的网站再试试，至少我这边是完全没问题的。

测了半天，发现是软件的问题。换了一个软件直接使用优选IP就可以了。打扰了。打扰了。谢谢。
