### ISSUE TITLE
查询ipv6时报错，希望解决一下！

### ISSUE THREAD

**Issue by tejing** [XIU2/CloudflareSpeedTest#17]
如题，出现一下错误信息：
G:\CloudflareST>CloudflareST.exe -p 0 -f ipv6.txt -dd -ipv6
panic: invalid argument to Intn

goroutine 1 [running]:
math/rand.(*Rand).Intn(0xc0000b8330, 0xffffffffffffffff, 0x10)
        C:/Program1/Go/src/math/rand/rand.go:169 +0xa5
math/rand.Intn(...)
        C:/Program1/Go/src/math/rand/rand.go:337
main.randipEndWith(...)
        C:/Github/CloudflareSpeedTest/util.go:95
main.loadFirstIPOfRangeFromFile(0xc0000a20a8, 0x8, 0xc0000b90e0, 0xc0000a20c9, 0x4)
        C:/Github/CloudflareSpeedTest/IPRangeLoader.go:48 +0x1d9
main.main()
        C:/Github/CloudflareSpeedTest/main.go:135 +0x88

CloudflareST版本是 -v1.4.1

**Comment by XIU2** [comment]
简单看了下，是我上个版本更新导致的，我看看怎么修复。

**Comment by XIU2** [comment]
## 更新内容
1. **修复** IPv6 测速报错的问题。**#17**   
`上个版本更新时没测试完全。`
