### ISSUE TITLE
对多拨网络不太友好

### ISSUE THREAD

**Issue by Cptmacmillan2022007** [XIU2/CloudflareSpeedTest#172]
测速线程 -n 到20才稳定

不带-n或将-n参数调大多拨会断线，同时连接的电脑手机都上不了网。

单拨没有任何问题

还有一开始测速还有速度为啥后面全部变成0.00MB/s这是为啥？（已按照#168中的提示照做了）

是否存在干扰和假墙？

使用badafans的测速没有任何问题

**Comment by XIU2** [comment]
参数自己找到合适的就好，不同情况下适用不同的参数。

****

这个你需要对同样的 IP 去测试对比才知道，可能是这几个 IP 问题，也可能是下载测速地址的问题。
https://github.com/XIU2/CloudflareSpeedTest#-单独对一个或多个-ip-测速
