### ISSUE TITLE
建议使用-ipv6 时自动调用 -f ipv6.txt 

### ISSUE THREAD

**Issue by delphinuz** [XIU2/CloudflareSpeedTest#173]
试一下，单独使用 -ipv6时，虽然程序印出 "开始延迟测速（模式：TCP IPv6....)，但实际仍是v4的结果，需要主动加上  -f ipv6.txt 。

若能自动加入  -f ipv6.txt 是否会更方便些？

**Comment by XIU2** [comment]
不是很有必要，不差这点。。。
之所以加上 -ipv6 参数，纯粹是我为了偷懒，没有写自动判断机制。

**Comment by delphinuz** [comment]
> 同样曾经设想过，但因为偷懒而没去添加支持的还有**同时测速 IPv4+IPv6** 的功能。

是的，现在ipv6需求也多了，若能直接达到这功能就完美了。还是期待这部分有机会完善，谢谢。

**Comment by XIU2** [comment]
还有一个原因。
CloudflareST 原理是**遍历每个 IP 段**去延迟测速的（只有 IP 段最后一段 ` .xxx ` 是完全随机的），IPv4 还好，IPv6 数量太多了，这点就导致不可能像 IPv4 一样去遍历 IP 段，那样数量太多了，要测速到猴年马月去，所以当初我只能改为**随机 IP 段**（不再局限于 IP 最后一段），这样 IP 数量就大幅下降了，但可能就没那么全面了（相当于每次测速都只是 IP 段中的一部分）。

总之，这个问题目前没有什么两全其美的方法（兼具全面+快速）。

**Comment by delphinuz** [comment]
目前的随机 IP 段方式就很好了，使用上没什么问题。只是能加上同时测速v4/v6会比较方便，或是将下载速度为0的剔除。

我的意思是，不用加参数就可以完成一般使用者需要的功能，是最方便的。
