### ISSUE TITLE
关于 tcping

### ISSUE THREAD

**Issue by hellodword** [XIU2/CloudflareSpeedTest#176]
```sh
date +%s.%3N && curl -s https://cloudflare.com/cdn-cgi/trace --resolve cloudflare.com:443:198.41.197.61 | grep -oP '(?<=^ts=)[\d\.]+' && date +%s.%3N
```

本地时间准确（或者程序内置一个NTP client）就可以计算出延迟。

相比 [tcping](https://github.com/XIU2/CloudflareSpeedTest/blob/7f6e374ae4955c3a2f5537cd72f08be34f8dc30d/task/tcping.go#L88-L102)，是 tls 所以不会有“假墙”的担忧，完整的 https 请求也更符合某些使用场景。

**Comment by XIU2** [comment]
可以，但没必要，相比 TCPing 这样速度会更慢。
至于假墙，最近我都没遇到过了，也没什么站长说假墙勒索了，可能是墙修复了这个漏洞？

总之，我的技术一般，没有强烈需求的话，我是没动力去折腾的，当然如果有技术也欢迎 PR~
