### ISSUE TITLE
AC2100路由执行提示 line 1: syntax error: unexpected "("

### ISSUE THREAD

**Issue by DaoChen6** [XIU2/CloudflareSpeedTest#179]
![image](https://user-images.githubusercontent.com/63903027/154527535-434e113f-0080-4c63-944d-fff4ce7f6dd5.png)
如题，错误提示`line 1: syntax error: unexpected "("`

**Comment by XIU2** [comment]
这种一般都是因为选错了版本，你挨个试试其他的 Linux 版本。

**Comment by DaoChen6** [comment]
感谢解答，已成功运行

**Comment by XIU2** [comment]
@DaoChen6 应该是和 #43 里提到的情况差不多，即**同一个 IP 在 路由器上 与 电脑上 分别测速得到的结果不同**（无论用的是 CloudflareST 还是其他单纯的 wget/curl 下载工具）。

我没有相关设备，也无法深入研究到底是什么原因导致的，这种情况在好几个人身上复现过。
