### ISSUE TITLE
ip 段不全

### ISSUE THREAD

**Issue by CrazyBoyFeng** [XIU2/CloudflareSpeedTest#19]
我注意到软件内置列表是 cloudfalre 官方公开的回源 ip，并不是 anycast 泛播 ip。有的回源 ip 并不提供泛播业务。
这里有一份比较全的泛播列表，不过是按子网 24 收录的：
https://github.com/TulvL/cloudflare-ip-tester/blob/master/whole/ip_list.csv

**Comment by XIU2** [comment]
你的意思是 Cloudflare 公开的 IP 并不是全部 IP？
还是说 Cloudflare 公开的 IP 是包含了回源 IP + 泛播 IP？

**Comment by CrazyBoyFeng** [comment]
抱歉，我没说清楚。不是说官方这个列表有遗漏，而是说它包含了很多不能作为泛播使用的节点。  
比如 104.21.0.0/16 这个段是无法作为泛播的，可能是保留了供付费用户，或者不提供泛播业务。  
不过你说的也没错，宁枉毋纵。都测一下是比较合理的。

此外，用个人站点测速可能会在人多时触发 ddos，推荐用官方测速 api：
https://speed.cloudflare.com/__down?bytes=100000

**Comment by XIU2** [comment]
我这个项目一开始也是用的官方下载测速地址，然而可能是用的人太多（当然不止我一个项目在用），导致一到晚上就会这个地址就会**提示资源超过限制**，后来我想过其他方法 #6 ，最后还是干脆自建了，特意选的 .png 图片格式，反正缓存率是 99.99%，DDOS 也是打的 Cloudflare 节点而不是我的服务器。
