### ISSUE TITLE
任何时段测速均为0.2M左右

### ISSUE THREAD

**Issue by kimberlytor** [XIU2/CloudflareSpeedTest#195]
请教一下，在任何时段测速均为0.2M左右，无论电脑还是手机，也试过cf自建测速，某次电脑上测试结果见下图，电脑上为上海电信，手机上为联通。
![image](https://user-images.githubusercontent.com/100819379/161385073-5f3b4bb5-6472-4da1-b3f8-ff3a42111300.png)

**Comment by XIU2** [comment]
那你尝试过手动访问这些下载测速地址，下载速度如何？

**Comment by kimberlytor** [comment]
刚刚测试下载速度4M/s

**Comment by kimberlytor** [comment]
刚刚测试cf自建的下载地址的下载速度在4-5M/s

**Comment by XIU2** [comment]
那就是说这是网络问题？

**Comment by kimberlytor** [comment]
我在issue中搜索到过两个类似的问题，意思是被运营商限制了么？代理用的hysteria

**Comment by XIU2** [comment]
这个我不确定，我也没办法去确定。。。

**Comment by kimberlytor** [comment]
感谢解答，请问下您能想到的原因有哪些呢？我自己去测试一下

**Comment by XIU2** [comment]
这个我也没啥办法，基本上就是常见的排除法。
即换个同地区的其他网络试试，如果都这样，那么多半是运营商搞的鬼，毕竟现在国内很多地区开始针对 Cloudflare 了。

**Comment by kimberlytor** [comment]
好的，感谢解答，那我再测试下，把这个issue关了
