### ISSUE TITLE
需求功能---设定网速目标值，直到选出目标值ip才停止任务

### ISSUE THREAD

**Issue by gnz1123** [XIU2/CloudflareSpeedTest#198]

**Comment by gnz1123** [comment]
或者设定优选时长，完成后列出前10个最快ip

**Comment by XIU2** [comment]
这功能很早就有人提过了，用第三方脚本就能实现，我当时就把相关代码加到压缩包里的各个脚本中了，你自己去打开看看把，这些代码默认都是注释掉的，你自己去看注释说明。
