### ISSUE TITLE
无法替换hosts

### ISSUE THREAD

**Issue by pjw20911** [XIU2/CloudflareSpeedTest#199]
打开 cfst_hosts.bat 前，确定 nowip_hosts.txt 记录的IP 和 C:\Windows\System32\drivers\etc\hosts 的IP 完全一致

然后右键“以管理员身份运行”cfst_hosts.bat

检查nowip_hosts.txt 发现IP确实已经更新了，但C:\Windows\System32\drivers\etc\hosts 还是旧IP

最后结果是：
..........

完整测速结果已写入 result_hosts.txt 文件，可使用记事本/表格软件查看。
按下 回车键 或 Ctrl+C 退出。
旧 IP 为 104.23.120.57
新 IP 为 104.24.205.187

开始备份 Hosts 文件（hosts_backup）...
hosts
系统找不到指定的文件。
已复制         0 个文件。

开始替换...
拒绝访问。
完成...

请按任意键继续. . .

**Comment by XIU2** [comment]
看起来就是权限问题，虽然以管理员身份运行了。

你是一直都不行还是突然不行的？如果是前者，怕是其他什么地方的权限配置有问题。
比较 Windows 的权限配置挺复杂混乱的。。。

**Comment by pjw20911** [comment]
> 看起来就是权限问题，虽然以管理员身份运行了。
> 
> 你是一直都不行还是突然不行的？如果是前者，怕是其他什么地方的权限配置有问题。 比较 Windows 的权限配置挺复杂混乱的。。。

以前不记得哪个版本是可以成功替换的，后来手动更新到v2.0.3，好像从这时候不能替换了。那时我也没管，反手Ctrl+H替换一下也不麻烦，今天周末有时间了就想着折腾一下，看看啥原因

**Comment by XIU2** [comment]
和 CloudflareST 无关，CloudflareST 只负责测速并输出结果，替换 Hosts 什么的全都是脚本完成的。

**Comment by pjw20911** [comment]
破案了，文件属性问题.... 

hosts 这个文件，带有系统属性时，无法写入

反复试了几次，用 attrib -s 去掉属性后正常了，attrib +s 后问题复现

看起来，文件属性还凌驾于管理员权限之上....

**Comment by pjw20911** [comment]
> 和 CloudflareST 无关，CloudflareST 只负责测速并输出结果，替换 Hosts 什么的全都是脚本完成的。
> 
> 这几个脚本本质上就是运行 CloudflareST，获取结果文件中的第一个 IP，写入 nowip_hosts.txt 文件，备份 hosts 文件，最后替换 hosts 文件。你右键编辑脚本就能查看脚本代码了，简单明了。
> 
> 因为这些功能都可以通过**第三方脚本、软件**去扩展实现，因此我不会也不可能将这些功能集成到 CloudflareST 程序中的。
> 
> > 对于这点，我非常克制，因为一旦开始这样做，最后 CloudflareST 只会变得非常**臃肿、复杂、难以维护**，变成讨厌的样子。
> 
> **CloudflareST 只负责最核心、基本的测速功能**，其他任何个性化功能我都不会添加（很多人提过，但我都拒绝了，但也顺手帮他们写了脚本，包括这几个 hosts 脚本也是当初为此写的）。

破案了，文件属性问题.... 

hosts 这个文件，带有系统属性时，无法写入

反复试了几次，用 attrib -s 去掉属性后正常了，attrib +s 后问题复现

看起来，文件属性还凌驾于管理员权限之上....

**Comment by XIU2** [comment]
我也记不清楚 hosts 文件是默认就有系统文件属性，还是没有。

**Comment by ixinshang** [comment]
> 

win8.1类似的情况，attrib -s后，依旧没法使用。 还没找到原因。

**Comment by vc5** [comment]
头疼，还是关闭UAC为妙
