### ISSUE TITLE
测试下载地址已访问不到了

### ISSUE THREAD

**Issue by christan-duplicate** [XIU2/CloudflareSpeedTest#2]
https://apple.freecdn.workers.dev/105/media/us/iphone-11-pro/2019/3bd902e4-0752-4ac1-95f8-6225c32aec6d/films/product/iphone-11-pro-product-tpl-cc-us-2019_1280x720h.mp4
测试下载地址已访问不到了

**Comment by christan-duplicate** [comment]
建议下载地址改为：https://speed.cloudflare.com/__down?bytes=1000000000

**Comment by XIU2** [comment]
emmm ，才发现这个 Issues，上个月有段时间老是收不到 Github 的通知邮件。  
抱歉回复晚了，这月初有个人去知乎通知我我才发现的，当时发的 v1.2.7 已经修复了。

**Comment by myfalcom** [comment]
今晚测速好像又无法测到下载速度了。

**Comment by XIU2** [comment]
@myfalcom 看了下发现 `speed.cloudflare.com` 这个官方的测速网站提示资源超出限制了。。。  
应该是用的人太多导致的，这就很蛋疼了，只能再找找有没有合适的测速网站了。

**Comment by XIU2** [comment]
@myfalcom 今天试了下又能用了，我估计是这网站下载测速有限制（每天），或者是 Cloudflare 昨天发现挂了，调整了下网站资源限制。  
不过考虑这点，我想我应该添加个参数，让大家可以手动指定测速URL。

**Comment by XIU2** [comment]
@myfalcom 好像又不行了，似乎是这个测速的文件太大了（953MB），调小一点就可以了。  
更新 v1.2.8 了，调低至 300MB 大小。

**Comment by myfalcom** [comment]
300MB到晚上好像又说超限了，是不是得用手动参数才行了。

**Comment by XIU2** [comment]
@myfalcom 主要是文件太小的话就不准确了，我昨天也是测试了几遍选了个比较合适的 300MB。  

**理论上改成 300MB 实际测速次数能翻三倍**，但是因为这个测速地址并不只是我一个项目再用（我在 Github 瞎逛都找到了好几个类似项目，它们很多也都在用，而且用的是 **953MB** 的链接），所以除非大部分人用的是我这个项目，否则只是我自己项目调小，而别人项目都没调小的话，实际上还是无法改变现实情况（所有人共用一个上限）。

**Comment by myfalcom** [comment]
不然把测速地址可以设置手动输入吧。默认还是以cloudflare的为主。

**Comment by XIU2** [comment]
v1.2.9 已经支持 `-url "https://xxx"` 参数来指定下载测速地址了。  
同时我也开了个 **Issues #6 用来征集可用于 [下载测速] 的地址。**

**Comment by XIU2** [comment]
@myfalcom 我自己带头写了一些可以用下载测速的地址，你可以去 Issues #6 里看看。

**Comment by myfalcom** [comment]
其实用VPS的，都可以里面放个文件测速。我刚试了可以的。

**Comment by XIU2** [comment]
> 其实用VPS的，都可以里面放个文件测速。我刚试了可以的。

下载测速地址必须用的是 Cloudflare CDN 服务。  

如果你的网站用的就是 Cloudflare CDN 且启用了 **CDN 代理**（ DNS 解析处的**橙色云朵**），那么在你网站里放个文件确实可以拿来下载测速，但是不知道像这种文件 Cloudflare **是否会完全缓存**，否则如果老是前往你的网站服务器获取该文件，可能会比较**消耗你的服务器流量**。

**Comment by myfalcom** [comment]
现在就是用自己的VPS里面生成一个 大文件，然后通过CDN代理进行测速，效果很不错。平时测下倒无所谓了。

不过这个电脑上测输输命令还行，手机上就难受了。要拿个大神能出个安卓版就完美了。

**Comment by XIU2** [comment]
@myfalcom 

然而我并不会安卓编程。。。  
我平时都是业余自学的，自己产生需求，然后就自己临时学习合适的语言去实现。

**Comment by XIU2** [comment]
@myfalcom 

为了方便，v1.3.0 版本把默认下载测速地址改为我自建的了。
