### ISSUE TITLE
怎么回事，我格式都对了，怎么无法测试？

### ISSUE THREAD

**Issue by Mike-Yann** [XIU2/CloudflareSpeedTest#201]
![image](https://user-images.githubusercontent.com/101911284/164155672-20118461-f359-45ba-ba9b-30c5f5b62ecf.png)
如图，我这格式是正确的，以前还行的（
![image](https://user-images.githubusercontent.com/101911284/164155876-2a4a0d5d-91d1-44e0-8c95-577af5dd54bf.png)
![notepad_tun55WRJ7O](https://user-images.githubusercontent.com/101911284/164155888-0ac3f3a6-6880-400e-8b87-24769ff04a62.png)
我很疑惑

**Comment by XIU2** [comment]
不要截图，你把这个 txt 文件内容完整的复制出来。

另外，你为什么用的还是 2.0.2 旧版本。。。

**Comment by baby9** [comment]
我说这段时间这些中转节点速度怎么这么慢，原来是被你们拿去天天测速了
