### ISSUE TITLE
怎么屏蔽104开头的IP

### ISSUE THREAD

**Issue by DemoorBug** [XIU2/CloudflareSpeedTest#207]
这次workers.dev炸了之后，改路由也不能使用优选104开头的ip，但是测速的时候全都是104的，能不能屏蔽这些开头的ip？

**Comment by MrQQQQQQQQQQ** [comment]
> 这次workers.dev炸了之后，改路由也不能使用优选104开头的ip，但是测速的时候全都是104的，能不能屏蔽这些开头的ip？

ip.txt 里面去掉104段的， 应该就可以了

**Comment by ymmshi** [comment]
想问一下为啥104开头的ip也不行呀

**Comment by ixinshang** [comment]
> 

openwrt的插件怎么屏蔽？
自定义参数吗

**Comment by XIU2** [comment]
@ixinshang 不管是哪种版本的，都会有个 ip.txt 文件。
一般会和插件程序本身放在一起的，或者你去问一下插件作者。

**Comment by ixinshang** [comment]
> @ixinshang 不管是哪种版本的，都会有个 ip.txt 文件。 一般会和插件程序本身放在一起的，或者你去问一下插件作者。

好嘞。谢谢

**Comment by DemoorBug** [comment]
> > 这次workers.dev炸了之后，改路由也不能使用优选104开头的ip，但是测速的时候全都是104的，能不能屏蔽这些开头的ip？
> 
> ip.txt 里面去掉104段的， 应该就可以了

可以了,谢谢了
