### ISSUE TITLE
CloudflareSpeedTest测速异常

### ISSUE THREAD

**Issue by AndersonGhost** [XIU2/CloudflareSpeedTest#21]
大佬，您好！现在出现一个问题，向您请教一下：
公司的网络是100M的联通，使用CloudflareSpeedTest可以找到速度为10M/s的节点。
家里的网络是300M的联通（最快下载速度32M/s），同样使用CloudflareSpeedTest只能找到1.5M/s的节点。
这是为什么啊？如何解决这个问题呢？

**Comment by XIU2** [comment]
这可能是公司的企业宽带掏钱更多导致的？  
你可以尝试把公司里测速找到的速度快的 IP 复制出来，后面加上 /32 子网掩码，然后新建一个文本文件.txt 并写入，运行的时候加速启动参数 -f "xxx.txt" 看看。  
这就是用家里的网络单独测速这些公司里速度快的 IP。

**Comment by AndersonGhost** [comment]
大佬您好，感谢解答！在家里使用CloudflareSpeedTest测试了无数次，从来没有找到超过1.5MB/s的节点，可家里面的带宽是300M啊（这个确定无疑）。这是为什么呢？是不是开发商做了手脚？

**Comment by XIU2** [comment]
要知道，你买的宽带只会保证你在国内测速能跑满 300Mbps，并不会保证链接国外服务器速度也能跑满 300Mbps。

**Comment by AndersonGhost** [comment]
原来是这样啊   对于目前的这个网络而言（不更换网络），有提升解决的办法吗？

**Comment by XIU2** [comment]
基本没戏，因为这是运营商故意限速的（国际宽带），你公司也是因为加钱才会更快。

**Comment by XIU2** [comment]
不同地区不同运营商都不太一样，我也是联通，但是除了晚上高峰期，我都能轻松找到 20-30MB/s 的 IP。

**Comment by AndersonGhost** [comment]
就是说我的运营商，故意将我的国际带宽限制在1.5Mb/s以内了吗？这个不可以投诉吗？

**Comment by XIU2** [comment]
没希望，因为运营商的律师团队不是白吃白喝的。
宽带合同早就规避了这些，并没有保证国际宽带速度，这种情况下投诉是没什么用的。  

当然也不一定是完全限制国际宽带到 1.5MB/s 了，可能只是限制了 Cloudflare CDN 的服务器？你可以找一些提供下载文件的国外网站测速看看。  

当然，现在都八点了，已经进入了国外高峰期了，这时候往往是国内用户连接国外最卡的时候了（会持续到凌晨）。

**Comment by AndersonGhost** [comment]
感谢大佬的耐心解答！！很感激！确实如你所言，如果我不套CDN的话，通过直连外网，网速可以达到20MB/s，而使用了 Cloudflare CDN的话，速度最快不超过1.5MB/s。那就是说运营商对我们小区的 Cloudflare CDN 做了限制，这个应该无解了吧。

**Comment by XIU2** [comment]
嗯，至少我想不到什么解决办法。  

不太可能是针对你的小区这么小范围，应该是全市甚至全省范围的，因为测试环境太少，无法具体判断。  

最好是像我一开始说的那样，把公司里测速快的 IP 放到家里测速看看。

****

另外，你试试把 `ip.txt` 文件中的内容改成下载这两个，测速看看如何。
```
35.200.109.86/32
202.81.235.92/25
```

> 这两个是 Cloudflare 与其他人合作的，所以并没有包含在 Cloudflare 公开的 IP 段中，我也是从其他使用我软件的人那里知道的（Issues）。

**Comment by AndersonGhost** [comment]
大佬您好，根据您的提示，我测得如下结果：

# XIU2/CloudflareSpeedTest v1.4.4

开始延迟测速（模式：TCP IPv4，端口：443）：
12 / 12 [-----------------------------------------------------------
开始下载测速：
3 / 3 [-------------------------------------------------------------
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
202.81.235.92     4       4       0.00    74.75     3.81
35.200.109.86     4       4       0.00    224.51    1.61
104.24.5.132      4       4       0.00    231.51    0.75

其中，最后一个IP是在公司测得10MB/s的节点，在家中测得为0.75MB/s，上面两个节点是您提供的。
第一个居然超过了1.5MB/s！

**Comment by XIU2** [comment]
因为你看 `202.81.235.92` 的延迟就不对劲，我平时测速最低的也才 130ms+，而这个 IP 却只有几十 ms。  
这个服务器 IP 实际归属地是香港，自然比其他美国的服务器 IP 快一些。

**Comment by AndersonGhost** [comment]
这是怎么回事呢？这个IP在我这里确实很快

**Comment by XIU2** [comment]
我说了呀，这个是香港的 IP。  
而 Cloudflare 自己的 CDN IP 中，其实也有香港的 CDN IP 节点，但是国内电信、联通访问这些香港 CDN IP 都需要绕其他国家，导致延迟还不如直连美国呢，只有移动的才能直连 Cloudflare 香港的 CDN IP。

**Comment by AndersonGhost** [comment]
谢谢大佬不厌其烦的解答，受教了！感谢！！您还有香港或是其他地方的CDN IP吗？

**Comment by XIU2** [comment]
我只知道这三个，还都是在本项目其他 Issues #15 里知道的。
```
35.200.109.86/32
202.81.235.61/32
202.81.235.92/32
```

**Comment by AndersonGhost** [comment]
感谢大佬的无私！！谢谢！！

**Comment by XIU2** [comment]
如果没什么问题的话，就关闭该 Issues 吧。  
走之前，如果觉得软件还不错，可以点个 [⭐](https://github.com/XIU2/CloudflareSpeedTest/stargazers) 鼓励一下~

**Comment by AndersonGhost** [comment]
好的，必须的

**Comment by AndersonGhost** [comment]
已经点了哈   可以关闭了   大佬~

**Comment by AndersonGhost** [comment]
> 我只知道这三个，还都是在本项目其他 Issues #15 里知道的。
> 
> > 这个人也是在用我的软件去扫描未公开的 Cloudflare CDN IP 节点（只要下载测速不是 0.00 就说明可以用）。
> 
> ```
> 35.200.109.86/32
> 202.81.235.61/32
> 202.81.235.92/32
> ```

大佬，您好~  自从您公布了这几个节点后，现在已经变得超级慢了【笑哭】

**Comment by XIU2** [comment]
我试了下并不慢呀：
```
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
35.200.109.86     4       4       0.00    157.63    15.87
202.81.235.92     4       4       0.00    42.17     11.23
202.81.235.61     4       4       0.00    43.66     11.00
```

看了下公开后 7 小时内的下载次数也才 153 次（全平台）。

**Comment by AndersonGhost** [comment]
可能是我这边的网络有问题【笑哭】

**Comment by XIU2** [comment]
因为目前软件用的是我自建的下载测速地址，所以我在 Cloudflare 可以看到该文件下载测速的次数。  
发现个很奇怪的事情，**晚上使用该软件测速的人最多**。。。  

之所以奇怪，是因为晚上是**高峰期**（晚上~凌晨），这段时间测速往往结果会比较捉急，**与其他时间测速结果相差较大**，所以我在项目使用说明里注明了**建议避开高峰期使用**。

**Comment by AndersonGhost** [comment]
大佬，经过测试（用VPS套这个ip来看油管），现在确实是变慢了很多~  毕竟服务器的带宽是有限的

**Comment by XIU2** [comment]
还好吧，即使是现在处于**高峰期顶峰的半夜**，我这边测速结果依然很稳定（那两个延迟低的相比 5 个小时前差别不大）。
```
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
202.81.235.61     4       4       0.00    50.94     10.57
202.81.235.92     4       4       0.00    48.19     9.14
35.200.109.86     4       4       0.00    160.53    2.43
```

**Comment by AndersonGhost** [comment]
真羡慕大佬的网络环境啊~~

**Comment by AndersonGhost** [comment]
可能还是我这边的运营商做了限制

**Comment by XIU2** [comment]
那个 Issues 的人也没说怎么找非公开的 Cloudflare CDN IP，否则我也能没事找找，不可能只有这三个。  

我这个人就很喜欢分享、帮助别人，遇到什么好东西我捂不住，总想告诉别人。。。
特别是最近几个 Issues 间接反映了一些人测速结果不理想，我就习惯性的把这三个 IP 告诉你们了，后来干脆我就直接加到 `ip.txt` 中了。这样也算是对大家有所帮助了~

**Comment by AndersonGhost** [comment]
是呀！ 感觉大佬是一个十分热心的人，造福了我们这么多人~  十分感谢啊！！一定会有福报的~
