### ISSUE TITLE
延迟测试能否多加一个可以自选的ping模式

### ISSUE THREAD

**Issue by RealSlakey** [XIU2/CloudflareSpeedTest#211]
瞄了一下代码似乎是用tcping测试延迟的，最近电信似乎对Cloudflare CDN进行了大量阻断，其导致的结果就是用CFST测出来的是无丢包和正常低延迟的，但是自己pingCFST测速结果时，很多都是ping不通（同时x.x.x.x/cdn-cgi/trace也是无法打开的状态）导致无法作为优选CDN节点
如果CFST中延迟测试多加一个ping模式可以减少此类情况发生

**Comment by XIU2** [comment]
Ping 是 ICMP 协议，而无论是网站，还是套的代理走的都是 TCP 协议，因此 TCP 协议更准确。

**Comment by RealSlakey** [comment]
有速度也ping不通

**Comment by RealSlakey** [comment]
> 有速度也ping不通

虽然听上去很离谱，但是这几天我这电信的情况确实是这样的

**Comment by XIU2** [comment]
那你可能需要选择放弃使用 Cloudflare 了~

**Comment by RealSlakey** [comment]
> 

不好意思大佬，我排查了一下，原因找到了，是由于我换了路由上openwrt的科学上网插件，之前写的shell脚本运行前会停止ssrplus的服务`/etc/init.d/shadowsocksr stop`再调用CFST进行测速，最近几天换用passwall后没有注意到这部分，所以出现了测试结果和本机ping结果不一致的情况...
这几天属实把我自己都绕进去了，没想到是因为这个，感谢大佬的帮助啦
