### ISSUE TITLE
这两天下载测速队列很高，都有2000多，导致一直等待测不了速

### ISSUE THREAD

**Issue by kidxiang** [XIU2/CloudflareSpeedTest#213]
开始下载测速（下载速度下限：2.00 MB/s，下载测速数量：4，下载测速队列：2061）：

请问，这个“下载测速队列”是什么意思？需要跟所有测速的人一起排队吗？

我用的自己建立的worker反代的测速链接，这样也需要和其他人一起排队吗？那自建链接就没什么意义了吧

如果是自建链接，能否优化一下排队呢？

**Comment by XIU2** [comment]
虽然你已经关了，但我需要给你科普解释下。

CloudflareST 步骤：
1. 延迟测速
2. 从低到高排序（根据延迟、丢包）
3. 根据设定的**延迟上下限条件**过滤（如有）
4. 对上面得到的 IP 列表挨个进行下载测速
5. 根据设定的**下载速度条件**过滤（如有）

**下载测速队列**指的是：延迟测速并排序后，**等待下载测速的 IP 列表数量**（因为是一个个测速的）。
