### ISSUE TITLE
 ip.txt 是否剔除了跟百度云合作的节点？

### ISSUE THREAD

**Issue by dordun** [XIU2/CloudflareSpeedTest#214]
ip.txt 是否剔除了跟百度云合作的节点？

**Comment by XIU2** [comment]
只去掉了部分被 Cloudflare 限制免费套餐域名使用的 IP 段。
有其他需求的，可以自行剔除。

**Comment by dordun** [comment]
> 
不知道你有关于百度云加速节点的IP段吗？

**Comment by XIU2** [comment]
没有。。。毕竟 Cloudflare 几年前就跟百度分手了（改为京东云了）。
当初百度云加速的 IP 用的是 Cloudflare 的 IP 段，因此 IP 段估计都收回了。

**Comment by dordun** [comment]
> 

那意思就是百度云不跟cloudflare合作了吗？

**Comment by XIU2** [comment]
几年前就终止合作了。

**Comment by dordun** [comment]
> 没有。。。毕竟 Cloudflare 几年前就跟百度分手了（改为京东云了）。 当初百度云加速的 IP 用的是 Cloudflare 的 IP 段，因此 IP 段估计都被 Cloudflare 收回了。

京东云是跟cloudflare合作的吗？那京东云是中国的京东吗？

**Comment by XIU2** [comment]
京东云不是中国的京东还能是哪里的京东？
你自己去 Cloudflare 官网看吧。

**Comment by dordun** [comment]
> > 京东云不是中国的京东还能是哪里的京东？ 你自己去 Cloudflare 官网看吧。
> 
> 那你可以把地址给我一份嘛？找不到

谢谢！
