### ISSUE TITLE
建议增加测速返回地址在本地是否能 ping 通的检测

### ISSUE THREAD

**Issue by nie11kun** [XIU2/CloudflareSpeedTest#216]
最近在使用中发现正常测速后返回的 IP 显示的速度都很高，但是经过我手动测试，在本地有一部分测速正常的 IP 都无法 ping 通，导致实际上这些 IP 不可用。

**Comment by XIU2** [comment]
软件是 TCP Ping 443 端口测试 + TCP 下载测试。
如果延迟测速+下载测速都通过了，说明是可用的。

你的意思是得到的 IP 结果都测试通过了，结果 ICMP Ping 不可用？导致完全不能用？

无论是套代理还是网站，都是走的 TCP 协议。

**Comment by XIU2** [comment]
今天又频繁遇到前面说的情况。

而且我这次很确定是 运营商/墙 干的，干扰的很厉害，不访问那么一切正常，一旦访问可能很快就超时了，而且是很标准的 3 分钟，这么有规律显然是故意的。
让我想到了 Steam、Github 的 SNI 干扰，也是一但访问可能就会超时 3 分钟，都是**只局限于单个宽带用户**（即只有你超时，其他人哪怕是邻居也完全不受影响），不过这次是针对的 Cloudflare CDN IP。

看来距离 Cloudflare 完全退出中国不远了~

**Comment by nie11kun** [comment]
> 今天又频繁遇到前面说的情况。
> 
> 而且我这次很确定是 运营商/墙 干的，干扰的很厉害，不访问那么 IP 一切正常，一旦访问可能很快就超时了，而且是很标准的 3 分钟，这么有规律显然是故意的。 让我想到了 Steam、Github 的 SNI 干扰，也是一但访问可能就会超时 3 分钟，都是**只局限于单个宽带用户**（即只有你超时，其他人哪怕是邻居也完全不受影响），不过这次是针对的 Cloudflare CDN IP。
> 
> 看来距离 Cloudflare 完全退出中国不远了，且用且珍惜吧~

是的，的确是测试出来的 IP 显示速度很高也没有丢包，我实际使用就是 timeout 连不上，白天基本正常，一到晚上就凉了。
通过 ping 检测可用的 IP 我这边断断续续可用。

**Comment by XIU2** [comment]
那你应该和我遇到的情况差不多，不过这问题无解，有 IPv6 的尝试下 IPv6 吧。。。
