### ISSUE TITLE
文件东西都更新了 为什么网站总是断连 又好 又断开

### ISSUE THREAD

**Issue by SKTBaker** [XIU2/CloudflareSpeedTest#219]
有时候死活连不上

**Comment by XIU2** [comment]
墙 / 运营商的问题。
#217

**Comment by SKTBaker** [comment]
我想重装请问怎么删除卸载清空原来的东西呢
重装对连接有影响吗

**Comment by XIU2** [comment]
啥玩意？你来错地方了吧。。。

你说的话，我完全无法理解和该项目有什么关联。。。

**Comment by SKTBaker** [comment]
> 啥玩意?你来错地方了吧……
> 
> 你说的话,我完全无法理解和该项目有什么关联…
> 
> cloudflare是单文件程序,绿色无依赖的,解压即用,不用就直接删除,压根不存在安装、卸载,重装的说法

> 啥玩意?你来错地方了吧……
> 
> 你说的话,我完全无法理解和该项目有什么关联…
> 
> cloudflare是单文件程序,绿色无依赖的,解压即用,不用就直接删除,压根不存在安装、卸载,重装的说法。

https://www.likecs.com/show-202080.html
我是别的网站到这里的还有知乎 找到了
