### ISSUE TITLE
下载测速时间参数自定义值无效，支持按下载速度排序

### ISSUE THREAD

**Issue by muziling** [XIU2/CloudflareSpeedTest#22]
默认的dt 5参数，测速只有700k不到， 参数改为dt 30，速度有2.15MB/s，这个速度才是正确的。

参数的默认值很不合理

**Comment by muziling** [comment]
另外希望能加一个参数输出最快的单个节点IP，而不是输出到csv中

**Comment by XIU2** [comment]
测速文件只有 300MB，如果测速时间太长，也会导致测速结果失衡。

**Comment by XIU2** [comment]
> 另外希望能加一个参数输出最快的单个节点IP，而不是输出到csv中

至于这个要求，你可以设置相应的过滤条件来解决。

**Comment by muziling** [comment]
> > 另外希望能加一个参数输出最快的单个节点IP，而不是输出到csv中
> 
> 至于这个要求，你可以设置相应的过滤条件来解决（四个相关参数 `-dn -tl -sl -p` 组合使用）。

好像只有按ping延迟排序，没有按测速结果排序

**Comment by XIU2** [comment]
以前在用 Cloudflare 官方下载测速地址时，是默认下载测速时间 10 秒，结果后来似乎是用的人太多，导致 Cloudflare 官方下载测速地址一到晚上就提示资源上限无法使用了。  
后来我就自建了一个文件用于测速，担心流量问题（毕竟官方的都跑到上限了）只做了 300MB，现在导致的问题就是，如果你的下载速度足够快，那么下载测速时间太长，就会导致下载测速结果低于实际平均速度。  
而如果下载速度太慢，而下载测速时间太短，也会导致下载测速结果低于实际平均速度。。。

**Comment by XIU2** [comment]
300MB 文件理论上在默认的 5秒时间时，需要 60MB/s 下载速度才会下载完。  
我倒是没考虑到如果速度太慢了会怎么样，因为我这边除非晚上，否则都能轻松泡个 20-30MB/s。  

你试过下载测速时间指定为 10 秒吗？和指定为 30 秒差别大不大？  
如果不大，那我就改回 10 秒默认值好了。

**Comment by muziling** [comment]
可能不是秒数的问题，我刚指定10秒，自己数，测试了6秒就结束了，但显示的速度只有500k， 
重复测试，也是用10秒，会得到2M~3M的速度

**Comment by XIU2** [comment]
比较奇怪，我研究下。

**Comment by muziling** [comment]
另外我用的是amd64版本，在openwrt x64上运行的。 希望对排查问题有帮助

**Comment by XIU2** [comment]
发现一个弱智 BUG 导致无论设置多少都是 5 秒...

**Comment by XIU2** [comment]
修复这个 BUG 后，又发现一个问题，如果下载速度太慢，则会超过设定的时间。。。

**Comment by XIU2** [comment]
你下载这个修复 `-dt` 参数无效 BUG 后，默认为 10 秒的试试。

[CloudflareST_linux_amd64.zip](https://github.com/XIU2/CloudflareSpeedTest/files/5716722/CloudflareST_linux_amd64.zip)

**Comment by XIU2** [comment]
我又研究了下，添加了一个**按下载速度排序**功能，这个功能是默认的，不需要添加参数。  

当你进行了下载测速时才会**按下载速度排序**，如果使用了 `-dd` 参数禁用了下载测速，或者指定过滤条件后却没找到一个符合条件的，则依然会输出**按延迟排序**的结果。

你下载试试，看有没有什么问题。

[CloudflareST_linux_amd64.zip](https://github.com/XIU2/CloudflareSpeedTest/files/5716963/CloudflareST_linux_amd64.zip)

**Comment by XIU2** [comment]
## v1.4.5 更新内容
1. **新增** 下载速度排序。**#22**   
`只有下载测速后才会按下载速度排序。`
`如果使用了 -dd 参数禁用了下载测速，或者指定过滤条件后却没找到一个符合条件的 IP，则结果依然会按延迟排序。`
2. **修复** 下载测速时间 `-dt` 参数自定义值无效的问题。**#22**   
3. **回调** 下载测速时间默认值为 10 秒。**#22**

**Comment by muziling** [comment]
加了sl 参数后，dn 参数就无效了， 我想要的是sl 设置后，如果测速有超过这个速度的IP，就停止测速，不需要几百上千个都测试过去。

**Comment by XIU2** [comment]
当满足条件的 IP 足够数量后（-dn）就会停止。

**Comment by muziling** [comment]
明白了，刚试了，程序的dn参数说明看不出来是这个意思

**Comment by XIU2** [comment]
https://github.com/XIU2/CloudflareSpeedTest#使用示例

这里最后我写了。

**Comment by XIU2** [comment]
昨天更新修复了一个 BUG，也就是前面你说的下载测速时间不准确的问题。  

****

## v1.4.6 更新内容
1. **修复** 下载测速时间不准确、卡住的问题。  
`下载测速时，可能会遇到实际测速时间明显超过 -dt 指定的时间，甚至发生下载测速卡住的情况。`
