### ISSUE TITLE
能否增加quic/udp模式的测速

### ISSUE THREAD

**Issue by HX-Technology-LLC** [XIU2/CloudflareSpeedTest#225]
有些网站可以用quic访问,一些优选的IP尽管tcp速度较快,但是udp速度不佳

**Comment by XIU2** [comment]
速度不佳是因为 UDP 协议在国内被运营商 QOS 的很严重。

**Comment by cherinyy** [comment]
个人认为推出对于 HTTP/3 的测速功能还是有必要的。IPv6 刚推出的时候也是一堆问题，到现在基本可用的程度，也经过了不短的时间。

IPv6 也好，HTTP/3 也好，都是不可阻挡的发展趋势。
