### ISSUE TITLE
我哪里弄错了么？似乎不好使。

### ISSUE THREAD

**Issue by Gslw** [XIU2/CloudflareSpeedTest#23]
```
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

尝试新的跨平台 PowerShell https://aka.ms/pscore6

PS C:\Users\Htm_w> cd G:\CloudflareST_windows_amd64
PS G:\CloudflareST_windows_amd64> .\CloudflareST.exe -tl 170 -sl 8 -dn 10
# XIU2/CloudflareSpeedTest v1.4.5

开始延迟测速（模式：TCP IPv4，端口：443）：
27928 / 27928 [-----------------------------------------------------------------------------------------------] 100.00%
开始下载测速（延迟时间上限：170 ms，下载速度下限：8 MB/s）：
62 / 2230 [-->__________________________________________________________________________________________________] 2.78%
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
104.31.141.88     4       4       0.00    151.66    0.22
104.25.97.251     4       4       0.00    155.25    4.05
104.31.70.245     4       4       0.00    156.49    3.40
104.31.14.119     4       4       0.00    159.58    0.37
104.27.146.228    4       4       0.00    159.68    0.15
172.67.48.153     4       4       0.00    159.99    0.23
172.67.52.177     4       4       0.00    160.05    0.18
172.67.74.235     4       4       0.00    161.20    0.20
172.67.60.5       4       4       0.00    161.27    0.17
172.67.35.32      4       4       0.00    161.38    0.21
104.23.130.6      4       4       0.00    161.46    0.32
172.67.47.242     4       4       0.00    161.73    0.43
104.16.242.183    4       4       0.00    161.90    0.28
172.67.45.245     4       4       0.00    161.95    0.58
104.25.112.130    4       4       0.00    162.01    0.11
104.23.134.186    4       4       0.00    162.21    0.32
104.25.108.134    4       4       0.00    162.24    0.12
104.27.73.70      4       4       0.00    162.66    0.23
172.67.166.46     4       4       0.00    162.70    0.04
104.16.247.130    4       4       0.00    163.04    0.20

完整测速结果已写入 result.csv 文件，请使用记事本/表格软件查看。
按下 回车键 或 Ctrl+C 退出。
```

**Comment by XIU2** [comment]
项目里写了：https://github.com/XIU2/CloudflareSpeedTest#使用示例

```
# 如果一个满足条件的 IP 都没有，那么就会正常输出结果（和不指定条件一样）。
```

你这种情况就是最终测速结果中，没有找到任何一个满足平均延迟低于 170ms 且下载速度高于 8MB/s 条件的 IP。  
所以软件就会和不指定条件一样正常输出结果。

**Comment by Gslw** [comment]
> 项目里写了：[https://github.com/XIU2/CloudflareSpeedTest#使用示例](https://github.com/XIU2/CloudflareSpeedTest#%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B)
> 
> ```
> # 如果一个满足条件的 IP 都没有，那么就会正常输出结果（和不指定条件一样）。
> ```
> 
> 你这种情况就是最终测速结果中，没有找到任何一个满足**平均延迟低于 170ms 且下载速度高于 8MB/s** 条件的 IP。
> 所以软件就会和不指定条件一样输出完整结果。
> 
> 我看你最终结果中，最快的也才 4MB/s，我看你是半夜测速的，而我的项目开头就写了：
> 
> > **注意：建议测速时避开晚上高峰期（国外）**，否则测速结果会与其他时间**差距很大...**
> 
> 你尝试白天测速试试，如果速度依然不理想，那么把 `ip.txt` 内容改成下面这三个 IP 试试：
> 
> ```
> 35.200.109.86/32
> 202.81.235.61/32
> 202.81.235.92/32
> ```

可是下载测速只进行到62 / 2230就知道后边的也不满足？

**Comment by XIU2** [comment]
因为你设置了 `-tl 170` 参数，所以软件在测速到 170ms 平均延迟的 IP 时，**不管是否凑够满足条件的 IP 数量，都会停止测速。**  

这是因为虽然延迟低不等于速度快，但是**延迟低中出现速度快的 IP 概率更高**，所以如果延迟低的几十个都找不到一个速度快的 IP，那延迟高的 IP 中就更难找到速度快的了。  

所以我才建议同时指定 `-tl` 参数，**避免软件一直测速下去**，这是无效测速，基本是浪费时间。

**Comment by Gslw** [comment]
> 因为你设置了 `-tl 170` 参数，所以软件在测速到平均延迟 170ms 的 IP 时，**不管是否凑够满足条件的 IP 数量，都会停止测速。**
> 
> 这是因为虽然延迟低不等于速度快，但是**延迟低中出现速度快的 IP 概率更高**，所以如果延迟低的 IP 中都找不到一个速度快的，那**延迟高的 IP 中就更难找到速度快**的了。
> 
> 所以我才建议同时指定 `-tl 和 -sl` 两个参数，**避免软件一直测速下去**，这是无效测速，只是浪费时间。

低延迟里有高速这个好理解，但是62 / 2230之后也会有低延迟啊，没准有符合的速度呢，当然的确是2230个都测是耗时间

你现在说的这个了逻辑就是前10个170延迟里下载速度没满足的其他的测都没必要了，这不严谨吧？

**Comment by XIU2** [comment]
软件是先延迟测速，然后把结果根据按延迟从低到高排序。  
然后再根据延迟排序去下载测速，也就是说下载测速是从延迟最低的 IP 开始的。  
测速到 170ms 的 IP，后面就没有 170ms 的 IP 了（有丢包的除外，但是只要丢包，速度肯定有影响）。

**Comment by Gslw** [comment]
嗯，我知道延迟排序后测速，按我贴出来的测速了62个就结束。按照输出结果只测试到163ms左右。

你的意思163ms后边的都是有丢包的？至于你说的后面就没有低于 170ms 的 IP 了怎么会，第一步延迟筛选完这2230应该都低于170ms才对。

**Comment by Gslw** [comment]
> 软件是先延迟测速，然后把延迟测速结果**按延迟从低到高排序**。
> 然后再根据延迟排序去下载测速，也就是说**下载测速是从延迟最低的 IP 开始的**（你没发现测速结果中延迟都低于 170ms 吗？）。
> 
> 测速到 170ms 的 IP 时，后面就没有低于 170ms 的 IP 了（有丢包的除外，因为丢包会极大的影响平均延迟和下载速度，所以默认扔到测速结果列表最后了）。
> 
> 而且是你自己设置的 `-tl 170` 呀，你可以不设置，或者值写的高一些，比如 `-tl 200`，这样测速范围会更大。
> 
> 软件参数说明 `-h` 中写了：
> 
> ```
> -dn 20
>     下载测速数量；延迟测速并排序后，从最低延迟起下载测速的数量；(默认 20)
> ```
> 
> 项目首页的使用示例中，我也补充了下：
> 
> ```
> # 如果一个满足条件的 IP 都没找到，那么就会和不指定条件一样输出完整结果。
> # 所以建议先不指定条件测速一遍，看看平均延迟和下载速度大概在什么范围，避免指定条件过低/过高！
> ```

嗯，我知道延迟排序后测速，按我贴出来的测速了62个就结束。按照输出结果只测试到163ms左右。

你的意思163ms后边的都是有丢包的？至于你说的后面就没有低于 170ms 的 IP 了怎么会，第一步延迟筛选完这2230应该都低于170ms才对。

**Comment by XIU2** [comment]
可能是 163ms 到 170ms 之间没有 IP，比如 163ms 后下一个 IP 的平均延迟就是 171ms 了，那么也会停止测速。  
因为你使用 -tl 170 参数就代表只接受 170ms 延迟以下的测速结果了。

是你主动放弃了平均延迟 170ms 以上的测速结果。

**Comment by Gslw** [comment]
> 可能是 163ms 到 170ms 之间没有 IP，比如 163ms 后下一个 IP 的平均延迟就是 171ms 了，那么也会停止测速。
> 因为你使用 -tl 170 参数就代表只接受 170ms 延迟以下的测速结果了。
> 
> 是你主动放弃了平均延迟 170ms 以上的测速结果。

163ms-170ms没有IP为啥会存在63-2230？

第一步从 27928里筛选出的这2230个不就是为了没有170ms以上的么？

**Comment by XIU2** [comment]
我项目和软件里没有任何地方说锅 第一步 就根据条件筛选了。  

第一步是先延迟测速（就是你看到的进度条）。
然后获得测速结果，再去排序，再去下载测速，再去筛选。

条件筛选是最后进行的，而不是第一步延迟测速后就进行了。

你看到的 2230 实际上是所有延迟测速通过的 IP。
63 是你下载测速进度。

**Comment by Gslw** [comment]
> 我项目和软件里没有任何地方说过 第一步 就根据条件筛选了。
> 
> 第一步是先延迟测速（就是你看到的进度条）。
> 然后获得测速结果，再去根据延迟从低到高排序，再去下载测速，最后去按条件筛选。
> 
> 条件筛选是最后进行的，而不是第一步延迟测速后就进行了。
> 
> > 因此，如果找不到一个满足条件的 IP，软件就会像不指定条件一样输出完整结果。
> 
> 目前 `-tl` 平均延迟上限是不能单独使用的，只会在下载测速中搭配 `-sl` 下载速度下限 条件筛选。
> 
> ```
>     -tl 200
>         平均延迟上限；只输出低于指定平均延迟的 IP，与下载速度下限搭配使用；(默认 9999 ms)
>     -sl 5
>         下载速度下限；只输出高于指定下载速度的 IP，凑够指定数量 [-dn] 才会停止测速；(默认 0 MB/s)
> ```
> 
> 你看到的 2230 实际上是所有延迟测速通过的 IP，而不是仅仅 170ms 延迟以下的 IP。
> 而 63 是你下载测速进度，也就是 2230 个延迟测速结果中，只有 63 个是低于 170ms 延迟的 IP。

第一部没有筛选延迟，那这延迟测速后是依据什么从27928里排序后仅剩下2230个？

这2230个难道不是通过了什么样的标准剩下的，按你说的只排序不应该剩下27928个？

另外62是下载测速个数，进度是62/2230-----------2.78%

**Comment by XIU2** [comment]
在没有使用 `-allip` 参数的情况下，软件是会每个 IP 段随机一个 IP，因为这个 IP 是随机的，所以并不是所有都能用，再去掉丢包率过高的 IP。
另外，你看到的 27928 实际上是 ✖ 4 的，因为延迟测速次数默认是 4 次，实际上 IP 只有 6982 个。

**Comment by Gslw** [comment]
好的，我很少用Github，本身也不会编程，感谢你一直耐心的解答。

6982个IP第一步进行延迟排序每个测4次[总共27928次]，那第二步剩下的2230个或者2230次测速是怎么剩下来的？不是说没筛选么？

**Comment by XIU2** [comment]
我前面不是说了吗？
> 软件是会每个 IP 段随机一个 IP，因为这个 IP 是随机的，所以不是所有都能用，再去掉丢包率过高的 IP。
> 所以这也算是初步筛选过滤，但并不是根据 -tl -sl 参数而条件筛选过滤的。

**Comment by Gslw** [comment]
嗯，明白了。第一步说是延迟测试其实是丢包率合格后的延迟排序给第二步。

那我这第二步意思是测试到62个后面的延迟都不满足170ms以下，所以没必要测速了，就结束按默认输出结果了。没错吧？

**Comment by XIU2** [comment]
是的，第一步延迟测速本身也算是初步过滤，过滤掉了不能用的 IP（丢包率高的 IP 也算不能用）。

你测速到 62 个 IP 时，后面的 IP 平均延迟都高于 170ms 了，所以按照你设定的条件，软件就会停止测速。

**Comment by XIU2** [comment]
如果没什么问题了，就关闭该 Issues 吧。
另外，走之前如果觉得对你有所帮助，希望可以点击项目右上角的 [⭐ Star] 鼓励一下吧！

**Comment by Gslw** [comment]
好的，耽误你这么久抱歉，谢谢！
