### ISSUE TITLE
Openwrt路由器，SSH按照教程一步步做的，前面一切正常，运行报错

### ISSUE THREAD

**Issue by cheyuze** [XIU2/CloudflareSpeedTest#232]
root@OpenWrt:~# cd CloudflareST
（这里之前下载CloudflareST_linux_amd64，2.03版本按照教程已经进行过了）
（解压缩也正常）
root@OpenWrt:~/CloudflareST# ./CloudflareST
./CloudflareST: line 1: syntax error: unexpected "("
root@OpenWrt:~/CloudflareST# 

cfst_hosts.sh脚本也可以正常运行。虽然也会报错但可以证明前面操作是无误的。
root@OpenWrt:~/CloudflareST# chmod +x cfst_hosts.sh
root@OpenWrt:~/CloudflareST# bash cfst_hosts.sh
开始测速...
cfst_hosts.sh: line 35: ./CloudflareST: cannot execute binary file: Exec format error
CloudflareST 测速结果 IP 数量为 0，跳过下面步骤...
root@OpenWrt:~/CloudflareST#

**Comment by XIU2** [comment]
这种报错，说明你下载错了 CloudflareST 版本，挨个尝试不同版本吧。

**Comment by cheyuze** [comment]
ARMv8 Processor x 6 (600MHz 1200MHz, 38.1°C)

> 报错，说明你下载错了CloudflareST个版本（不同系统、架构都不一样的），欢迎试用不同版本吧。

架构 ARMv8 Processor x 6 (600MHz 1200MHz, 38.1°C)
这个是ARM64位吧emmmTAT

**Comment by cheyuze** [comment]
> 这种报错，说明你下载错了 CloudflareST 版本（不同系统、架构都是不一样的），挨个尝试不同版本吧。

感谢，问题已解决，用32位就正常了emm
