### ISSUE TITLE
不知道这个测速的代码是啥，能不能加一个像curl的resolve这个参数

### ISSUE THREAD

**Issue by wo2429** [XIU2/CloudflareSpeedTest#234]
curl --resolve HOST:PORT

不太懂，勿喷

**Comment by XIU2** [comment]
Curl 的 `--resolve` 参数是用来手动指定域名 IP 的。

例如：
``` bash
curl --resolve "api.cloudflare.com:443:X.X.X.X" https://api.cloudflare.com/cdn-cgi/trace
```
不使用该参数时，Curl 会先 DNS 解析该域名得到 IP 地址，然后再去访问该 IP。
而使用该参数后，Curl 将跳过 DNS 解析，直接访问 `X.X.X.X` 这个 IP（和 Hosts 文件内手动指定域名解析 IP 是一个意思）。

**Comment by wo2429** [comment]
是的，我的意思是测速的时候，能不能这样测？因为有的ip是一定要经过证书的握手才能测出速度的，单纯的使用ip去测速，测不出来

**Comment by wo2429** [comment]
好吧，因为发现一些ip测速没速度，但是放到v2里面是可以用的

**Comment by XIU2** [comment]
也只能是这个原理，单纯 IP 是无法下载测速。
所以才需要一个 下载测速地址 依托，而我当初自建的因为用的人太多了被 Cloudflare 限速了，后来就建议大家自建了。

**Comment by wo2429** [comment]
ok  明白了，感谢

**Comment by XIU2** [comment]
目前软件内置的默认下载测速地址，都是大家自建并共享出来的，我给做成了一个重定向，每分钟切换一个，但不保证可用性。

你说的测速没速度，可能是下载测速地址的问题，也可能是因为 #217 ，有精力你可以折腾下，不过 Cloudflare 在国内因为各种原因导致很玄学，我也很蛋疼，特别是几个月前开始我这边被阻断的不行不行的。。。已经放弃 IPv4 了。

**Comment by wo2429** [comment]
除了cf官方给出的ip段以外，可以用另一个大锅的项目里面扫描的ip，用来代理或者加速网站，都还是很不错的   自建一个ddns即可

**Comment by XIU2** [comment]
那些 IP 都是第三方个人自建的 Cloudflare CDN 中转（反代），虽然没啥安全隐患（不涉及加解密），但是也不保证可靠性，因为一旦用的人多了，肯定会被搭建者发现，然后就会限制或者关闭，所以只会越用越少。。。

**Comment by wo2429** [comment]
好的，非常感谢

**Comment by wo2429** [comment]
老哥再麻烦一下，在curl中，可以这样进行测速，而且放到v2中也是可以用的，服务器下行10M的，能跑满
`curl -o /dev/null -s -w %{speed_download} -m 10 --resolve "cloudflare.com:443:47.100.124.138" -O https://dl.feizhucache.ml/file/200MB.bin`
![](https://pic1.imgdb.cn/item/6332afb116f2c2beb1db5c09.png)

但是在ST中测速，测不出来是什么原因
![](https://pic1.imgdb.cn/item/6332afaf16f2c2beb1db59a8.png)

**Comment by XIU2** [comment]
因为你的 curl 代码写错了。
你用的是：
```
curl -o /dev/null -s -w %{speed_download} -m 10 --resolve "cloudflare.com:443:47.100.124.138" -O https://dl.feizhucache.ml/file/200MB.bin
```

而正确的应该是这样：

```
curl -o /dev/null -s -w %{speed_download} -m 10 --resolve "dl.feizhucache.ml:443:47.100.124.138" -O https://dl.feizhucache.ml/file/200MB.bin
```

**Comment by wo2429** [comment]
额  好吧，但是ip确实能用，只不过网速不太快

**Comment by XIU2** [comment]
不是速度快慢的问题，是有限制。

用 `dl.feizhucache.ml` 会握手失败，但是用 `api.cloudflare.com` 就可以正常链接，因此不属于 CloudflareST 的问题。

``` cmd
D:\>curl -o 0.txt --resolve "dl.feizhucache.ml:443:47.100.124.138" https://dl.feizhucache.ml/file/200MB.bin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed


D:\>curl -o 1.txt --resolve "api.cloudflare.com:443:47.100.124.138" https://api.cloudflare.com/cdn-cgi/trace
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   199    0   199    0     0    738      0 --:--:-- --:--:-- --:--:--   742
```

``` cmd
D:\>curl -I -v --resolve "dl.feizhucache.ml:443:47.100.124.138" https://dl.feizhucache.ml/cdn-cgi/trace
* Added dl.feizhucache.ml:443:47.100.124.138 to DNS cache
* Hostname dl.feizhucache.ml was found in DNS cache
*   Trying 47.100.124.138:443...
* Connected to dl.feizhucache.ml (47.100.124.138) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* schannel: failed to receive handshake, SSL/TLS connection failed
* Closing connection 0
curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed
```

**Comment by wo2429** [comment]
明白了，感谢解答    谢谢谢谢
