### ISSUE TITLE
测延迟时经常卡住

### ISSUE THREAD

**Issue by CussiusKon** [XIU2/CloudflareSpeedTest#238]
测延迟过程中经常卡住不动，测速有时也这样，重新运行可能会好也可能卡在另一个地方，是什么原因呢？

**Comment by XIU2** [comment]
请描述详细一点，我没有遇到过这种情况，也没有人反馈过类似情况。

尝试调整降低 `-n` 参数试试（默认 200）。
尝试减少 `ip.txt` 内的 IP 段数量试试。

这种模糊的情况，只能排除法一点点排查。

**Comment by CussiusKon** [comment]
> 
我用的参数，
```
-t 2 -tl 200 -sl 10 -url https:
```
-n默认，我是在pc上用，我觉得应该不至于是线程数的问题，有时设为500也能成功。ip库就是用的程序自带的那些。有时就是卡在测延迟某进度一直不动，发生频率感觉挺高的

**Comment by XIU2** [comment]
目前所知的信息完全无法判断是什么原因。。

**Comment by XIU2** [comment]
下载远程协助软件（这个是只有被控功能的单文件版，用完即删），告诉我你的设备代码、临时密码。  
https://dl.todesk.com/windows/ToDesk_Lite.exe

我远程协助看看吧，但不保证一定能解决，毕竟我从来没遇到过，也没有任何人反馈过类似情况。

**Comment by XIU2** [comment]
不吭声的话，我就不等了，撤了。

**Comment by CussiusKon** [comment]
> 不吭声的话，我就不等了，撤了。

抱歉，刚看到，不过先这样吧，反正多试几次基本都会成功的，再说吧。多谢

**Comment by CussiusKon** [comment]
很久没遇到这个问题了，关闭了
