### ISSUE TITLE
无代理测试结果显示平均延迟均为0.xx

### ISSUE THREAD

**Issue by eschcn** [XIU2/CloudflareSpeedTest#239]
[admin@XXStation CloudlaareST]# ./CloudflareST
# XIU2/CloudflareSpeedTest v2.0.3 

开始延迟测速（模式：TCP IPv4，端口：443，平均延迟上限：9999 ms，平均延迟下限：0 ms)
4931 / 4931 [----------------------------------------------------------------------------------------------------------------------------] 100.00%
开始下载测速（下载速度下限：0.00 MB/s，下载测速数量：10，下载测速队列：10）：
10 / 10 [--------------------------------------------------------------------------------------------------------------------------------] 100.00%
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
104.25.34.142     4       4       0.00    0.32      48.57          
104.27.97.140     4       4       0.00    0.36      47.87          
104.25.35.104     4       4       0.00    0.34      46.96          
104.20.105.129    4       4       0.00    0.27      44.96          
104.27.118.135    4       4       0.00    0.34      44.03          
104.27.108.52     4       4       0.00    0.29      42.83          
104.25.36.70      4       4       0.00    0.35      42.72          
104.20.103.22     4       4       0.00    0.32      42.06          
104.27.96.1       4       4       0.00    0.27      38.87          
104.27.109.207    4       4       0.00    0.25      37.98          

完整测速结果已写入 result.csv 文件，可使用记事本/表格软件查看。
[admin@MiniStation CloudlaareST]# ip=$(curl -s http://myip.ipip.net)
[admin@MiniStation CloudlaareST]# echo "My public IP address is: $ip"
My public IP address is: 当前 IP：124.XXX.XXX.XXX  来自于：中国 XXXX 电信

**Comment by XIU2** [comment]
自行排查吧，这种情况，绝对是走代理了。

如果是 TCP 劫持的话，就不会有下载速度结果了。
