### ISSUE TITLE
IP段多了两个202的IP

### ISSUE THREAD

**Issue by myfalcom** [XIU2/CloudflareSpeedTest#24]
我看ip地址段后面跟了两个202地址，速度还很快，这是哪边的？也是cloudflare的？

**Comment by XIU2** [comment]
不是 Cloudflare 自己的 IP，是香港某公司与 Cloudflare 合作的 CDN 节点。  

所以算是非公开的 Cloudflare IP。

是 #15 这个人找到的。

**Comment by myfalcom** [comment]
真人才啊！希望能发现更多的IP。
