### ISSUE TITLE
mac os 下编码不正确，无法打开

### ISSUE THREAD

**Issue by benzo970210** [XIU2/CloudflareSpeedTest#243]
楼主，本人使用arm 架构芯片 ，m1，下载mac 版本显示编码不正确，无法打开

**Comment by XIU2** [comment]
这个版本不行吗？
CloudflareST_darwin_arm64.zip
我没有 MAC 设备，不是很清楚。

**Comment by benzo970210** [comment]
未能打开文稿“CloudflareST”。文本编码Unicode (UTF-8)不适用。
该文件可能已使用了不同的文本编码来存储，或者可能不是文本文件。
 报错 是这样的。
