### ISSUE TITLE
指定测ipv6，结果还是在测ipv4，发生了什么？

### ISSUE THREAD

**Issue by aa51513** [XIU2/CloudflareSpeedTest#245]
./CloudflareST -ipv6 -n 1000 -url "https://cf.xiu2.xyz/url" -o "result_ipv6.txt"
# XIU2/CloudflareSpeedTest v2.0.3 

开始延迟测速（模式：TCP IPv6，端口：443，平均延迟上限：9999 ms，平均延迟下限：0 ms)
26 / 26 [-------------------------------------------------------------------------------------------------------] 100.00%
开始下载测速（下载速度下限：0.00 MB/s，下载测速数量：5，下载测速队列：5）：
5 / 5 [---------------------------------------------------------------------------------------------------------] 100.00%
IP 地址                                   已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
104.16.91.83                              4       4       0.00    37.31     60.74          
172.67.131.231                            4       4       0.00    186.30    18.88          
104.24.157.171                            4       4       0.00    189.61    1.37           
172.64.94.148                             4       3       0.25    190.52    0.13           
172.65.7.31                               4       4       0.00    193.03    0.00           

完整测速结果已写入 result_ipv6.txt 文件，可使用记事本/表格软件查看。

已经确定本机有IPv6，且连通性正常
测试方法如下：
命令：curl ipv6.icanhazip.com
结果：240e:828:41d:4f00:66c:29fc:fd15:1c3f

**Comment by XIU2** [comment]
因为你压根没有指定 IP 段文件为 ipv6.txt 啊。。。
软件默认的是 ip.txt 文件，即 IPv4 段数据。

你肯定没看我写的教程：
https://github.com/XIU2/CloudflareSpeedTest#-ipv4ipv6

**Comment by aa51513** [comment]
> 因为你压根没有指定 IP 数据文件为 ipv6.txt 啊。。。 软件默认的是 `-f ip.txt` 文件，即 IPv4 段数据。
> 
> 你肯定没看我写的教程： https://github.com/XIU2/CloudflareSpeedTest#-ipv4ipv6

原来如此，感谢指点，我以为-f 参数的默认值，会自动根据-ipv6字段自适应变化

**Comment by XIU2** [comment]
刚刚更新版本支持了 IPv4 + IPv6 混合测速，因此取消了 ` -ipv6 ` 参数，你更新版本后，记得移除该参数，否则 CloudflareST 会提示参数不存在并终止运行。。
