### ISSUE TITLE
感觉已经废了。我换hysteria了

### ISSUE THREAD

**Issue by benzo970210** [XIU2/CloudflareSpeedTest#246]
感觉已经废了。我换hysteria了

_Originally posted by @pchaos in https://github.com/XIU2/CloudflareSpeedTest/issues/220#issuecomment-1152065418_
      想问问hysteria 好用不好用

**Comment by XIU2** [comment]
你不应该直接在那个 Issues 下回复问那个人吗？新开 Issues 干嘛？
这里不是论坛，是反馈交流 CloudflareST 软件的。
