### ISSUE TITLE
kernel: nf_conntrack: table full (16384), dropping packet

### ISSUE THREAD

**Issue by biozzl** [XIU2/CloudflareSpeedTest#247]
Below error message was shown when using ipv6 speed testing modle.
Tried to modfiy -n from 200 to 100, but not resolved.
```
Nov 10 19:15:28 kernel: nf_conntrack: table full (16384), dropping packet
Nov 10 19:15:33 kernel: net_ratelimit: 1126 callbacks suppressed
```

**Comment by XIU2** [comment]
请提供完整报错信息，仅这些我完全不明白。

**Comment by XIU2** [comment]
我随便搜了搜这个报错，仅限于 Linux 系统，似乎是 Linux 内核配置参数的问题。

https://security.stackexchange.com/questions/43205/nf-conntrack-table-full-dropping-packet
https://unix.stackexchange.com/questions/184066/kernel-nf-conntrack-table-full-dropping-packet-underlying-reason
https://serverfault.com/questions/632385/how-to-mitigate-error-kernel-nf-conntrack-table-full-dropping-packet

这不属于 CloudflareST 自身问题，对于这类问题我无法提供帮助。

**Comment by cherinyy** [comment]
这可能是一个普遍问题，我在 ImmortalWrt (OpenWrt 分支) 下运行 CloudflareSpeedTest，测试 IPv6 或 IPv4 `-allip` 时就会遭遇这个问题。

CloudflareSpeedTest 直接占满了连接数，并且没有释放，而是等着连接超时自动断开。

表现在日志上就是 `nf_conntrack: table full, dropping packet`。

**Comment by charSLee013** [comment]
> 这可能是一个普遍问题，我在 ImmortalWrt (OpenWrt 分支) 下运行 CloudflareSpeedTest，测试 IPv6 或 IPv4 `-allip` 时就会遭遇这个问题。 
> 表现在日志上就是 `nf_conntrack: table full, dropping packet`。

这句话对也不对，虽然可以通过`net.ipv4.netfilter.ip_conntrack_max`调整大小避免出现 `nf_conntrack: table full, dropping packet` 

但是因为`nf_conntrack` 大小也需要占用内核空间，并且像路由器这种小型设备上可用内存普遍才128M，当使用 `-allip` 的时候就完全不够用了

> CloudflareSpeedTest 直接占满了连接数，并且没有释放（我不知道在设计上有没有主动释放的功能），而是等着连接超时自动断开。

即使`CloudflareSpeedTest` 主动释放掉连接(`free socket`操作)，**内核** 也会继续`track connection` 直到 `timeout` 为止，同时调小 `net.ipv4.netfilter.ip_conntrack_tcp_timeout_established` 和 `net.netfilter.nf_conntrack_generic_timeout` 可以缓解此类问题

**Comment by cherinyy** [comment]
我测试了一下，这跟在哪个设备上运行 CloudflareSpeedTest 没有关系，因为网络出口是路由器，所以压力总会给到路由器上。

https://github.com/XIU2/CloudflareSpeedTest/assets/9050713/bab836f7-3268-4fe6-b5f6-c89ad92d06f2

这是我在 PC 上运行 CloudflareSpeedTest 的效果，因为 GitHub 限制上传文件 10 MiB 的缘故所以我没有录完，但是很明显到后面阶段，连接数是会超出的。

感谢 @charSLee013 的解答，不过我认为从这个 IP 数量以及连接数的增速来看，单单调整路由器的相关参数是远远不够的，更何况普通用户不会甚至不能调整路由器的参数。

所以我认为 CloudflareSpeedTest 方面还是得进行相关的优化。

现在的主要问题在于，如果发生了 `nf_conntrack: table full, dropping packet` 的情况，是否会影响 CloudflareSpeedTest 后续的测试？
以及是否会对其他正在运行的网络服务造成影响？（比如因为 `dropping packet` 导致微信通话等等断开连接或断断续续）

我注意到现在有个 `-n` 参数来限制同时测速的线程数量，似乎调整到一个合适的区间就能够避免爆连接数。

**Comment by XIU2** [comment]
其实一开始 `-n` 参数默认的线程数是 500，不过偶尔就会有人反应测速后网络卡顿等问题（但大部分人包括我是没问题的），于是我给调低成默认 200 了，在此之后反馈类似问题的人明显少了许多，个别几个我也会让其继续调低 `-n`（大都是在路由器、手机上跑的）。

这个 `-n` 值调多少合适和**当前设备、路由器、运营商限制**都有关系，不过只有值较高时才可能触发运营商限制（各地运营商限制连接数都不一样，有的限制很低，有的完全不限制）。
如果是在电脑上测速，那么电脑性能都是足够了，因此绝大部分情况下问题都出在 路由器 上。

> 根据我个人的使用情况以及部分以往的反馈者讨论的内容来看，感觉路由器性能和 `-n` 关系还是很大的。
> 我之前旧路由器不支持 IPv6 本来打算买个新的（否则我测试 Cloudflare 的 IPv6 功能只能在服务器上搞，很不方便），结果本地运营商做活动免费升级千兆+送了个支持 IPv6 的 WIFI6 路由器，于是我就给换上了，结果发现性能和 WIFI 还不如我的旧 WIFI5 路由器。。。
> 但考虑到 IPv6 还是很值的就暂时先用着了，后续我在使用 CloudflareST 时发现出现了网络卡顿情况（测速 IP 比较多的时候才会出现），将我原先一直用的默认 `-n 500` 调低后才解决了。。。这也让我更加确定免费送的路由器有多拉了。。。

但具体用多少合适就只能自己测了，200 不合适就减半到 100，没问题了就在增加一半到 150，就这样加一半减一半的测。

****

另外，我并不是专业程序员，因为这个软件（包括其他我开源的项目）是我日常生活中产生了需求后临时自学了各种编程语言写出来的，所以可能不如专业的考虑全面，像你们上面讨论的问题，我就一知半解。。。而且我路由器太拉也没办法在路由器上看具体的连接数情况，也无法调整内核参数测试。。

**Comment by cherinyy** [comment]
我能够明白你的意思，但是现在的情况是，可能默认 `-n 200` 还是偏高了。

我 512 MiB 内存的路由器都爆连接数了，而现在大部分普通的路由器，才 256 MiB 甚至 128 MiB。

512 MiB 高了不适合作为目标，而 128 MiB 又低了，所以我个人觉得对标 256  MiB 路由器的连接数情况会比较合适。

我抽个空，拿 256 MiB OpenWrt 路由器测试一下，看看多少线程比较合适。

当然正如你所说，这可能还受到运营商的限制，不过正因为存在运营商的限制，才更应该调低默认值，以保证测速的有效性和网络的可用性。

**Comment by XIU2** [comment]
@cherinyy 
你这路由器就有点离谱了，我这运营商送的免费路由器，估计连 128M 有没有都不确定，但我跑 `-n 300` 是完全没问题的。

从默认的 `-n 500` 改为默认 `-n 200` 后，反馈类似网络问题的人已经明显降低了（这还是使用人数提高后的情况下），这已经是一个合适的默认值了，不可能为了兼顾一些个别情况而把默认值调的过低，就比如以前有个人反馈时，交流测试时发现要低至 `-n 50` 甚至更低才会没有网络问题，但这个速度也太慢了，绝大部分人都不会遇到这种情况。

另外，除了 `-n` 值这个变量以外，测速的 IP 数量越多，也就越容易遇到这种问题。

总之，除非现在大量人反馈这种网络问题，否则我是不可能再调低了。

****

另外，运营商的连接数限制是不可能这么低的，否则日常上网都可能会受到影响。
