### ISSUE TITLE
测速的下载速度远超网络带宽速度，请教一下是否正常？

### ISSUE THREAD

**Issue by hoockoo** [XIU2/CloudflareSpeedTest#251]
IP 地址	已发送	已接收	丢包率	平均延迟	下载速度 (MB/s)
172.66.44.85	4	4	0	160.41	174.45
172.67.6.81	4	4	0	167.55	95.55
172.67.86.142	4	4	0	163.79	76.61
172.67.88.209	4	4	0	164.93	58.23
172.67.172.187	4	4	0	165.62	46.98
172.67.117.170	4	4	0	161.85	46.04
172.67.80.43	4	4	0	167.11	41.76
172.67.113.60	4	4	0	177.99	39.74

我是300M的宽带，正常来说下载速度应该不超过50MB，但测速结果的前几名经常都是超出实际带宽，甚至乎超出网口物理极限，请问是什么问题呢？我使用的是linux arm64的版本。

**Comment by XIU2** [comment]
新建一个 1.txt 文件，把这几个 IP 一行一个都复制到文件里。

然后命令行 ` CloudflareST -f 1.txt ` 测速看看。

**Comment by hoockoo** [comment]
> 新建一个 1.txt 文件，把这几个 IP 一行一个都复制到文件里。
> 
> 然后命令行 `./CloudflareST -f 1.txt` 对这几个 IP 单独测速看看。
> 
> 另外，你用的参数是什么？指定的下载测速地址是什么？还是说都是默认的（即没指定任何参数）？

大佬~上面的结果就是我用1.txt单独测速的结果，测速地址是按你教程搭的，使用的命令是：

./CloudflareST -o bestip.csv -f 1.txt -url xxxxxxx

感觉是最近电信免费升级了300M宽带(实际是350M)才有这种问题，以前100M(实际是150M)的时候使用相同的硬件测速，也就最多20MB出头，没出现过这种情况。现在是基本5次会有4次出现上面的情况。

**Comment by XIU2** [comment]
Windows 上是否正常？

**Comment by hoockoo** [comment]
> > 新建一个 1.txt 文件，把这几个 IP 一行一个都复制到文件里。
> > 然后命令行 `./CloudflareST -f 1.txt` 对这几个 IP 单独测速看看。
> > 另外，你用的参数是什么？指定的下载测速地址是什么？还是说都是默认的（即没指定任何参数）？
> 
> 大佬~上面的结果就是我用1.txt单独测速的结果，测速地址是按你教程搭的，使用的命令是：
> 
> ./CloudflareST -o bestip.csv -f 1.txt -url xxxxxxx
> 
> 感觉是最近电信免费升级了300M宽带(实际是350M)才有这种问题，以前100M(实际是150M)的时候使用相同的硬件测速，也就最多20MB出头，没出现过这种情况。现在是基本5次会有4次出现上面的情况。

root@OpenWrt:/mnt/sda4/CloudflareST# cat result.csv 
IP 地址,已发送,已接收,丢包率,平均延迟,下载速度 (MB/s)
172.67.172.187,4,4,0.00,159.96,156.14
172.67.6.81,4,4,0.00,160.39,121.12
172.67.117.170,4,4,0.00,160.47,61.37
172.66.44.85,4,4,0.00,159.94,59.80
172.67.175.27,4,4,0.00,160.42,54.23
172.67.249.232,4,4,0.00,160.06,52.98
172.64.162.157,4,4,0.00,159.56,38.08
172.65.179.251,4,4,0.00,160.34,0.00
172.65.254.220,4,4,0.00,159.86,0.00
172.65.245.120,4,4,0.00,160.44,0.00

使用默认参数./CloudflareST -url xxxxxx也会有这个问题。

**Comment by hoockoo** [comment]
> Windows 上是否正常？

这个我倒没试过，我晚上测一下再回复你结果，谢谢~

**Comment by XIU2** [comment]
你用这个命令测试下：
``` bash
curl -o /dev/null --resolve "测速地址的域名:443:IP" https://下载测速地址

# 示例：
curl -o /dev/null  --resolve "speed.cloudflare.com:443:172.67.172.187" https://speed.cloudflare.com/__down?bytes=200000000
```
即使用 curl 实现和 CloudflareST 下载测速一样的效果，强制域名走指定的 IP，看看下载速度是多少。

****

我以前遇到过有人反馈类似的问题，但对方是 路由器 下载测速结果很慢，而电脑上下载测速很快，而通过 curl 模拟下载测速依然是很慢（即和 CloudflareST 一样），所以根据排除法，基本确定是 路由器 的问题，但具体是什么原因我也不清楚。

**Comment by charSLee013** [comment]
路由器上慢可能是路由器性能太羸弱了，路由器既要运行程序又要处理收到的包
而在PC上测速，路由器只负责转发即可，而且还有专门的硬件来加速转发

**Comment by XIU2** [comment]
@charSLee013 可能是，类似的还有人手机上通过虚拟机运行 CloudflareST 下载测速明显慢于电脑上的，可能是性能问题，也可能是 WIFI 的问题（相比电脑网线）。

**Comment by hoockoo** [comment]
> 你用这个命令测试下：
> 
> ```shell
> curl -o /dev/null --resolve "测速地址的域名:443:IP" https://下载测速地址
> 
> # 示例：
> curl -o /dev/null  --resolve "speed.cloudflare.com:443:172.67.172.187" https://speed.cloudflare.com/__down?bytes=200000000
> ```
> 
> 即使用 curl 实现和 CloudflareST 下载测速一样的效果，强制域名走指定的 IP，看看下载速度是多少。
> 
> 我以前遇到过有人反馈类似的问题，不过对方是 路由器 上下载测速结果很慢，但 电脑 上下载测速很快。 路由器上通过 curl 模拟下载测速依然是很慢（和 CloudflareST 一致），电脑上改 Hosts 通过浏览器单线程下载测速也和 CloudflareST 速度一致，所以根据排除法，基本确定是 路由器 的问题，但具体是什么原因我也不清楚。

我刚刚连续试了4次，curl命令正常，晚上再试试windows。
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  200M  100  200M    0     0  22.2M      0  0:00:09  0:00:09 --:--:-- 35.0M

**Comment by hoockoo** [comment]
> 路由器上慢可能是路由器性能太羸弱了，路由器既要运行程序又要处理收到的包 而在PC上测速，路由器只负责转发即可，而且还有专门的硬件来加速转发

我这个测速数值过大就很诡异了，测速时我看了一下CPU占用最高20%左右，峰值流量42MB。

**Comment by XIU2** [comment]
也就是说，同一个 IP，同一个下载测速地址，多次单独测试，CloudflareST 下载测速得到的结果均远高于 Curl 的？

而且你提到是最近突然出现的？我看了下，上次大量修改 下载测速 相关代码是 v2.0.0 版本（当时整个软件重写了一遍），后续对其相关改动也只是细枝末节、注释之类的，都没有影响到其功能核心代码。

**Comment by hoockoo** [comment]
> 也就是说，同一个 IP，同一个下载测速地址，多次单独测试，CloudflareST 下载测速得到的结果均远高于 Curl 的？
> 
> 而且你提到是最近突然出现的？我看了下，上次大量修改 下载测速 相关代码是去年 11 月的 v2.0.0 版本（当时整个软件重写了一遍），后续对其相关改动也只是细枝末节、注释之类的，都没有影响到其功能核心代码。
> 
> 另外，你的下载测速文件是多大的？ 尝试修改下载测速时间试试，例如把默认的 10 秒改成 ` -dt 5` 及 ` -dt 20` 对比一下有没有差异。

我刚刚想了一下，有可能是我用python调用os.system()来运行CloudflareST的问题，因为python单进程的话只能把CPU的一个核心吃满，以前没问题可能是因为我带宽比较小，运行CloudflareST时连一个核心都吃不满，现在带宽变大，一个核心就不够用了，导致测速结果异常。

**Comment by XIU2** [comment]
不清楚，等晚上你在电脑上测速结果出来后再研究吧。

如果电脑上测速结果正常，那么问题可能出在你的 Linux 设备上。
如果电脑上测速结果异常，那么就需要进一步排查了（虽然我也没什么头绪。。。

**Comment by hoockoo** [comment]
> 不清楚，等晚上你在电脑上测速结果出来后再研究吧。
> 
> 如果电脑上测速结果正常，那么问题可能出在你的 Linux 设备上。 如果电脑上测速结果异常，那么就需要进一步排查了（虽然我也没什么头绪。。。

windows下好像是没有问题的，看来我要自己再排查一下问题了，谢谢帮忙！
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
172.67.115.119    4       4       0.00    166.05    48.14
172.67.6.119      4       4       0.00    165.87    37.12
172.67.179.195    4       4       0.00    165.97    28.71
172.67.155.191    4       4       0.00    166.48    25.34
172.64.83.59      4       4       0.00    166.71    21.07
172.64.150.41     4       4       0.00    163.68    18.81
172.67.135.177    4       4       0.00    165.75    16.24
172.67.243.215    4       4       0.00    166.93    15.99
172.67.224.185    4       4       0.00    163.93    14.62
172.67.143.68     4       4       0.00    166.04    7.70

**Comment by XIU2** [comment]
不同版本都是同样的代码编译出来的，理论上不通架构/系统应该表现情况一致的。

你这种情况，要么就是和你的 Linux 设备有关，要么就是我的 CloudflareST 在 ARM 上有问题？
但这就触及到我的知识盲区了，我也想不通 ARM 是什么地方会影响到测速结果。

目前 CloudflareST 下载测速是类似于 `curl -o /dev/null` 边下载边丢弃，计算下载量，然后除以时间得出平均速度。
我观察过下载测速时，内存占用、硬盘占用都正常，没有任何数据写入到内存、硬盘中，因此和内存、硬盘大小无关。
CPU 也反应很小，多线程延迟测速时，还有个 1% 波动，等到单线程下载测速时，则一直显示 0（忽略不计了）。。。

**Comment by XIU2** [comment]
看来是变成 玄学 问题了。。。

**Comment by wangchunin** [comment]
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
104.19.193.236    4       4       0.00    1181.50   722.99
104.18.255.36     4       4       0.00    1180.75   58.66
104.18.254.53     4       4       0.00    1192.50   45.90
104.19.169.52     4       4       0.00    1178.00   45.10
104.19.165.28     4       4       0.00    1177.50   42.61
104.19.196.56     4       4       0.00    1171.50   42.03
104.18.192.210    4       4       0.00    1190.50   36.29
104.19.241.20     4       4       0.00    1163.00   35.80
104.19.230.97     4       4       0.00    1178.25   33.38
104.19.231.230    4       4       0.00    1180.00   28.10

**Comment by wangchunin** [comment]
同样的问题，我宽带到底了也就700Mb，平时最多80MB/s

**Comment by XIU2** [comment]
已更新 v2.2.1 版本，修复 一些情况下下载测速数值过大的问题，有兴趣的话你可以试试。
https://github.com/XIU2/CloudflareSpeedTest/releases/tag/v2.2.1

**Comment by hoockoo** [comment]
> 已更新 v2.2.1 版本，修复 一些情况下下载测速数值过大的问题，有兴趣的话你可以试试。 https://github.com/XIU2/CloudflareSpeedTest/releases/tag/v2.2.1

大佬，我更新2.2.1后手动测速了5次，貌似不会出现超速的情况了，当然了我发生超速的情况一般都是在早上6点我路由自动运行测速脚本的时候，明早我再观察一下脚本运行的情况后给你反馈情况。看了一下你和[charSLee013](https://github.com/charSLee013)的讨论，终于搞明白我宽带在100M时没出现超速的情况而升级300M后才超速，我测速文件大小为200M，感谢~

**Comment by XIU2** [comment]
嗯，该 BUG 需要满足一定前提条件，而且即使这样也不是每次都会出现，越极端的情况下越容易复现（例如我在海外大宽带服务器上测速），另外根据大家的反馈情况来看，似乎 Linux 系统下该 BUG 更容易复现。

**Comment by hoockoo** [comment]
![0212_1.jpg](https://user-images.githubusercontent.com/34845470/218294870-5d451f8a-9db2-4e6c-b406-bf46fa0782a7.jpg)

今天早上6点的测速，没有超速问题。
