### ISSUE TITLE
使用 -allip 参数时，在所有IP测试结束前，能不能给一个“当前最优”的IP，作为ddns的记录？

### ISSUE THREAD

**Issue by aa51513** [XIU2/CloudflareSpeedTest#252]
比如：我配置了1.1.1.0/24这个IP段，同时使用了-allip 参数

测试1.1.1.1的结果是 1Mbps 和32ms
先把这个更新到ddns

如果后续有更优秀的参数，就覆盖ddns，否则继续测试下一个IP
直到发现一个比当前更好的IP，或者本轮次结束

如果可以的话，还可以做一下循环不间断ping测延迟
每轮次去除掉上一轮中ping不通的IP地址，在下一轮测速自动跳过
为了更广泛的普适性，还可以设定多少轮次(比如10轮)之后，再次扫描所有IP(包含之前跳过的IP列表)，以防错过“复活”的优秀IP

**Comment by XIU2** [comment]
凡是能依靠第三方脚本、工具实现的功能，我都不会加到软件内的。
