### ISSUE TITLE
路由器接了两台宽带，使用了mwan3负载均衡，在运行的时候可以指定网络接口吗？参考curl

### ISSUE THREAD

**Issue by stonegr** [XIU2/CloudflareSpeedTest#255]
感谢开发者的开发及付出，路由器接了两台宽带，使用了mwan3负载均衡，在运行的时候可以指定网络接口吗？参考curl的--interface

![截图_20221118212123](https://user-images.githubusercontent.com/74632994/202714703-86976cd9-6bd1-4ae1-8060-295360626ed3.png)

**Comment by XIU2** [comment]
不能，没有该功能。

不出意外的话，也不会增加，因为该功能过于小众。

**Comment by stonegr** [comment]
> 不能，没有该功能。
> 
> 不出意外的话，也不会增加，因为该功能过于小众。

目前有什么能达到这种效果的方法吗？主要是两条宽带想分别优选同步更新到一个域名上去

**Comment by XIU2** [comment]
不是很清楚呀，因为我压根没有这方面需求与经历。。。
我都没用过两条宽带的网络。
