### ISSUE TITLE
大佬，我想学习下是如何实现下载测速的呢

### ISSUE THREAD

**Issue by lei-9** [XIU2/CloudflareSpeedTest#258]
我想的顺序：
第一步 根据cf 提供的可用网段 ipv4 / ipv6 来获取可用的网络ip（已实现）
第二步 随机ping 网络ip 是否可用（已实现）
第三步 测试ping 通的网络ip 下载速度（这一步需要怎么实现呢？求大佬赐教）
还是用 GET：{网络ip}/__down?bytes=100000  |  POST：{网络ip}/__up 测试上传下载吗？请求头一定要设置全吗？
原谅我看不懂go语言。。。求知若渴的小萌新诚恳求教～

**Comment by XIU2** [comment]
。。。不理解你到底要问什么

**Comment by lei-9** [comment]
> 

额，我的问题就是如何实现下载测速的，我按照你的方法来试试。感谢大佬解惑～
