### ISSUE TITLE
大佬，可不可以增加只测速指定地区的节点？

### ISSUE THREAD

**Issue by ywyha** [XIU2/CloudflareSpeedTest#26]
首先感谢大佬提供这么好用的工具，大佬可不可以增加指定地区筛选

**Comment by XIU2** [comment]
因为 Cloudflare CDN 用的是 **Anycast** 技术，这代表任何 CDN 节点 IP 的**实际位置都是不断变化**的。  
想要知道该 CDN IP 当时是哪个地区的，需要通过访问 `https://CDN-IP/cdn-cgi/trace` 来查看。  

> 例如：https://1.0.0.1/cdn-cgi/trace 中的 `colo=LAX`，LAX 就是洛杉矶。  

也就是先要去扫描区分出来地区才行，而这个地区是会经常变动（调整）的。

Cloudflare CDN 的亚洲节点很少，而且除了移动是直连外，电信、论坛都是绕道，所以速度还不如美国节点呢。

**Comment by ywyha** [comment]
> 因为 Cloudflare CDN 用的是 **Anycast** 技术，这代表任何 CDN 节点 IP 的**实际位置都是不断变化**的。
> 想要知道该 CDN IP 当前是哪个地区，可以通过访问 `https://CDN-IP/cdn-cgi/trace` 来查看。
> 
> > 例如：https://1.0.0.1/cdn-cgi/trace 中的 `colo=LAX`，LAX 就是洛杉矶。
> 
> 也就是先要去扫描并区分出来地区才行，而这个地区不是固定的，会经常变动（调整）。
> 
> Cloudflare CDN 的亚洲节点很少，而且除了移动是直连外，电信、联通大都是绕道美国，所以速度还不如直连美国节点呢。
> 
> 所以与其去寻找指定地区 CDN 节点，还不如直接看实际测速结果（下载速度）来选择的好。
> 
> 而且最主要的是，软件是先**延迟测速并按从低到高排序**后，再去**从最低延迟的 IP 开始下载测速**的，所以默认情况下的测速结果已经是**既下载速度最快，又平均延迟最低**的最快 IP 了。

大佬，你好，我并不是要找亚洲节点，我想找其他地区的节点……默认测出来的虽然速度比较快，但是与我的VPS距离比较远，有时候会与VPS之间连接质量一般，延迟低的好像都是欧洲的……虽然与CF节点直连连接良好，但是有时候节点与VPS之间连接一般……所以希望大佬能优化下脚本按地区筛选，以及标注上节点的位置……再次谢谢大佬提供这么好用的工具

**Comment by XIU2** [comment]
我再上一个 Issues 里提到了：https://github.com/XIU2/CloudflareSpeedTest/issues/25#issuecomment-749585723  

并不说你通过哪个 IP 访问 Cloudflare CDN，就是这个 IP 去回源访问你的网站服务器。

Cloudflare CDN 公开的所有 IP 段中，分为两类。
- 一类是**回源 IP**，即是 Cloudflare CDN 专门去你服务器回源获取数据的 IP。
- 一类是**任播 IP**，即是用户访问的 CDN IP。

**Comment by CrazyBoyFeng** [comment]
> > 因为 Cloudflare CDN 用的是 **Anycast** 技术，这代表任何 CDN 节点 IP 的**实际位置都是不断变化**的。
> > 想要知道该 CDN IP 当前是哪个地区，可以通过访问 `https://CDN-IP/cdn-cgi/trace` 来查看。
> > > 例如：https://1.0.0.1/cdn-cgi/trace 中的 `colo=LAX`，LAX 就是洛杉矶。
> > 
> > 
> > 也就是先要去扫描并区分出来地区才行，而这个地区不是固定的，会经常变动（调整）。
> > Cloudflare CDN 的亚洲节点很少，而且除了移动是直连外，电信、联通大都是绕道美国，所以速度还不如直连美国节点呢。
> > 所以与其去寻找指定地区 CDN 节点，还不如直接看实际测速结果（下载速度）来选择的好。
> > 而且最主要的是，软件是先**延迟测速并按从低到高排序**后，再去**从最低延迟的 IP 开始下载测速**的，所以默认情况下的测速结果已经是**既下载速度最快，又平均延迟最低**的最快 IP 了。
> 
> 大佬，你好，我并不是要找亚洲节点，我想找其他地区的节点……默认测出来的虽然速度比较快，但是与我的VPS距离比较远，有时候会与VPS之间连接质量一般，延迟低的好像都是欧洲的……虽然与CF节点直连连接良好，但是有时候节点与VPS之间连接一般……所以希望大佬能优化下脚本按地区筛选，以及标注上节点的位置……再次谢谢大佬提供这么好用的工具

访问cf的流程是，用户访问cf入口节点，入口节点将流量转发回源节点，回源节点访问你的源服务器。
你只需要关注入口节点快不快稳不稳就行了，回源节点是cf自动调整的，你干预不了。

**Comment by XIU2** [comment]
emmm 如果没什么问题就关闭该 Issues 吧。

**Comment by ywyha** [comment]
> emmm 如果没什么问题就关闭该 Issues 吧。

了解了，谢谢大佬提供这么好用的工具，赞

**Comment by XIU2** [comment]
已更新 v2.2.0 版本，新增了你要的功能（虽然只是一部分，即只有匹配指定地区的功能，输出结果里则没有注明地区）。
https://github.com/XIU2/CloudflareSpeedTest/releases/tag/v2.2.0
