### ISSUE TITLE
V2.10版本新增IPV4和IPV6混合测速，请问我该如何指定只测IPV6呢？

### ISSUE THREAD

**Issue by cheyuze** [XIU2/CloudflareSpeedTest#261]
RT，试了几次运行出的结果都是IPV4的IP，希望可以指定为IPV6，不考虑IPV4

**Comment by cheyuze** [comment]
暂时先替换回原本的2.0.3了，期待大佬们解答，在此谢过Thanks♪(･ω･)ﾉ

**Comment by XIU2** [comment]
你的 IP 数据文件内只写 IPv6 地址不就行了？

**Comment by XIU2** [comment]
以前是，IP 数据文件内，要么只能有 IPv4 地址，要么只能有 IPv6 地址，而且使用 IPv6 的 IP 数据文件时，还需要 -ipv6 来让软件知道你要开始测速 IPv6 地址了。

而现在是，IP 数据文件内，可以同时存在 IPv4 和 IPv6 地址，软件会自动区分并正常测速。

IP 数据文件内，只有 IPv4 地址的话，软件自然就只测速 IPv4 地址呀。
IP 数据文件内，只有 IPv6 地址的话，软件自然就只测速 IPv6 地址呀。

目前软件提供的 IP 数据文件有两个：
 - `ip.txt` - 这个是 IPv4 的数据文件
 - `ipv6.txt` - 这个是 IPv6 的数据文件

软件默认使用的 IP 数据文件是 ip.txt，你给改成 ipv6.txt 不就行了？
```
CloudflareST -f ipv6.txt
```
