### ISSUE TITLE
测速仍为0.00

### ISSUE THREAD

**Issue by qeqeq1** [XIU2/CloudflareSpeedTest#27]
向上个issues中学习，加上了参数  -url "https://gh.con.sh/https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/download/v2.21.12/Waifu2x-Extension-GUI-v2.21.12-Portable.7z"

> C:\Users\Downloads\CloudflareST_windows_amd64>CloudflareST.exe -p 20 -f ipv6.txt -dd -ipv6 -n  888 
> # XIU2/CloudflareSpeedTest v1.4.6
> 
> 开始延迟测速（模式：TCP IPv6，端口：443）：
> 77548 / 77548 [-----------------------------------------------------------------------------------------------] 100.00%
> IP 地址                                   已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
> 2606:4700:3030:96:fa5b:236d:4eed:312c     4       4       0.00    270.41    0.00
> 2606:4700:3030:cc27:13bb:6960:73d2:91f5   4       4       0.00    270.91    0.00
> 2606:4700:3034:9abd:14bd:ef32:1788:f773   4       4       0.00    270.91    0.00
> 2606:4700:3034:9abd:14bd:5be8:69d3:1c9a   4       4       0.00    271.15    0.00

仍得到0.00结果 且过程中任务管理器始终显示网络利用率极低

**Comment by XIU2** [comment]
我看到你使用了 `-dd` 参数，这个参数是禁用下载测速。
所以预期结果就是不进行下载测速，下载测速结果自然都是 0.00 了。

**Comment by qeqeq1** [comment]
十分感谢=-=没有注意使用了这个参数 现已正常得出结果，十分感谢

**Comment by XIU2** [comment]
... 没什么问题就关闭该 Issues 吧。
走之前，如果觉得软件还不错，就去点个 ⭐ 吧！
