### ISSUE TITLE
程序闪退

### ISSUE THREAD

**Issue by 8ty** [XIU2/CloudflareSpeedTest#270]
双击就一闪而过

**Comment by 8ty** [comment]
是给ip.txt里加上几个ip段就这样子了

**Comment by cxw620** [comment]
> 是给ip.txt里加上几个ip段就这样子了

发出来看看

**Comment by XIU2** [comment]
CloudflareST 是**命令行程序**，闪退意味着报错了，根据你的描述，基本可以确定是你添加的几个 IP 段格式有误，导致软件在解析 IP 段时报错并自动退出。

如果你是在 cmd 里用命令去运行 CloudflareST，那么软件退出前输出的信息依然会保留，你就能看到报错内容了。
参考： https://github.com/XIU2/CloudflareSpeedTest#-cmd-带参数运行-cloudflarest

**Comment by 8ty** [comment]
> CloudflareST 是**命令行程序**，闪退意味着报错了。根据你的描述，基本可以确定是**你添加的几个 IP 段格式有误**，导致软件在解析 IP 段时报错并自动退出。
> 
> 你把 `ip.txt` 文件内的内容贴出来，看一眼就知道了。
> 
> 如果你是在 CMD 里用命令去运行 CloudflareST，那么软件退出前输出的信息依然会保留在 CMD，你就能看到报错内容了。 参考： [https://github.com/XIU2/CloudflareSpeedTest#-cmd-带参数运行-cloudflarest](https://github.com/XIU2/CloudflareSpeedTest#-cmd-%E5%B8%A6%E5%8F%82%E6%95%B0%E8%BF%90%E8%A1%8C-cloudflarest)

173.245.48.0/20
103.21.244.0/22
103.22.200.0/22
103.31.4.0/22
141.101.64.0/18
108.162.192.0/18
190.93.240.0/20
188.114.96.0/20
197.234.240.0/22
198.41.128.0/17
162.158.0.0/15
104.16.0.0/13
104.24.0.0/14
104.29.64.0/24 
104.29.13.0/24
104.29.65.0/24 
104.29.66.0/24
104.29.3.0/24
104.29.45.0/24
172.64.0.0/17
172.64.128.0/18
172.64.192.0/19
172.64.224.0/22
172.64.229.0/24
172.64.230.0/23
172.64.232.0/21
172.64.240.0/21
172.64.248.0/21
172.65.0.0/16
172.66.0.0/16
172.67.0.0/16
131.0.72.0/22
23.227.38.0/24
23.227.39.0/24
66.235.200.0/24
里面的内容是这些

**Comment by 8ty** [comment]
> CloudflareST 是**命令行程序**，闪退意味着报错了。根据你的描述，基本可以确定是**你添加的几个 IP 段格式有误**，导致软件在解析 IP 段时报错并自动退出。
> 
> 你把 `ip.txt` 文件内的内容贴出来，看一眼就知道了。
> 
> 如果你是在 CMD 里用命令去运行 CloudflareST，那么软件退出前输出的信息依然会保留在 CMD，你就能看到报错内容了。 参考： [https://github.com/XIU2/CloudflareSpeedTest#-cmd-带参数运行-cloudflarest](https://github.com/XIU2/CloudflareSpeedTest#-cmd-%E5%B8%A6%E5%8F%82%E6%95%B0%E8%BF%90%E8%A1%8C-cloudflarest)

看了一下好像并没有什么不对

**Comment by XIU2** [comment]
我试了下这些 IP 段，可以正常解析并测速，没有格式问题。

你根据我前面发的 CMD 方式链接，用 CMD 去运行 CloudflareST 来看看报错内容是什么。

**Comment by XIU2** [comment]
等一下，不对呀，你发的这些 IP 段都是 ip.txt 里默认的内容，压根就没有你添加的其他内容啊。
这当然不可能报错呀。。。

**Comment by 8ty** [comment]
> 我试了下这些 IP 段，可以正常解析并测速，没有格式问题。
> 
> 你根据我前面发的 CMD 方式链接，用 CMD 命令行方式去运行 CloudflareST 来看看报错内容是什么。

神奇，我又从github这里重新复制了一遍，结果能跑了，但是原来的还是不行，我猜可能是当初从网页上复制下来的编码不对

**Comment by XIU2** [comment]
可能是你复制到的一些不可见的内容。
一些字符是看不见的，但实际上是存在的。

**Comment by 8ty** [comment]
> ~等一下，不对呀，你发的这些 IP 段都是 ip.txt 里默认的内容，压根就没有你添加的其他内容啊。~
> 
> 奥，看到了，你是夹在中间了。。。是在 HostLoc 里我发的哪些以前我扫的 IP 段呀。

大佬有扫到能用的jp的ip段吗

**Comment by 8ty** [comment]
> 可能是你复制到的一些不可见的内容。 一些字符是看不见的，但实际上是存在的。

可能是了

**Comment by 8ty** [comment]
还有不知道为什么，有些优选ipping得通但是不能用，奇怪了，也不是付费段里的

**Comment by XIU2** [comment]
以前扫到的有，但分享出来后，用的人多了，就被 Cloudflare 官方限制了（免费套餐的域名不能用了，指向会报错）。

后来又遇到了我这边联通对 Cloudflare 阻断的事，导致 Cloudflare IPv4 在我这边联通下是几乎不能用了，所以我也不再关注了，这些我以前扫到的 IPv4 段我握在手里也没啥用了，前段时间在 LOC 看到有人问就给发出去了。

**Comment by XIU2** [comment]
104.16.0.0/13 包含了 104.16.0.0~104.23.255.255
包括你添加的那几个我扫的 IP 段，其实都包含在 104.24.0.0/14 里，你加不加都一样，因为 CloudflareST 会遍历每一个 /24。
