### ISSUE TITLE
[功能请求]增加地区限制

### ISSUE THREAD

**Issue by tdjnodj** [XIU2/CloudflareSpeedTest#271]
想使用特定地区的cloudflare节点，希望能加一个参数以限制选择的地区。

实现这个功能的思路: 在 http://[cloudflare ip]/cdn-cgi/trace 中可以看到`colo=[地区名]`，在测延迟后、测速前读取一下这个colo，不符合指定的就不测，符合的就测。这样应该就能筛选指定地区的ip了。

同时，也希望能在测速后的结果中显示这个ip的地区。

**Comment by XIU2** [comment]
以前有人提过类似的需求 Pull requests 不过最后因为一些问题而搁置了。#254 

不过我对这类功能兴趣不大，因为目前 Cloudflare CDN 的 IPv4 各地区阻断严重，我这边去年就用不了了，只能用 IPv6 凑活着了，平时我用 CloudflareST 也很少用来测速 Cloudflare CDN 了，反而都在测速其他 CDN、网站 IP 什么的。。。

因此我也不想让 CloudflareST 和 Cloudflare CDN 过度绑定（虽然这名字...）。

**Comment by tdjnodj** [comment]
感谢大佬
