### ISSUE TITLE
测速出来数值太大，远超宽带大小

### ISSUE THREAD

**Issue by wangchunin** [XIU2/CloudflareSpeedTest#272]
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
104.19.193.236    4       4       0.00    1181.50   722.99
104.18.255.36     4       4       0.00    1180.75   58.66
104.18.254.53     4       4       0.00    1192.50   45.90
104.19.169.52     4       4       0.00    1178.00   45.10
104.19.165.28     4       4       0.00    1177.50   42.61
104.19.196.56     4       4       0.00    1171.50   42.03
104.18.192.210    4       4       0.00    1190.50   36.29
104.19.241.20     4       4       0.00    1163.00   35.80
104.19.230.97     4       4       0.00    1178.25   33.38
104.19.231.230    4       4       0.00    1180.00   28.10

我是联通700Mb的宽带，不应该出现这种情况才对
延迟我用curl测的所以比较大，跟这个应该没关系

**Comment by XIU2** [comment]
以前有人反馈过类似情况，但最终都没有找到原因，都是在不同设备下，测速同一个 IP 地址，速度不一样，有的正常，有的像你这样异常。
#251 我记得还有几个类似的反馈，但一时之间找不到。

**Comment by wangchunin** [comment]
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
104.16.54.38      4       4       0.00    1120.75   168.78
104.16.27.216     4       4       0.00    1097.75   72.63
104.19.221.17     4       4       0.00    1120.25   49.46
104.16.204.78     4       4       0.00    1124.50   47.28
104.17.21.241     4       4       0.00    1116.75   43.66
104.18.15.37      4       4       0.00    1111.25   34.84
104.16.148.224    4       4       0.00    1116.50   34.12
104.16.214.96     4       4       0.00    1098.25   26.68
104.16.77.173     4       4       0.00    1106.75   24.43
104.16.78.99      4       4       0.00    1093.25   20.94

**Comment by wangchunin** [comment]
出现频率挺高的，几乎每次都出现，现在我去试试单个ip

**Comment by wangchunin** [comment]
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
104.19.193.236    4       4       0.00    1559.75   56.27
104.16.54.38      4       4       0.00    1574.00   36.84

**Comment by wangchunin** [comment]
单独测试又是对的

**Comment by XIU2** [comment]
另外，你用的**下载测速地址**是什么，是默认的，还是其他的？

另外，你测速用的是什么设备？根据以往的反馈结果，似乎问题都出在路由器等设备上。

**Comment by wangchunin** [comment]
我自己网站 dd if=/dev/random 生成的200MB
N1 openwrt
我感觉这种速度应该是哪个环节上，处理到了缓存，导致速度特别快，应该在测试设备以内的环节

**Comment by XIU2** [comment]
可能是 OpenWrt 或者说相关架构方面的问题，但这就触及我的知识盲区了。

出现的几个类似问题反馈，似乎都是 OpenWrt 的路由器，但是用 OpenWrt 跑 CloudflareST 的肯定也不少人（从 Issues 里路由器相关讨论、衍生项目来看），但反馈该问题的只有你们两三个人。。。考虑到肯定还有一些遇到问题但懒得反馈的人，但按照比例应该也不会有多少。

因此也不清楚，到底是哪里不一样，导致你们几个会出现该问题，而其他大部分 OpenWrt 路由器的人却正常。

**Comment by XIU2** [comment]
对了，你有没有试过这个版本：
据说是原生 OpenWrt 编译的 #64 ，我不清楚这种，你试试是否存在该问题。
https://github.com/immortalwrt-collections/openwrt-cdnspeedtest

**Comment by wangchunin** [comment]
嗯好的，我去试试，谢谢你的关注

**Comment by XIU2** [comment]
已更新 v2.2.1 版本，修复 一些情况下下载测速数值过大的问题，有兴趣的话你可以试试。
https://github.com/XIU2/CloudflareSpeedTest/releases/tag/v2.2.1
