### ISSUE TITLE
请问此工具中的下载测速可以处理重定向吗？

### ISSUE THREAD

**Issue by Sunsetra** [XIU2/CloudflareSpeedTest#276]
主要是因为有些网址很难找到单纯的直链，所以只能使用带有重定向的链接。想请问一下能否使用带重定向的链接来进行测速？

**Comment by XIU2** [comment]
软件内的下载测速支持重定向，包括软件自带的 Cloudflare CDN 下载测速地址，其实就是个重定向，是大家自建分享给我的，然后我再给轮询为重定向，来负载均衡。

**Comment by Sunsetra** [comment]
好的，非常感谢
