### ISSUE TITLE
通过-sl参数限定下载速率但是在有效ip为0的时候仍然将速度为0的若干个ip写入result.txt

### ISSUE THREAD

**Issue by edisonzf2020** [XIU2/CloudflareSpeedTest#281]
命令如下，/opt/CloudflareST/CloudflareST  -t 5 -tll 30 -tl 80 -sl 0.2 -dn 5 -f /opt/CloudflareST/ip-cf-xg.txt -o "result_hosts.txt"
结果：
开始测速...
# XIU2/CloudflareSpeedTest v2.1.0 

开始延迟测速（模式：TCP，端口：443，平均延迟上限：80 ms，平均延迟下限：30 ms)
6534 / 6534 [-----------------------------------------------------------------------------------------------------------------------] 100.00%
开始下载测速（下载速度下限：0.20 MB/s，下载测速数量：5，下载测速队列：8）：
0 / 5 [_______________________________________________________________________________________________________________________________] 0.00%
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
104.18.126.53     5       5       0.00    44.61     0.00           
104.17.146.117    5       5       0.00    46.07     0.00           
104.17.167.209    5       5       0.00    53.68     0.00           
104.19.159.41     5       5       0.00    75.95     0.00           
104.19.207.111    5       5       0.00    76.15     0.00           
104.17.60.73      5       5       0.00    76.73     0.00           
104.19.242.199    5       5       0.00    76.86     0.00           
104.19.190.216    5       5       0.00    79.42     0.00           

完整测速结果已写入 result_hosts.txt 文件，可使用记事本/表格软件查看。

**Comment by XIU2** [comment]
这不是 BUG，就是这样设计的。

当一个满足条件的 IP 都没有时，软件会把所有 IP 的测试结果输出，来方便你查看这些结果，判断问题（如是不是你把条件设置过高了之类的，这样下次测速就知道该如何调整条件了）。
