### ISSUE TITLE
windows_amd64 版本依然 2.1.0 

### ISSUE THREAD

**Issue by milo1023** [XIU2/CloudflareSpeedTest#283]
发现请关闭

**Comment by 1265578519** [comment]
![image](https://user-images.githubusercontent.com/6442439/215835309-d37f8e2d-64bb-4562-b507-17e3fb146154.png)

**Comment by YujiaCheng1996** [comment]
Linux的也是，还是老版本

**Comment by XIU2** [comment]
人傻了，可能是昨天忙活一下午忙昏头了，只运行了编译脚本，忘记运行压缩脚本了。。。导致又把旧压缩文件上传了。。。

已经更新压缩包为最新版本了。
