### ISSUE TITLE
在一台hz服务器上运行了CloudflareST_windows_amd64 v2.2.0，然后ip被锁定了，，说我在网络扫描，问我为什么这么做和如何避免

### ISSUE THREAD

**Issue by 1265578519** [XIU2/CloudflareSpeedTest#285]
在一台hz服务器上运行了CloudflareST_windows_amd64 v2.2.0，然后ip被锁定了，，说我在网络扫描，问我为什么这么做和如何避免

好麻烦
![2](https://user-images.githubusercontent.com/6442439/216306780-93fd1764-d1b8-4ff1-9889-a4c6f6c92f57.jpg)

各位切记别在服务器上运行，或者试一试的想法挂代理去测vps服务器的速度。

**Comment by vanishs** [comment]
我觉得这个血的教训应该放在README中。要不ISSUES会经常有人提了。

**Comment by 1265578519** [comment]
![1](https://user-images.githubusercontent.com/6442439/216761884-40da7046-011a-4ea3-8f39-e4ca1cee0074.png)
和服务器商家中英文沟通困难。。。

**Comment by XIU2** [comment]
@vanishs 加上了，不过能不能注意到就随缘啦。。。
https://github.com/XIU2/CloudflareSpeedTest#-httping

**Comment by 1265578519** [comment]
![image](https://user-images.githubusercontent.com/6442439/218320598-e53d94a0-8ada-4630-8032-8065c3083e53.png)
![image](https://user-images.githubusercontent.com/6442439/218320718-8ed80170-47a0-4aba-8164-aecb45cc101c.png)
![image](https://user-images.githubusercontent.com/6442439/218320759-0d303483-6a40-49f9-a529-2766e524bb8d.png)
和老外沟通不过来，，，只能到期取消后重新买新的了

**Comment by fireinrain** [comment]
这个issue可以关掉吧
