### ISSUE TITLE
linux 下载最新的2.2版本结果发现还是2.1版本，这是打包错了么？

### ISSUE THREAD

**Issue by Nicolas-Gong** [XIU2/CloudflareSpeedTest#286]
flag provided but not defined: -cfcolo

CloudflareSpeedTest v2.1.0

一开始以为下载错了，下载了好几次，都是这样，去蓝奏云下载也是一样的。

**Comment by XIU2** [comment]
#283

**Comment by Nicolas-Gong** [comment]
我前2天下载的，今天才用发现是2.1，今天又重新下了几次都是2.1，那么请问啥时候更新下啊？

**Comment by XIU2** [comment]
两天前就更新了，我可以确定现在的文件都是最新的 v2.2.0 版本。

我随便下了几个都是 v2.2.0 的，没有任何问题，请检查你那边是不是哪里搞错了吧。

**Comment by Nicolas-Gong** [comment]
现在可以了，十点多时我下载了2次，蓝奏云下载了1次，都是2.1。
用的都是这个链接https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.0/CloudflareST_linux_amd64.tar.gz
直接wget下载的。
