### ISSUE TITLE
⭕️如何使用此工具测试上传速度？

### ISSUE THREAD

**Issue by zedzenon** [XIU2/CloudflareSpeedTest#287]
你好
如您所知，此工具会根据下载速度找到最佳的 Cloudflare IP

怎样才能只根据上传速度进行测试呢？

我可以获得具有最佳上传速度的 CDN IP 吗？

**Comment by XIU2** [comment]
CloudflareST 不支持对上传进行测速，且有该需求的人太少，因此也不会考虑添加支持的。
