### ISSUE TITLE
测速一直为0的问题

### ISSUE THREAD

**Issue by CussiusKon** [XIU2/CloudflareSpeedTest#292]
如果说网站套了cdn之后仍然无法访问，是不是自建的测速也无法正常使用啊？我现在遇到的情况就是域名套了cdn也无法直接访问了，无论怎么优选，测速阶段都没有速度，一个都选不出来了。。。。这是正常的吗

**Comment by XIU2** [comment]
没明白你说的是什么意思。

用默认下载测速地址有速度么？或者说用其他别人分享的下载测速地址有速度么？

**Comment by CussiusKon** [comment]
> 

好像是我的宽带线路有问题，同一个ip，用宽带非常慢，用手机网络就很快。是被宽带运营商限速了吗

**Comment by CussiusKon** [comment]
> 没明白你说的是什么意思。
> 
> 用默认下载测速地址有速度么？或者说用其他别人分享的下载测速地址有速度么？

**Comment by XIU2** [comment]
或许吧，这种情况只能猜。
如果是运营商限速的，那么无解。。
如果只是单纯的宽带与 Cloudflare CDN 之间的网络问题，那么还是无解。。。

**Comment by XIU2** [comment]
Github Releases 更新 v2.2.2 版本了，你测试完没啥问题的话，就关闭该 Issues 吧~

这算是一个因为 注释不规范+测试不完全 导致的 BUG，缘由这里说明了：https://github.com/XIU2/CloudflareSpeedTest/pull/290#issuecomment-1426980439

**Comment by chxin579** [comment]
> Github Releases 更新 v2.2.2 版本了，你测试完没啥问题的话，就关闭该 Issues 吧~
> 
> 这算是一个因为 注释不规范+测试不完全 导致的 BUG，缘由这里说明了：[#290 (comment)](https://github.com/XIU2/CloudflareSpeedTest/pull/290#issuecomment-1426980439)

修复完又出BUG了，显示可用几百个，然后下面测速0个
![111](https://user-images.githubusercontent.com/43876662/218307140-ac86e5bf-b4d2-4172-a1a2-7c480734415a.png)

**Comment by XIU2** [comment]
@chxin579 这不是 BUG，可用数量仅代表未超时的 IP，并不代表过滤条件后的 IP 数量。

**Comment by chxin579** [comment]
> @chxin579 这不是 BUG，可用数量仅代表未超时的 IP，并不代表过滤条件后的 IP 数量。

对不起，延迟上限写错了
