### ISSUE TITLE
2.2.1 测速一直为0

### ISSUE THREAD

**Issue by lovelygfj** [XIU2/CloudflareSpeedTest#293]
不论用默认的url还是自定义的url，测速永远是0.
同样的设置，2.2.0就正常。
请大佬检查一下，谢谢

**Comment by XIU2** [comment]
请描述详细一点，因为我更新版本前都测试了最少几十遍（用来检查 BUG 是否修复成功）均没有问题。

**Comment by lovelygfj** [comment]
**默认：**
PS C:\Users\***\Desktop\better-cloudflare-ip\xiu2> .\CloudflareST.exe
# XIU2/CloudflareSpeedTest v2.2.1

开始延迟测速（模式：TCP，端口：443，平均延迟上限：9999 ms，平均延迟下限：0 ms)
5955 / 5955 [--------------------------------------------------------------------------------------------] 可用: 3040
开始下载测速（下载速度下限：0.00 MB/s，下载测速数量：10，下载测速队列：10）：
10 / 10 [------------------------------------------------------------------------------------------------]
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
162.159.58.56     4       4       0.00    89.55     0.00
104.19.157.83     4       4       0.00    158.08    0.00
104.19.91.35      4       4       0.00    160.34    0.00
104.19.156.217    4       4       0.00    160.74    0.00
104.19.110.187    4       4       0.00    163.74    0.00
104.19.162.173    4       4       0.00    163.95    0.00
104.19.120.7      4       4       0.00    165.35    0.00
104.19.205.39     4       4       0.00    165.79    0.00
104.19.138.78     4       4       0.00    166.84    0.00
104.19.254.173    4       4       0.00    167.01    0.00

完整测速结果已写入 result.csv 文件，可使用记事本/表格软件查看。
按下 回车键 或 Ctrl+C 退出。

**自定义**
PS C:\Users\lovel\Desktop\better-cloudflare-ip\xiu2> .\CloudflareST.exe -n 1000 -dn 5 -f ips.txt -url https://cdn.cloudflare.steamstatic.com/steam/apps/256843155/movie_max.mp4
# XIU2/CloudflareSpeedTest v2.2.1

开始延迟测速（模式：TCP，端口：443，平均延迟上限：9999 ms，平均延迟下限：0 ms)
13 / 13 [--------------------------------------------------------------------------------------------------] 可用: 11
开始下载测速（下载速度下限：0.00 MB/s，下载测速数量：5，下载测速队列：5）：
5 / 5 [----------------------------------------------------------------------------------------------------]
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
162.159.58.89     4       4       0.00    63.54     0.00
64.68.192.87      4       4       0.00    184.52    0.00
162.159.160.222   4       4       0.00    194.19    0.00
172.64.199.228    4       4       0.00    210.16    0.00
172.64.141.74     4       4       0.00    211.31    0.00

完整测速结果已写入 result.csv 文件，可使用记事本/表格软件查看。
按下 回车键 或 Ctrl+C 退出。

**Comment by XIU2** [comment]
我研究下看看

**Comment by lylus** [comment]
我也出现了这个问题，linux和windows的情况一样，用老版本就正常，

**Comment by XIU2** [comment]
你们先去蓝奏云下载最新的 v2.2.2 版本再试试是否正常。
https://pan.lanzouv.com/b0742hkxe

Github Releases 上传文件似乎在抽风。。。

**Comment by XIU2** [comment]
Github Releases 也更新 v2.2.2 文件了，你测试完没啥问题的话，就关闭该 Issues 吧~

这算是一个因为 注释不规范+测试不完全 导致的 BUG，缘由这里说明了：https://github.com/XIU2/CloudflareSpeedTest/pull/290#issuecomment-1426980439

**Comment by lovelygfj** [comment]
2.2.2测试OK

**Comment by XIU2** [comment]
@lovelygfj @lylus 
你们再重新下载一下，因为我刚才发现了 #200 问题的真正原因，顺便给修复了，考虑到时间间隔太近，也没几个人下载，因此就干脆不更新版本号，直接重新编译一份上传替换旧文件了~

**Comment by XIU2** [comment]
@lovelygfj @lylus 我擦，我特么又忙昏头了，刚才又光编译忘记压缩了，搞得我又特么给旧压缩包上传上去了，又犯了和发布 v2.2.0 版本时一样的错。。。
你们刚才如果看到我发的上一条回复而重新下载了的话，请再重新下载一次。。。

**Comment by lovelygfj** [comment]
有点奇怪，第一次运行正常。后续再运行，就ping不到了。
暂时还不知道是网络环境的问题，还是程序的问题。

PS C:\Users\lovel\Desktop\better-cloudflare-ip\xiu2> .\CloudflareST.exe -n 1000 -dn 5 -f ips.txt -url https://cdn.cloudflare.steamstatic.com/steam/apps/256843155/movie_max.mp4 -sl 1 -httping
[小提示] 在使用 [-sl] 参数时，建议搭配 [-tl] 参数，以避免因凑不够 [-dn] 数量而一直测速...
XIU2/CloudflareSpeedTest v2.2.2

开始延迟测速（模式：HTTP，端口：443，平均延迟上限：9999 ms，平均延迟下限：0 ms)
1242 / 1242 [--------------------------------------------------------------------------------------------] 可用: 1223
开始下载测速（下载速度下限：1.00 MB/s，下载测速数量：5，下载测速队列：1223）：
5 / 5 [--------------------------------------------------------------------------------------------------]
IP 地址                                   已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
2606:4700:8d79:a658:48ce:e1f3:e92c:344f   4       4       0.00    225.90    5.28
2606:4700:8d79:a658:48c1:4ab0:dce2:676e   4       4       0.00    227.04    5.21
2606:4700:8d79:0:f1:2143:d3ab:4e9b        4       4       0.00    227.29    5.13
2606:4700:8d79:a6e7:347c:f80f:1a8e:dab9   4       4       0.00    226.90    5.12
2606:4700:8d79:de:712a:d9fc:b55e:33a9     4       4       0.00    226.56    5.01

完整测速结果已写入 result.csv 文件，可使用记事本/表格软件查看。
按下 回车键 或 Ctrl+C 退出。
PS C:\Users\lovel\Desktop\better-cloudflare-ip\xiu2> .\CloudflareST.exe -n 1000 -dn 5 -f ips-v4.txt -url https://cdn.cloudflare.steamstatic.com/steam/apps/256843155/movie_max.mp4 -sl 1 -httping
[小提示] 在使用 [-sl] 参数时，建议搭配 [-tl] 参数，以避免因凑不够 [-dn] 数量而一直测速...
# XIU2/CloudflareSpeedTest v2.2.2

开始延迟测速（模式：HTTP，端口：443，平均延迟上限：9999 ms，平均延迟下限：0 ms)
6531 / 6531 [-----------------------------------------------------------------------------------------------] 可用: 1
开始下载测速（下载速度下限：1.00 MB/s，下载测速数量：1，下载测速队列：1）：
1 / 1 [-----------------------------------------------------------------------------------------------------]
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
1.1.1.1           4       4       0.00    241.25    16.60

完整测速结果已写入 result.csv 文件，可使用记事本/表格软件查看。
按下 回车键 或 Ctrl+C 退出。
PS C:\Users\lovel\Desktop\better-cloudflare-ip\xiu2> .\CloudflareST.exe -n 1000 -dn 5 -f ips-v4.txt -url https://cdn.cloudflare.steamstatic.com/steam/apps/256843155/movie_max.mp4 -sl 1 -httping
[小提示] 在使用 [-sl] 参数时，建议搭配 [-tl] 参数，以避免因凑不够 [-dn] 数量而一直测速...
# XIU2/CloudflareSpeedTest v2.2.2

开始延迟测速（模式：HTTP，端口：443，平均延迟上限：9999 ms，平均延迟下限：0 ms)
3000 / 6531 [------------------------------------------↙___________________________________________________] 可用: 0
PS C:\Users\lovel\Desktop\better-cloudflare-ip\xiu2> .\CloudflareST.exe -n 1000 -dn 5 -f ips-v4.txt -url https://cdn.cloudflare.steamstatic.com/steam/apps/256843155/movie_max.mp4 -sl 1
[小提示] 在使用 [-sl] 参数时，建议搭配 [-tl] 参数，以避免因凑不够 [-dn] 数量而一直测速...
# XIU2/CloudflareSpeedTest v2.2.2

开始延迟测速（模式：TCP，端口：443，平均延迟上限：9999 ms，平均延迟下限：0 ms)
6531 / 6531 [-----------------------------------------------------------------------------------------------] 可用: 0

[信息] 延迟测速结果 IP 数量为 0，跳过下载测速。

[信息] 完整测速结果 IP 数量为 0，跳过输出结果。

**Comment by lovelygfj** [comment]
不知道进程是不是没有彻底关闭，等一会儿再运行，就正常了。之前2.2.1的时候，好像偶发也有这个情况。不太像运营商阻断的。

**Comment by XIU2** [comment]
这种情况，放在 TCPing 上不正常，放在 HTTPing 上可能就算是正常情况了。
你可以参考第一个 HTTPing PR  #254 里的我们测试时遇到的情况。

即使后来第二个 PR 优化了下，改成了**只请求头部**，但是在一些情况下也会出现类似的情况，比如我这边联通对 Cloudflare CDN  IPv4 地址存在阻断干扰机制 #217 ，只要建立 HTTPS 链接（无论是正常链接还是仅请求头部），都会触发机制，因此我这边用 HTTPing 测速 CF IPv4 的话，就会每次测速，可用 IP 数量一次比一次少（超时的 IP 就是触发阻断机制了），属实蛋疼。。。

**Comment by lovelygfj** [comment]
> 

那就没问题了，感谢大佬！

**Comment by XIU2** [comment]
因此你这种情况，要么是运营商干的、要么就是墙干的、要么就是 Cloudflare CDN 干的，但难以判断具体是哪个导致的。
因为 HTTPing 本质上也算是一种网络扫描行为，像 #285 在海外服务器上使用，遇到管理严格的 IDC 就认为你是在网络扫描，直接给服务器暂停了。。。
因此运营商、Cloudflare CDN 也可能是因为这个缘由而限制你一段时间，因此才会过一会儿就恢复了。
