### ISSUE TITLE
关于 新版本只能测试 443端口  下载速度得问题

### ISSUE THREAD

**Issue by L763103999** [XIU2/CloudflareSpeedTest#294]
测试443端口得时候 可以测试 延迟  和下载 速度 测试 80端口 或者其他异形端口时候 无法测试下载速度  我使用其他脚本 可测试 80端口下载速度
![image](https://user-images.githubusercontent.com/114154414/218448067-ef6af00e-f46b-4888-b667-0439e4737dfa.png)
结果呈现 

使用其他脚本时候 可测试 80端口

**Comment by XIU2** [comment]
你测速 -tp 80 端口，需要 -url 指定 http 协议的下载测速地址。
