### ISSUE TITLE
CloudflareST.exe : 无法将“CloudflareST.exe”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。

### ISSUE THREAD

**Issue by tandix** [XIU2/CloudflareSpeedTest#298]
执行下面的这个命令，对ip进一步优选遇到问题
PS E:\软件\CloudflareST> CloudflareST.exe -tll 5

下面是系统回复的报错信息
![报错截图01](https://user-images.githubusercontent.com/125651779/220686784-327e0836-c6bd-43e9-844a-0c743754baad.png)

CloudflareST.exe : 无法将“CloudflareST.exe”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果
包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ CloudflareST.exe -tll 5
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (CloudflareST.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

不太懂代码，请问这个要怎么解决？

**Comment by XIU2** [comment]
Windows 系统下 CMD 和 PowerShell 是完全不同的。

在 CMD 里是这样运行的：
```cmd
CloudflareST.exe -tll 5
```

在 PowerShell 里则是这样运行的：
```PowerShell
.\CloudflareST.exe -tll 5
```
