### ISSUE TITLE
提个建议，希望增加丢包率排序

### ISSUE THREAD

**Issue by kingvenlee** [XIU2/CloudflareSpeedTest#30]
提个建议，希望增加丢包率排序。
因为找出来的速度快的ip，丢包率很高的话没有什么意义的

**Comment by XIU2** [comment]
一直都有的。

软件是先延迟测速，然后再延迟排序，延迟排序的时候，**丢包的和不丢包的是独立排序的**。
然后再去从最低延迟开始下载测速（不丢包的）。

你可以使用 `-dd` 禁用下载测速，然后正常延迟测速一次后，去看 `result.csv` 文件，就能发现，文件内容前半段是不丢包的按延迟排序，后半段是丢包的按延迟排序。

**Comment by XIU2** [comment]
如果没什么问题的话，就关闭该 Issues 吧。
当然，走之前如果觉得软件还不错，就点个 ⭐ 吧！
