### ISSUE TITLE
ParseCIDR err invalid CIDR address: /128

### ISSUE THREAD

**Issue by hamidtb** [XIU2/CloudflareSpeedTest#300]
hi
i have a list of IP like this:

23.227.38.53
23.227.39.11
104.16.97.148
66.235.200.241
23.227.39.54

and this IP's stored in ip.txt

but every time i run program in linux, it give the flowing error: 
ParseCIDR err invalid CIDR address: /128

**Comment by charSLee013** [comment]
Hi there,
I tried running the program on my Linux machine and it worked without any errors. Here's the output I got:
```
user@Ubuntu:/tmp/CloudflareSpeedTest$ go run .
# XIU2/CloudflareSpeedTest

开始延迟测速（模式：TCP，端口：443，平均延迟上限：9999 ms，平均延迟下限：0 ms)
5 / 5 [----------------------------------------------------------------------------------------------------] 可用: 5
开始下载测速（下载速度下限：0.00 MB/s，下载测速数量：5，下载测速队列：5）：
5 / 5 [----------------------------------------------------------------------------------------------------]
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
66.235.200.241    4       4       0.00    1.58      0.00
23.227.38.53      4       4       0.00    1.61      0.00
104.16.97.148     4       4       0.00    1.78      0.00
23.227.39.54      4       4       0.00    1.79      0.00
23.227.39.11      4       4       0.00    1.81      0.00

完整测速结果已写入 result.csv 文件，可使用记事本/表格软件查看。
user@Ubuntu:/tmp/CloudflareSpeedTest$ cat ip.txt
23.227.38.53
23.227.39.11
104.16.97.148
66.235.200.241
23.227.39.54
```

Please try updating to the latest version of the program or provide more information, such as the output log, for further debugging.

**Comment by XIU2** [comment]
I remember seeing similar feedback before. After troubleshooting, it was found that the file contained invisible characters, so please check your `ip.txt` file.

**Comment by Atticus6** [comment]
ip.txt后面不能有空格键
