### ISSUE TITLE
不能识别/24 IP段

### ISSUE THREAD

**Issue by fantastlcok** [XIU2/CloudflareSpeedTest#31]
测试指定IP时，例如 1.1.1.1/24 。还是会随机选取IP段里的IP进行测试。

**Comment by XIU2** [comment]
emmm 使用 1.1.1.1/32 即可。
字位掩码 32 指的就是单个 IP 。

**Comment by fantastlcok** [comment]
> emmm使用1.1.1.1/32即可。
> 字位长度32指的就是单一IP。

发完马上意识到....我弱智了。丢人
