### ISSUE TITLE
为何删除了某几个IP？

### ISSUE THREAD

**Issue by mjj996** [XIU2/CloudflareSpeedTest#35]
35.200.109.86/32
202.81.235.61/32
202.81.235.92/32

旧版还有的哦，新版删除了？
难道有什么秘密？

**Comment by XIU2** [comment]
这三个不是 Cloudflare 官方的 IP，是其他 Issues 里别人扫描到的。

第一个 IP 是个人自建的（谷歌云的个人服务器），这个人找到了我让我移除的。
后两个 IP 已经失效（估计是用的人太多）。

**Comment by mjj996** [comment]
> 这三个不是 Cloudflare 官方的 IP，是其他 Issues 里别人扫描到的。
> 
> 第一个 IP 是个人自建的（谷歌云的个人服务器），这个人找到了我让我移除的。
> 后两个 IP 已经失效（估计是用的人太多）。



> 这三个不是 Cloudflare 官方的 IP，是其他 Issues 里别人扫描到告诉我的，我才加到 `ip.txt` 中了。
> 
> * 第一个 IP 是个人自建的（用到谷歌云服务器，所以也存在安全隐患），这个人找到了我并要求移除。
> * 后两个 IP 则是已经失效（估计是公开后用的人太多导致）。

谢谢指教
