### ISSUE TITLE
/128报错

### ISSUE THREAD

**Issue by SunnyGPT** [XIU2/CloudflareSpeedTest#362]
### 问题描述

运行程序之后，cmd里.\程序报错
Microsoft Windows [版本 10.0.17134.228]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\Users\zero\Desktop\86>.\CloudflareST.exe
# XIU2/CloudflareSpeedTest v2.2.2

2023/03/07 00:40:49 ParseCIDR err invalid CIDR address: /128

C:\Users\zero\Desktop\86>

哭晕，半天找不到原因

### 软件版本

2.2.2

### 附加截图

![WX20230307-004403](https://user-images.githubusercontent.com/126902077/223175393-a135eb35-63fc-438d-b1e9-e4e813c8441c.png)

**Comment by XIU2** [comment]
如果 ip.txt 内的 IP 或 IP 段你没写错的话，那么多半是其中存在一些不可见字符导致的，因为类似的情况我见过好几次了。。
比如在网页之类的地方复制时，可能会连带着复制了一些不可见字符。

**Comment by SunnyGPT** [comment]
谢谢，确实cmd合并后出现隐藏字符。
________________________________
发件人: XIU2 ***@***.***>
发送时间: 2023年3月7日 8:26
收件人: XIU2/CloudflareSpeedTest ***@***.***>
抄送: SunnyGPT ***@***.***>; State change ***@***.***>
主题: Re: [XIU2/CloudflareSpeedTest] /128报错 (Issue #362)


如果 ip.txt 内的 IP 或 IP 段你没写错的话，那么多半是其中存在一些不可见字符导致的，因为类似的情况我见过好几次了。。
比如在网页之类的地方复制时，可能会连带着复制了一些不可见字符。

―
