### ISSUE TITLE
可以指定ip开头扫描吗，因为104经常被封，172稳定，默认扫描会出来很多不可用的104ip节点

### ISSUE THREAD

**Issue by 454592673** [XIU2/CloudflareSpeedTest#365]
### 功能需求

如题

### 预期目标

使用时增加参数指定ip开头进行测速

**Comment by XIU2** [comment]
你改一下默认的 ip.txt 内的 IP 段数据不就行了？

https://github.com/XIU2/CloudflareSpeedTest#-ipv4ipv6
