### ISSUE TITLE
设置的延迟不生效

### ISSUE THREAD

**Issue by nilfei** [XIU2/CloudflareSpeedTest#37]
![image](https://user-images.githubusercontent.com/18027182/105055236-d25bb680-5aad-11eb-9fce-8ab2a18f281e.png)

**Comment by XIU2** [comment]
项目使用示例中 [#自定义测速条件](https://github.com/XIU2/CloudflareSpeedTest#-自定义测速条件) 写了：

> 如果满足条件的 IP 一个都没找到，那么就会和不指定条件一样输出完整结果。
> 所以建议先不指定条件测速一遍，看看平均延迟和下载速度大概在什么范围，避免指定条件过低/过高！

你设置的下载速度下限为 20 MB/s，但软件测速结果中**一个满足条件的都没有**，所以就会等同于不指定测速条件一样输出结果。
