### ISSUE TITLE
下载测速10条IP没测速完 CMD窗口就消失了

### ISSUE THREAD

**Issue by ccxx25** [XIU2/CloudflareSpeedTest#371]
### 问题描述

软件第一次使用是正常的  后面再启动 下载测速10条IP没测速完 CMD窗口就消失了

### 软件版本

v2.2.2

**Comment by XIU2** [comment]
CloudflareST 是一个命令行程序，如果报错的话会直接退出，想要查看错误信息，就要通过 CMD 命令行去运行 CloudflareST，这样即使闪退也只是 CloudflareST 的进程退出，CMD 的命令行窗口依然正常，并且可以看到错误信息。

如果你不知道怎么用 CMD 去运行 CloudflareST.exe，那么请参考这个教程（注意最后一个运行步骤的命令，你不需要加上任何参数，只需要运行 `CloudflareST.exe` 即可，即和你双击运行一样，所有参数都使用默认值）。

https://github.com/XIU2/CloudflareSpeedTest#-cmd-带参数运行-cloudflarest

**Comment by ccxx25** [comment]
嗯 解决了，是result.csv 这个文件在编辑状态 所以测速完保存报错了
