### ISSUE TITLE
macOS 支持M芯片使用 homebrew 安装

### ISSUE THREAD

**Issue by Mrered** [XIU2/CloudflareSpeedTest#372]
### 功能需求

我做了一个，纯小白水平，目前只支持 `arm64` 版，有时间了做 `amd64` 。
I made new one! But only support `arm64/Apple Silicon` instead `amd64/Intel`. When I have time, I will make an `amd64/Intel` version support.

安装方式：
How to install:

```shell
brew install mrered/cloudflarest/cfstarm64
```

### 预期目标

有时间了做 `amd64` 。
When I have time, I will make an `amd64/Intel` version support.

![截图](https://user-images.githubusercontent.com/34948506/230725702-49466e57-8f22-4c11-9e99-4fa08aedc748.png)

**Comment by Mrered** [comment]
由于本人非常懒，所以为了避免漏掉作者新的 release 会订阅一个 RSS 提醒我的，一般会在较快时间内更新。

**Comment by Mrered** [comment]
目前存在的问题，不能直接在终端里 `CloudflareST` 必须指定 `ip.txt` 位置 `/opt/homebrew/Cellar/cfstarm64/2.2.2/bin/ip.txt` 

```shell
CloudflareST -f /opt/homebrew/Cellar/cfstarm64/2.2.2/bin/ip.txt
```

**Comment by XIU2** [comment]
> 由于本人非常懒，所以为了避免漏掉作者新的 release 会订阅一个 RSS 提醒我的，一般会在较快时间内更新。

放心，我也很懒，一般不是 BUG 之类的非必要我也是基本不会更新的~

**Comment by Mrered** [comment]
> ### 功能需求
> 我做了一个，纯小白水平，目前只支持 `arm64` 版，有时间了做 `amd64` 。 I made new one! But only support `arm64/Apple Silicon` instead `amd64/Intel`. When I have time, I will make an `amd64/Intel` version support.
> 
> 安装方式： How to install:
> 
> ```shell
> brew install mrered/cloudflarest/cfstarm64
> ```
> 
> ### 预期目标
> 有时间了做 `amd64` 。 When I have time, I will make an `amd64/Intel` version support.
> 
> ![截图](https://user-images.githubusercontent.com/34948506/230725702-49466e57-8f22-4c11-9e99-4fa08aedc748.png)

还没实现 `amd64` 却节外生枝了一个懒人版

**Comment by Mrered** [comment]
另外，我发现了一个仓库，开了一个 PR [Update CloudflareSpeedTest by Mrered · Pull Request #12 · ivaquero/homebrew-chinese (github.com)](https://github.com/ivaquero/homebrew-chinese/pull/12#issuecomment-1549703911) 由于比较小白，过程比较曲折。

**Comment by XIU2** [comment]
我没用过因此不清楚 Mac 系统下使用 .zip 还是 .tar.gz 会更好。
我只是当初搜索了一下，根据官方的教程来看：

`.zip` 解压会更方便点，可以通过 GUI 操作。  
> https://support.apple.com/zh-cn/guide/mac-help/mchlp2528/mac

`.tar.gz` 解压的话，似乎只能通过终端命令行方式来操作。  
> https://support.apple.com/zh-cn/guide/terminal/apdc52250ee-4659-4751-9a3a-8b7988150530/mac

因此，为了尽可能降低使用门槛，我选择了兼容性最好、最主流的 `.zip` 压缩格式（Windows、Mac、Android、iOS 都可以**无需第三方应用**就能解压），而 Linux 可能默认没有自带支持解压 `.zip` 的工具（例如 unzip），因此选择了 `.tar.gz` 压缩格式。

**Comment by Mrered** [comment]
作者不嫌辛苦的话，可以单独发布两个为macOS准备的 `.tar.gz` 嘛？感谢😘

**Comment by ystarlongzi** [comment]
安装时怎么还需要 github 的账密？
