### ISSUE TITLE
arm openwrt下无下载速度

### ISSUE THREAD

**Issue by xvim** [XIU2/CloudflareSpeedTest#374]
### 问题描述

BusyBox v1.35.0 (2022-11-25 01:15:37 UTC) built-in shell (ash)
Mem: 167080K used, 333948K free, 284K shrd, 112K buff, 41212K cached
CPU:   0% usr   1% sys   0% nic  97% idle   0% io   0% irq   0% sirq
Load average: 0.13 0.14 0.08 2/139 27958
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
27621 27616 root     S     700m 143%   1% cdnspeedtest -t 3 -n 50 -dn 10 -tl 250 -tll 40 -sl 3 -p 10

运行在红米ax6000 openwrt路由器上面，没有下载速度，同一网络，换笔记本运行正常，需要大量内存？

### 软件版本

v2.2.1

### 附加截图

Cloudflare账号验证成功
当前工作模式为ipv4
按要求未停止科学上网服务
# XIU2/CloudflareSpeedTest v2.2.1 

开始延迟测速（模式：TCP，端口：443，平均延迟上限：250 ms，平均延迟下限：40 ms)
5955 / 5955 [-----------------------------------------------------] 可用: 3026  
开始下载测速（下载速度下限：3.00 MB/s，下载测速数量：10，下载测速队列：2666）：
0 / 10 [________________________________________________________________________________________________________________________________________________________________________]

BusyBox v1.35.0 (2022-11-25 01:15:37 UTC) built-in shell (ash)
Mem: 167080K used, 333948K free, 284K shrd, 112K buff, 41212K cached
CPU:   0% usr   1% sys   0% nic  97% idle   0% io   0% irq   0% sirq
Load average: 0.13 0.14 0.08 2/139 27958
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
27621 27616 root     S     700m 143%   1% cdnspeedtest -t 3 -n 50 -dn 10 -tl 250 -tll 40 -sl 3 -p 10

**Comment by XIU2** [comment]
CloudflareST 下载测速过程中，下载的文件内容只会在网卡过一遍计算一下流量就丢弃了（类似于 Linux 下的 /dev/null），不会写入内存/硬盘的，因此对内存和影片无要求。
