### ISSUE TITLE
使用 -tl -sl 5 -dn 10 测不出来  

### ISSUE THREAD

**Issue by Tzbfire** [XIU2/CloudflareSpeedTest#38]
有bug

开始下载测速（延迟时间上限：200 ms，下载速度下限：5 MB/s）：
0 / 10 [________________________________________________________________________________________________________] 0.00%
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
198.41.220.24     4       4       0.00    260.25    0.00
198.41.222.204    4       4       0.00    260.71    0.00
198.41.209.100    4       4       0.00    261.01    0.00
198.41.221.8      4       4       0.00    261.50    0.00
190.93.247.46     4       4       0.00    263.24    0.00
1.0.0.238         4       4       0.00    265.19    0.00
190.93.245.55     4       4       0.00    274.14    0.00
141.101.113.236   4       4       0.00    275.64    0.00
198.41.214.130    4       4       0.00    277.21    0.00
198.41.212.23     4       4       0.00    327.14    0.00
141.101.121.79    4       4       0.00    328.64    0.00
190.93.246.237    4       4       0.00    329.88    0.00
173.245.49.234    4       4       0.00    330.89    0.00
198.41.211.213    4       4       0.00    376.90    0.00

**Comment by XIU2** [comment]
嗯，还有什么疑问吗？
如果没有的话，就关闭该 Issues 吧。
