### ISSUE TITLE
Mac arm 运行不起来 cfst_hosts.sh: line 35: ./CloudflareST: Permission denied

### ISSUE THREAD

**Issue by Temozly** [XIU2/CloudflareSpeedTest#381]
### 问题描述

一运行就报错 cfst_hosts.sh: line 35: ./CloudflareST: Permission denied，用sudo方式也不行

### 软件版本

v2.2.3

**Comment by XIU2** [comment]
你能用 MAC 就不应该问出这种问题呀。。。
你应该先赋予 CloudflareST 执行权限，然后才能用啊。
```
chmod a+x ./CloudflareST
```

**Comment by Temozly** [comment]
是的，偷懒了，给mac 丢人了，
