### ISSUE TITLE
能否添加指定 [下载速度上限] 条件？

### ISSUE THREAD

**Issue by yburger** [XIU2/CloudflareSpeedTest#384]
### 问题描述

测速时经常会出现排位第一的测速结果里“下载速度”这一项明显偏高（突破了网络物理上限），比如我宿舍的百兆网，测速结果排第一位的往往下载速度测出13m/s，14m/s甚至更高的下载速度，而排第二位及后面的结果一般都是正常的（接近宽带网速上限），而且那些测速结果偏高的IP往往都延迟巨高且丢包严重（手动ping测试完全没有结果文件里那么低的延迟），能否添加指定 [下载速度上限] 条件，让用户自行设置宽带速度上限，避免被这种异常结果干扰？

### 软件版本

v2.2.3

**Comment by XIU2** [comment]
不会考虑添加，因为这不是常见需求。

**Comment by XIU2** [comment]
另外，测速时某 IP 质量很好，但测速后却变得很劣质，这种情况很显然是触发了什么限制导致 IP 被干扰了。
好像以前有人遇到过这种情况，但也没啥解决办法。

**Comment by yburger** [comment]
好吧，理解，毕竟这个需求确实非常小众。
> 另外，你这个 Issues 属于 `功能建议`，而非 `反馈问题`，你选错了。

选的时候我也想了，因为我是在不同的网络环境中（家里联通宽带、校园网）曾经多次出现过这个问题，“添加指定 [下载速度上限] 条件”这个功能需求只是我能想到的解决这个问题的一个办法，所以我最后还是选择了 `反馈问题`。
不过这个应该不是**测速导致**“**IP 被干扰、丢包、劣化了**”之类的问题，因为每次出问题只有这种**特征非常明显**的IP：测速结果里`下载速度`超出了`宽带网速上限`的结果。因为校园网**百兆网口**的原因，我在内网都没有跑过15m/s的网速，但是测速结果里多次出现过这个速度，而且每次这种速度异常的IP表现极差（我问题中提到的“延迟巨高且丢包严重”）的同时，和他同批次的其他IP都表现很好，如果说是测速导致的干扰，应该不会每次的结果里只有`下载速度`异常高的那个受干扰吧。

**Comment by XIU2** [comment]
不清楚，这种一般都称之为疑难杂症。

以前也有人反馈过类似问题，但是他们的测速结果都明显偏高（不是超出一点半点那种，是几倍甚至几十倍），但在 #290 修复了该问题，后续那些反馈的人也没有再遇到下载测速结果异常偏高的问题了。

**Comment by XIU2** [comment]
你是从 某个版本 开始遇到该问题的？
还是从 某个时间 开始遇到该问题的？

可以稳定复现吗？
