### ISSUE TITLE
测速很快，但无法使用

### ISSUE THREAD

**Issue by vip-design** [XIU2/CloudflareSpeedTest#387]
### 问题描述

测速正常 (延时<40ms，速度 > 10MB/s)，但是填入软件后就无法联通。

IP是国内的IP，其它国外IP都正常。

### 软件版本

v2.2.3

**Comment by XIU2** [comment]
这种问题和 CloudflareST 无关，是其他原因导致的，类似反馈好几个了。

**Comment by vip-design** [comment]
请问一般和什么有关？谢谢！

**Comment by XIU2** [comment]
这我怎么会知道呢。。。

**Comment by XIU2** [comment]
CloudflareST 的原理：
延迟测速是：TCPing / HTTPing（类似于下载测速，但只获取头部而不下载）
下载测速是：
```
curl -o /dev/null --resolve "测速地址的域名:443:IP" https://下载测速地址

# 示例：
curl -o /dev/null  --resolve "speed.cloudflare.com:443:172.67.172.187" https://speed.cloudflare.com/__down?bytes=200000000
```

因此你可以用 curl 实现和 CloudflareST 一样的下载测速效果。

**Comment by mengguyi** [comment]
> 请问一般和什么有关？谢谢！

好好看看README文件和置顶的issue

如果还有问题看看discussions

相信你一定能找到问题所在
![006](https://github.com/XIU2/CloudflareSpeedTest/assets/73788063/e655bf6a-33b1-491f-9a93-c0ee0cce9cc1)

**Comment by vip-design** [comment]
谢谢您的悉心解答！如果我使用需要连接的服务器自建测速地址的话，会不会获得更可靠稳定的结果呢？

> CloudflareST 的原理：
> 
> * **延迟测速**：TCPing / HTTPing（类似于下载测速，但只获取头部而不下载）
> * **下载测速**：和 Curl 的这个参数组合原理完全一致
> 
> ```
> curl -o /dev/null --resolve "测速地址的域名:443:IP" https://下载测速地址
> 
> # 示例：
> curl -o /dev/null --resolve "speed.cloudflare.com:443:172.67.172.187" https://speed.cloudflare.com/__down?bytes=200000000
> ```
> 
> 因此你可以用 Curl 实现和 CloudflareST 一样的下载测速效果。

**Comment by charSLee013** [comment]
> 谢谢您的悉心解答！如果我使用需要连接的服务器自建测速地址的话，会不会获得更可靠稳定的结果呢？

取决于 **Cloudflare 是否缓冲** 或者 **回源到你自建服务器的速度**，一般建议都是用热点较高的资源文件来进行测速
这样可以避免Cloudflare 因为缓冲策略之类的影响，比如公有素材 [https://cdn.cloudflare.steamstatic.com/steam/apps/256843155/movie_max.mp4](https://cdn.cloudflare.steamstatic.com/steam/apps/256843155/movie_max.mp4)

而且我看到你的提问中
> 测出的IP是国内的IP，其它国外IP都正常。

你是在测速国内的反代Cloudflare的IP地址么？这类IP地址并不是Cloudflare 的官方地址，不一定会对你的网络请求活动做出期待的反应（比如使用v2ray 代理之类的)
