### ISSUE TITLE
能否加入筛选掉包率的选项

### ISSUE THREAD

**Issue by xingpingcn** [XIU2/CloudflareSpeedTest#391]
### 功能需求

加入筛选掉包率的选项，例如选取掉包率小于0.2的ip，然后再测速。我发现掉包低，测速结果一般般的ip，实际使用效果远比掉包高，测速结果高的ip稳定、速度快

### 预期目标

加入筛选掉包率的选项，例如选取掉包率小于0.2的ip，然后再测速

**Comment by XIU2** [comment]
v2.2.4 新增 [丢包几率上限] 参数
https://github.com/XIU2/CloudflareSpeedTest/releases/tag/v2.2.4
