### ISSUE TITLE
希望能增加一个证书匹配的功能

### ISSUE THREAD

**Issue by Atlantis829** [XIU2/CloudflareSpeedTest#398]
### 功能需求

我希望这个工具不只是可以扫描CDN的IP段，我也希望它能被用作扫描其他的IP段。我的需求是希望能在Google的IP段中找到可用的googlevidoe.com的可用IP，虽然能扫描出可用的IP，但是不一定能用在video的网站上，也就是证书不匹配。希望您能增加这个功能。还有一个问题想请问一下，对于一个CDN厂家，它的自治系统下所有的IP都能访问被CDN代理的网站嘛？（国内Cloudflare除外），如果是这样，请问为什么Google的CDN扫描出来的可用IP会有证书问题呢？麻烦您了。

### 预期目标

scan 142.251.42.0/24
found 142.254.42.1 match googlevideo.com
就像这样

**Comment by XIU2** [comment]
暂不考虑该 `匹配证书` 功能，因为我用不上，因此也没啥兴趣和动力去折腾。

不是所有 CDN 的都像 Cloudflare CDN 一样，把所有网站证书部署到所有边缘节点上。

目前我就知道 `Cloudflare CDN、AWS Cloudfront CDN、Gcore CDN` 是这样，而像 `Akamai CDN、Fastly CDN` 则都是只部署了部分边缘节点，除此之外，还有一些 CDN（包括前面 CDN 中的一些网站）是只在分配给你的边缘节点 IP 上部署证书。
