### ISSUE TITLE
arm版本无法运行

### ISSUE THREAD

**Issue by iamgit66** [XIU2/CloudflareSpeedTest#4]

**Comment by iamgit66** [comment]
是否要编译为arm64架构才能运行？

**Comment by XIU2** [comment]
> 抱歉回答晚了，才发现我这个项目的通知设置的有问题，导致你们发 Issues 后我没有收到邮件通知。。。  

我这边似乎没有 arm 设备，你用的是哪个 arm 设备测试的？测试报错是什么？

**Comment by iamgit66** [comment]
./CloudflareST: line 1: syntax error: unexpected word (expecting ")")
Neo2开发板，H5芯片。
Linux Neo2 5.4.72 #0 SMP Tue Oct 27 09:55:05 2020 aarch64 GNU/Linux
google了一下，针对开发板，可能在编译参数上需要修改。
对GO语言不熟悉，本想搭个编译环境试试，没搭建成功。
如方便，还请试试编译一个适合开发板使用的版本arm 64位。感谢！

**Comment by XIU2** [comment]
我查查，我对 Golang 也没多熟悉，完全是入门汉临时学的。  
arm 版本我也只是随手一起编译了下，实际并没有测试过（没设备），只测试了 Windows 和 Linux 的。。。

**Comment by XIU2** [comment]
查了下有点蛋疼，我不知道你这个 arm 的编译参数到底要写哪个。。。
你这个是 arm 5 6 7？因为我没有设备所以我也没办法一个个测试。

**Comment by XIU2** [comment]
这个 arm64 你能用吗？

[CloudflareST_linux_arm64.zip](https://github.com/XIU2/CloudflareSpeedTest/files/5495563/CloudflareST_linux_arm64.zip)

**Comment by iamgit66** [comment]
这个版本能运行，非常感谢！！

**Comment by iamgit66** [comment]
如有更新发布，还请也编译一下这个arm64的版本！相当实用！

**Comment by XIU2** [comment]
好吧，这倒是蒙对了。。。  
那我关闭该 Issues 了，有什么问题请重新打开该 Issues 。
