### ISSUE TITLE
自动更新 Cloudflare 中的域名解析记录为最快 IP（Windows/Linux 脚本+手动教程）

### ISSUE THREAD

**Issue by XIU2** [XIU2/CloudflareSpeedTest#40]
如果你的域名托管在 Cloudflare，那么其实可以通过 Cloudflare 官方提供的 [API](https://api.cloudflare.com) 去更新域名解析记录。

该教程受众面窄，**有什么问题可以在下面告诉我，看在我写这么多的份上，点个⭐呗！**

> 因为只有在域名解析网站有域名，才能去测试 API 和写相关教程，所以就没办法去写其他解析网站...

> _不过有个妥协后的低门槛方法：**[自动更新 Hosts 为最快 IP（Windows/Linux 脚本）](https://github.com/XIU2/CloudflareSpeedTest/issues/42)**_

****

## \# 操作步骤观看顺序：

1. [x] [获取 API 令牌](https://github.com/XIU2/CloudflareSpeedTest/issues/40#issuecomment-767403093)
2. [x] [准备依赖](https://github.com/XIU2/CloudflareSpeedTest/issues/40#issuecomment-767403787)
3. [x] [获取域名 ID](https://github.com/XIU2/CloudflareSpeedTest/issues/40#issuecomment-767404048)
4. [x] [获取域名解析记录 ID](https://github.com/XIU2/CloudflareSpeedTest/issues/40#issuecomment-767418181)
5. [x] [更新域名解析记录](https://github.com/XIU2/CloudflareSpeedTest/issues/40#issuecomment-767439136)
6. [x] [自动更新脚本](https://github.com/XIU2/CloudflareSpeedTest/issues/40#issuecomment-767474313)
7. [x] [定时任务](https://github.com/XIU2/CloudflareSpeedTest/issues/40#issuecomment-767482649)

> 因为我没有 MacOS 设备，所以没有写相关教程，但查了下 MacOS 已经内置了 cURL，而命令是相通的，和 Linux 差不多。

****

如果看不到图片，只需把下面这条内容添加到 `C:\Windows\System32\drivers\etc\hosts` 文件中并重启浏览器：
```
151.101.88.133 user-images.githubusercontent.com
```

**Comment by XIU2** [comment]
## 获取 API 令牌

1. 前往 [Cloudflare API 令牌](https://dash.cloudflare.com/profile/api-tokens)页面。
2. 点击 `Global API Key` 后面的 **[查看]** 按钮。
3. 输入 Cloudflare 账号的**密码**，并通过人机验证。
4. 点击复制 **API 令牌**并保存好。

<img src="https://user-images.githubusercontent.com/54703944/105816499-57cff100-5fef-11eb-9059-c22d91782d4e.png" width="40%"><img src="https://user-images.githubusercontent.com/54703944/105816487-56062d80-5fef-11eb-969d-4de8b3f49491.png" width="30%"><img src="https://user-images.githubusercontent.com/54703944/105816494-57375a80-5fef-11eb-8148-8c1fcb7d8865.png" width="30%">

**Comment by XIU2** [comment]
## Linux 系统

### 准备依赖

虽然大部分的 Linux 系统都自带了 cURL，但是还是提前检查一下是否已安装：

``` bash
curl --help
```

如果提示没找到命令，那么就需要手动安装了：

``` bash
# CentOS
yum install -y curl

# Debian/Ubuntu
apt-get install -y curl
```

****

> **注意**：以下的**命令都是一个整体**，修改后要**一起粘贴、运行**，`\` 和 `^` 符号是命令分行用的，这样写方便大家理解。

### 获取域名 ID
``` bash
curl -X GET "https://api.cloudflare.com/client/v4/zones" \
-H "X-Auth-Email: 账号邮箱" \
-H "X-Auth-Key: 前面获取的 API 令牌" \
-H "Content-Type: application/json"
```

### 获取域名的解析记录 ID
``` bash
curl -X GET "https://api.cloudflare.com/client/v4/zones/域名ID/dns_records?page=1&per_page=20&order=type&direction=asc" \
-H "X-Auth-Email: 账号邮箱" \
-H "X-Auth-Key: 前面获取的 API 令牌" \
-H "Content-Type: application/json"
```

### 更新域名解析记录
``` bash
curl -X PUT "https://api.cloudflare.com/client/v4/zones/域名ID/dns_records/解析记录ID" \
-H "X-Auth-Email: 账号邮箱" \
-H "X-Auth-Key: 前面获取的 API 令牌" \
-H "Content-Type: application/json" \
--data '{"type":"A","name":"xxx.yyy.zzz","content":"最快 IP","ttl":1,"proxied":true}'
```

**Comment by XIU2** [comment]
## Windows 系统

### 准备依赖

为了方便，我在 Windows 系统上也用的是 cURL，下载 [cURL](https://xiu.lanzoux.com/b074fx69a) 并解压到任意位置。

> 考虑到很多人可能不会设置环境变量，那就直接用绝对路径好了。
> 如果你会设置环境变量，那么将 cURL 加入环境变量后，就可以把下面的绝对路径改成 `curl` 命令了。

解压 cURL 后，进入 `curl\bin` 看到 `curl.exe` 文件，这时候在地址栏**复制当前文件夹路径**，并替换下面命令头部的 `D:\Program Files\curl\bin\curl.exe` 路径。

****

> **注意**：以下的**命令都是一个整体**，修改后要**一起粘贴、运行**，`\` 和 `^` 符号是命令分行用的，这样写方便大家理解。

### 获取域名 ID
``` bash
"D:\Program Files\curl\bin\curl.exe" -X GET "https://api.cloudflare.com/client/v4/zones" ^
-H "X-Auth-Email: 账号邮箱" ^
-H "X-Auth-Key: 前面获取的 API 令牌" ^
-H "Content-Type: application/json"
```

### 获取域名的解析记录 ID
``` bash
"D:\Program Files\curl\bin\curl.exe" -X GET "https://api.cloudflare.com/client/v4/zones/域名ID/dns_records?page=1&per_page=20&order=type&direction=asc" ^
-H "X-Auth-Email: 账号邮箱" ^
-H "X-Auth-Key: 前面获取的 API 令牌" ^
-H "Content-Type: application/json"
```

### 更新域名解析记录
``` bash
"D:\Program Files\curl\bin\curl.exe" -X PUT "https://api.cloudflare.com/client/v4/zones/域名ID/dns_records/解析记录ID" ^
-H "X-Auth-Email: 账号邮箱" ^
-H "X-Auth-Key: 前面获取的 API 令牌" ^
-H "Content-Type: application/json" ^
--data "{\"type\":\"A\",\"name\":\"xxx.yyy.zzz\",\"content\":\"最快 IP\",\"ttl\":1,\"proxied\":true}"
```

**Comment by XIU2** [comment]
## 关于更新域名解析记录时的 JSON 数据补充说明

指的就是更新解析记录命令中的这段内容：

``` json
{"type":"A","name":"xxx.yyy.zzz","content":"最快 IP","ttl":1,"proxied":true}
```

****

名称 | 示例 | 说明
-- | -- | --
**type** | A | **解析记录类型**，如：A, AAAA, CNAME, HTTPS, TXT, SRV, LOC, MX, NS, SPF, CERT, DNSKEY...
**name** | xxx.yyy.zzz | **完整的域名**，不能只写子域名名称，最长 255 个字符
**content** | 127.0.0.1 | **解析 IP 地址**，IPv4、IPv6
**ttl** | 1 | **解析记录生存时间**，值为 1 则是自动，单位：秒
**proxied** | true | **是否走 CDN 代理**，是：true，否：false)

> 来自：https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record

**Comment by XIU2** [comment]
## 更新域名解析记录

> **注意**：以下的**命令都是一个整体**，修改后要**一起粘贴、运行**，`\` 和 `^` 符号是命令分行用的，这样写方便大家理解。

### Linux 系统

``` bash
curl -X PUT "https://api.cloudflare.com/client/v4/zones/域名ID/dns_records/解析记录ID" \
-H "X-Auth-Email: 账号邮箱" \
-H "X-Auth-Key: 前面获取的 API 令牌" \
-H "Content-Type: application/json" \
--data '{"type":"A","name":"xxx.yyy.zzz","content":"最快 IP","ttl":1,"proxied":true}'
```

****

### Windows 系统

``` bash
"D:\Program Files\curl\bin\curl.exe" -X PUT "https://api.cloudflare.com/client/v4/zones/域名ID/dns_records/解析记录ID" ^
-H "X-Auth-Email: 账号邮箱" ^
-H "X-Auth-Key: 前面获取的 API 令牌" ^
-H "Content-Type: application/json" ^
--data "{\"type\":\"A\",\"name\":\"xxx.yyy.zzz\",\"content\":\"最快 IP\",\"ttl\":1,\"proxied\":true}"
```

****

## 成功？失败？

运行命令后，会输出的一大串 JSON 内容，在其末尾看到，
- 如果写的是 `"success":true` 则说明**成功**。
- 如果写的是 `"success":false` 则说明**失败**，原因会在后面的 `messages` 中说明。

****

## 关于命令中的 JSON 数据说明

指的就是更新解析记录命令中的这段内容：

``` json
{"type":"A","name":"xxx.yyy.zzz","content":"最快 IP","ttl":1,"proxied":true}
```

****

名称 | 示例 | 说明
-- | -- | --
**type** | A | **解析记录类型**，如：A, AAAA, CNAME, HTTPS, TXT, SRV, LOC, MX, NS, SPF, CERT, DNSKEY...
**name** | xxx.yyy.zzz | **完整的域名**，不能只写子域名名称，最长 255 个字符
**content** | 127.0.0.1 | **解析 IP 地址**，IPv4、IPv6
**ttl** | 1 | **解析记录生存时间**，值为 1 则是自动，单位：秒
**proxied** | true | **是否走 CDN 代理**，是：true，否：false)

> 来自：https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record

**Comment by XIU2** [comment]
## \# 通过脚本自动更新域名解析记录

因为时间优先，我就先简单的写了两个脚本，可能比较简陋。。。所以有什么建议可以跟我说。

### \#\# Linux 系统

首先下载脚本（并赋予执行权限）:
``` bash
wget -N https://shell.xiu2.xyz/cfst_ddns.sh && chomd +x cfst_ddns.sh
```

然后需要编辑一下脚本变量（选一个 Linux 文本编辑器），打开后可以看到以如下脚本内容：
- **nano**：`nano cfst_ddns.sh`，打开后可以直接开始修改
- **vim**：`vim cfst_ddns.sh`，打开后还需要按下 **`I 键`** 进入编辑模式

``` bash
#!/usr/bin/env bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

FOLDER="/root/CloudflareST"
ZONE_ID="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
DNS_RECORDS_ID="yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
EMAIL="xxx@yyy.com"
KEY="zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
TYPE="A"
NAME="xxx.yyy.zzz"
TTL="1"
PROXIED="true"

_UPDATE() {
	./CloudflareST
	CONTENT=$(sed -n "2,1p" result.csv | awk -F, '{print $1}')
	curl -X PUT "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records/${DNS_RECORDS_ID}" \
		-H "X-Auth-Email: ${EMAIL}" \
		-H "X-Auth-Key: ${KEY}" \
		-H "Content-Type: application/json" \
		--data "{\"type\":\"${TYPE}\",\"name\":\"${NAME}\",\"content\":\"${CONTENT}\",\"ttl\":${TTL},\"proxied\":${PROXIED}}"
}

cd "${FOLDER}"
_UPDATE
```

各变量名说明：

| 变量名 | 值 |
---- | ----
**FOLDER** | CloudflareST 测速程序所在路径
**ZONE_ID** | 域名 ID
**DNS_RECORDS_ID** | 域名解析记录 ID
**EMAIL** | 账号邮箱
**KEY** | API 令牌
**TYPE** | 解析记录类型
**NAME** | 完整域名
**TTL** | 解析记录生存时间，值为 1 代表自动，单位：秒
**PROXIED** | 是否走 CDN 代理，是：true，否：false

修改完毕后，保存脚本：
- **nano**：按下 Ctrl+X 键、按下 Y 键、按下回车键，即可保存。
- **vim**：按下 Esc 键退出编辑模式，直接输入 `:wq` 并回车（英文模式下），即可保存。

然后运行脚本试试看：

``` bash
bash cfst_ddns.sh
```


****

### \#\# 其他说明

- 以上脚本只是一个示例，大家可以按需修改，比如在 `./CloudflareST` 后面添加其他参数。

****

### \#\# Windows 系统

首先下载批处理脚本：https://shell.xiu2.xyz/cfst_ddns.bat

然后将其放到 CloudflareST 测速程序所在目录下，**右键脚本 - 编辑**，会看到如下脚本内容：

``` bat
@echo off
Setlocal Enabledelayedexpansion
CloudflareST.exe -p 0
for /f "tokens=1 delims=," %%i in (result.csv) do (
    Set /a n+=1 
    If !n!==2 (
        Echo %%i
        curl -X PUT "https://api.cloudflare.com/client/v4/zones/域名ID/dns_records/域名解析记录ID" ^
                -H "X-Auth-Email: 账号邮箱" ^
                -H "X-Auth-Key: 前面获取的 API 令牌" ^
                -H "Content-Type: application/json" ^
                --data "{\"type\":\"A\",\"name\":\"完整域名\",\"content\":\"%%i\",\"ttl\":1,\"proxied\":true}"
        goto :END
    )
)
:END
pause
```

修改其中的**域名 ID、域名解析记录 ID、账号邮箱、API 令牌、完整域名**等信息。

最后保存，双击运行脚本试试看。

> **注意**：脚本运行完毕后**窗口不会关闭**，如果你想要脚本定时自动执行，记得先删除脚本最后的 `pause` 命令。

****

### \#\# 其他说明

- Widnows 的脚本加上参数 `-p 0` 是为了避免测速完成后，需要手动回车退出 CloudflareST。  
- 以上脚本只是一个示例，大家可以按需修改，比如在 `CloudflareST.exe` 后面添加其他参数。

**Comment by XIU2** [comment]
## \# 定时任务

稍后添加...

**Comment by doutuo** [comment]
这个得出的最快ip，直接就填在域名的A记录里面，然后cdn代理又为真开启。那我域名本身对应的ip，应该是我服务器的ip，这样就没法用了。

**Comment by XIU2** [comment]
@doutuo 
这个教程是更新域名解析记录用的，你说的情况代表你的需求不符合这个教程的目的。

**Comment by XIU2** [comment]
@doutuo 
等我稍后写两个自动更新 Hosts 的脚本，应该适用于你的需求了。

**Comment by XIU2** [comment]
@doutuo 
自动更新 Hosts 的脚本写完了，你可以去试试。

**Comment by doutuo** [comment]
> @doutuo
> 自动更新 Hosts 的脚本写完了，你可以去试试。

谢谢，辛苦你了！

**Comment by XIU2** [comment]
@doutuo 
不用谢，用着好用的话，点个 ⭐ 就行了~

**Comment by getizumo** [comment]
和 @doutuo 有同样的疑问（且没看懂 @XIU2 下面的回复）：

如果我的域名 `company.domain` 已经托管在CF，并开启了CDN，那这时候再修改它A记录的IP不就死循环了吗？

**Comment by XIU2** [comment]
@getizumo 

这个教程针对的是其他情况，比如：
 - Cloudflare **Workers**  
  _（我的一个 Github 文件下载加速网站就依赖这个）_
- 单纯的**域名解析**  
  _（比如前几天有个人找我远程协助来配置自动更新，它的梯子 IP 只需要写 Cloudflare CDN IP 即可，连域名都不需要，后来加个域名也是为了可以搭配 CloudflareST 来提高速度）_

一开始写这个教程的时候，我没拐过来弯，写完上面那个人一说，才发现这个教程**有点鸡肋，受众面太窄**了，所以我又写了个**自动更新 Hosts** 的脚本。

**Comment by 892947707** [comment]
域名添加到CF的合作伙伴，使用第三方DNS管理解析记录，比如DNSPOD，测出最快IP后只要更新DNSPOD的记录就行了

**Comment by XIU2** [comment]
@892947707 

用在第三方网站用 CNAME 接入 Cloudflare CDN，然后在其他的域名解析网站（如 DNSPOD）去指定自选 IP。

不过我在 DNSPOD 没有域名（连账号都没注册），网上似乎已经有人写过**使用 API 自动更新 DNSPOD  域名解析记录的脚本**了。

**Comment by youtside** [comment]
很有用啊 host方式不portable

**Comment by 18030600277** [comment]
You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard

免费的域名，，用不了这个API

**Comment by vistaspl** [comment]
华为云应该怎样用，给了三个API
User Name,Access Key Id,Secret Access Key

**Comment by XIU2** [comment]
@vistaspl 

你可以看看这个：https://github.com/XIU2/CloudflareSpeedTest/discussions/56

**Comment by linkala** [comment]
「在第三方网站用 CNAME 接入 Cloudflare CDN，然后在其他的域名解析网站（如 DNSPOD）去指定自选 IP」大佬能否实现自动化脚本，定时去执行直接第三方解析最快的API，小弟可以提供DNSPOD子账号，供大佬测试～

**Comment by starxing22** [comment]
> 这个得出的最快ip，直接就填在域名的A记录里面，然后cdn代理又为真开启。那我域名本身对应的ip，应该是我服务器的ip，这样就没法用了。
cfst_ddns.conf里最后一行PROXIED=true改成PROXIED=false就可以了

**Comment by beer-on-ice** [comment]
大佬，怎么批量更新啊，有很多cfworkers

**Comment by XIU2** [comment]
> 大佬，怎么批量更新啊，有很多cfworkers

@beer-on-ice  多复制几个脚本中的 curl 代码呗，如果是在同一个根域名下，那么只需要改改域名就行了。

**Comment by beer-on-ice** [comment]
> > 大佬，怎么批量更新啊，有很多cfworkers
> 
> @beer-on-ice 多复制几个脚本中的 curl 代码呗，如果是在同一个根域名下，那么只需要改改域名就行了。

嗯嗯成

**Comment by jiangbeth** [comment]
Success'':false,errors'':((code'':10000,message'':Authentication error))    这种如何解决呢，令牌和ID准确无误

**Comment by themdeee** [comment]
> ## # 更新域名解析记录
> 即修改指定子域名的解析记录信息。
> 
> > **注意**：以下的**命令都是一个整体**，修改后要**一起粘贴、运行**，`\` 和 `^` 符号是命令分行用的，这样写方便大家理解。
> 
> ### ## Linux 系统
> ```shell
> curl -X PUT "https://api.cloudflare.com/client/v4/zones/域名ID/dns_records/解析记录ID" \
> -H "X-Auth-Email: 账号邮箱" \
> -H "X-Auth-Key: 前面获取的 API 令牌" \
> -H "Content-Type: application/json" \
> --data '{"type":"A","name":"xxx.yyy.zzz","content":"最快 IP","ttl":1,"proxied":true}'
> 
> # 如果你只需要更新该域名解析记录中单独 “一个” 信息（上面那个只能同时设置域名解析记录的所有信息），那么可以改成这样：
> 
> curl -X PATCH "https://api.cloudflare.com/client/v4/zones/域名ID/dns_records/解析记录ID" \
> -H "X-Auth-Email: 账号邮箱" \
> -H "X-Auth-Key: 前面获取的 API 令牌" \
> -H "Content-Type: application/json" \
> --data '{"content":"最快 IP"}'
> ```
> 
> ### ## Windows 系统
> ```shell
> "D:\Program Files\curl\bin\curl.exe" -X PUT "https://api.cloudflare.com/client/v4/zones/域名ID/dns_records/解析记录ID" ^
> -H "X-Auth-Email: 账号邮箱" ^
> -H "X-Auth-Key: 前面获取的 API 令牌" ^
> -H "Content-Type: application/json" ^
> --data "{\"type\":\"A\",\"name\":\"xxx.yyy.zzz\",\"content\":\"最快 IP\",\"ttl\":1,\"proxied\":true}"
> 
> # 如果你只需要更新该域名解析记录中单独 “一个” 信息（上面那个只能同时设置域名解析记录的所有信息），那么可以改成这样：
> 
> "D:\Program Files\curl\bin\curl.exe" -X PATCH "https://api.cloudflare.com/client/v4/zones/域名ID/dns_records/解析记录ID" ^
> -H "X-Auth-Email: 账号邮箱" ^
> -H "X-Auth-Key: 前面获取的 API 令牌" ^
> -H "Content-Type: application/json" ^
> --data "{\"content\":\"最快 IP\"}"
> ```
> 
> ## # 成功？失败？
> 运行命令后，会输出的一大串 JSON 内容，在其末尾看到，
> 
> * 如果写的是 `"success":true` 则说明**成功**。
> * 如果写的是 `"success":false` 则说明**失败**，原因会在后面的 `messages` 中说明。
> 
> ## # 关于命令中的 JSON 数据说明
> 指的就是更新解析记录命令中的这段内容：
> 
> ```json
> {"type":"A","name":"xxx.yyy.zzz","content":"最快 IP","ttl":1,"proxied":true}
> ```
> 
> 名称	示例	说明
> **type**	A	**解析记录类型**，如：A, AAAA, CNAME, HTTPS, TXT, SRV, LOC, MX, NS, SPF, CERT, DNSKEY...
> **name**	xxx.yyy.zzz	**完整的域名**，不能只写子域名名称，最长 255 个字符
> **content**	127.0.0.1	**解析 IP 地址**，IPv4、IPv6
> **ttl**	1	**解析记录生存时间**，值为 1 则是自动，单位：秒
> **proxied**	true	**是否走 CDN 代理**，是：true，否：false
> > 来自：https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record

使用win11 powershell
好像要把
--data "{\"type\":\"A\",\"name\":\"xxx.yyy.zzz\",\"content\":\"最快 IP\",\"ttl\":1,\"proxied\":true}"
改成
--data '{\"type\":\"A\",\"name\":\"xxx.yyy.zzz\",\"content\":\"最快 IP\",\"ttl\":1,\"proxied\":true}'

**Comment by 2069692020** [comment]
大佬是否可以解析到阿里云

**Comment by tvrohd** [comment]
这个有用配合paopao dns,不要太好用,可以直接本地cname,自动更新cname后的那个域名,这样本地的IP也更新了
paopao DNS可以 这样   xxx.com@@@123.xxx.com     自动更新123.xxx.com的ip 就等于更新了xxx.com

**Comment by aihoom** [comment]
按照步骤来了 但是重定向太多

**Comment by erdcy** [comment]
Linux自动更新的脚本在哪个压缩包里啊，找了好久没找到
