### ISSUE TITLE
是否可以将这个项目作为库引入第三方的软件呢？ 还是说只能以软件调用的方式来使用？

### ISSUE THREAD

**Issue by fireinrain** [XIU2/CloudflareSpeedTest#416]
### 功能需求

在其他的go项目中 引入该模块 就可以获得使用该模块的功能

### 预期目标

能够被其他三方模块引用

**Comment by XIU2** [comment]
你想要可以自行实现，但我不会做这种功能，一方面是改动太大，另一方面则是这不是我的目标，这软件就是我拿来自用的。

**Comment by fireinrain** [comment]
> 你想要可以自行实现，但我不会做这种功能，一方面是改动太大，另一方面则是这不是我的目标，这软件就是我拿来自用的。

好的 谢谢回复。

**Comment by fireinrain** [comment]
谢谢大佬的开发，目前基于你的这个工具，我在此基础上搞了一个cf-speedtester 的sdk 可以集成到其他的golang project,
地址: https://github.com/fireinrain/cf-speedtester
