### ISSUE TITLE
ipv6测速始终是0.00MB/s

### ISSUE THREAD

**Issue by catninelife** [XIU2/CloudflareSpeedTest#417]
### 问题描述

我已经自建了套CF的ipv6文件下载，可以直接访问。 软件使用参数 -url http://xxx/100M.zip 
但是最终结果所有节点速度都是 0.00

### 软件版本

v2.2.4

### 附加截图

![Snipaste_2023-08-01_17-57-39](https://github.com/XIU2/CloudflareSpeedTest/assets/49945708/a0c8a3ad-fba3-4e60-8089-7b9ff0cf5ee0)

**Comment by catninelife** [comment]
Sorry没有仔细阅读说明。加上 -tp 80搞定了

**Comment by XIU2** [comment]
@fredericky123 题主的原因是他使用的下载测速地址是 HTTP 的，而 CloudflareST 的默认测速端口是 443（也就是 HTTPS 的），所以才需要在运行参数里加上 `-tp 80` 手动指定测速端口为 HTTP 对应的 80 端口才能正常测速。

如果你用的下载测速地址是 HTTPS 的，那么你和题主的测速0的原因显然是不同的，应该是其他原因导致的。

**Comment by fredericky123** [comment]
感谢感谢 我访问的是HTTPS 确实不是这个问题了
