### ISSUE TITLE
使用参数httping和n 1000参数时，可用ip数量为0

### ISSUE THREAD

**Issue by YangZhenxun** [XIU2/CloudflareSpeedTest#418]
### 问题描述

 莫名其妙的，也许跟 #296 有关？
使用参数见下图，在android termux上使用。
 ~~（我是小学生，若问题不好，望见谅！）~~
不在使用httping参数时是正常的，但是因为~~作死~~，所以就试了一下httping模式，结果就这样了......

### 软件版本

2.2.4

### 附加截图

![Screenshot_2023-08-03-07-51-20-94](https://github.com/XIU2/CloudflareSpeedTest/assets/109320759/39560ce8-00a2-4ff6-8263-082644396bde)

**Comment by XIU2** [comment]
HTTP Ping 容易被判定为端口扫描这种恶意行为（本质是一样的），所以被 Cloudflare、运营商 限制也不稀奇。

**Comment by YangZhenxun** [comment]
可以了，谢谢！

**Comment by XIU2** [comment]
CloudflareST 的 HTTPing 延迟测速，其实就和 Curl 的下面参数组合原理是完全一样的只获取头部信息。

```
curl -I --resolve "测速地址的域名:443:IP" https://下载测速地址

# 示例：
curl -I --resolve "music.googleapis.asia:443:172.67.172.187" https://music.googleapis.asia/mp3/sibai.mp3
```

**Comment by YangZhenxun** [comment]
谢谢，了解了。
