### ISSUE TITLE
指定参数没生效啊，比如端口tp和dn参数

### ISSUE THREAD

**Issue by httpsColon** [XIU2/CloudflareSpeedTest#423]
### 问题描述

指定参数没生效啊，比如端口和dn参数

### 软件版本

2.2.4

### 附加截图

![image](https://github.com/XIU2/CloudflareSpeedTest/assets/102579986/17d5dd7e-c10f-425b-886c-586a9933dbc1)

**Comment by XIU2** [comment]
前面的 `tl 200` 少加了 1 个 ` - `杠。
