### ISSUE TITLE
Mac端运行问题

### ISSUE THREAD

**Issue by FrostLunar** [XIU2/CloudflareSpeedTest#425]
### 问题描述

Mac端上面运行命令行反馈没有权限permission denied:；
使用sudo后又显示sudo: ./CloudflareST: command not found；
各种指令找不到权限不够，最后只能再次下载使用windows主机运行win端才行

### 软件版本

2.2.4

**Comment by XIU2** [comment]
#381

**Comment by FrostLunar** [comment]
好的，已经按照帖子所述方法解决，谢谢了
