### ISSUE TITLE
提供关闭进度条输出的开关

### ISSUE THREAD

**Issue by huberyhe** [XIU2/CloudflareSpeedTest#428]
### 功能需求

我做了一个服务调用了CloudflareST，现在服务的日志文件里存在大量进度条信息，看起来比较乱，能否提供关闭进度条的参数

### 预期目标

提供一个安静模式的参数，如`-s`，加上这个参数后不展示进度条信息。

**Comment by XIU2** [comment]
你是怎么记录日志的？

我尝试用 ` > ` 来讲内容输出到指定文件，无论是在 Windows 还是 Linux 系统下，`log.txt` 文件内都不包含进度条。
```
./CloudflareST > log.txt
```

**Comment by huberyhe** [comment]
> 你是怎么记录日志的？
> 
> 我尝试用 `>` 来将内容输出到指定文件，无论是在 Windows 还是 Linux 系统下，`log.txt` 文件内都不包含进度条。
> 
> ```
> ./CloudflareST > log.txt
> 
> CloudflareST.exe > log.txt
> ```
> 
> > 你这个需求，似乎过于冷门。。。

php的system函数调用的。我明白了，进度条是打印到错误输出的，我调用时带上`2>/dev/null`就好了。多谢指教
