### ISSUE TITLE
下载速度过小时以`B`, `KB`为单位

### ISSUE THREAD

**Issue by My-Responsitories** [XIU2/CloudflareSpeedTest#429]
### 功能需求

部分网站最大的文件只是100kb+的js文件, 但下载速度仍需要10s+(e.g. `github.githubassets.com`), 导致测速结果一堆`0.01MB`, `0.00MB`凑在一起. 能否在下载速度过小时以`B`, `KB`为单位

### 预期目标

在下载速度过小时以`B`, `KB`为单位
```go
var units = [...]string{"", "K", "M", "G", "T"}

func Speed2String(size float64) string {
	unitIndex := 0
	for size > 1024 {
		size /= 1024
		unitIndex++
	}
	return fmt.Sprintf("%.2f %sB/s", size, units[unitIndex])
}
```
导出的csv文件可以直接以`B/s`为单位

**Comment by XIU2** [comment]
所以为啥你要选这么小的文件来下载测速？

如果只是为了测试 IP 是否可用于某个地址，那么请使用 HTTPing 模式。
