### ISSUE TITLE
添加 mipsel 架构版本（路由器）

### ISSUE THREAD

**Issue by LetMeDecay** [XIU2/CloudflareSpeedTest#43]
https://zhuanlan.zhihu.com/p/57163950
参考这个编译，可以增加mips版本的执行文件

我这里测试红米ac2100可以跑这个`小端架构`编译出来的版本
[![ySp7m6.png](https://s3.ax1x.com/2021/01/28/ySp7m6.png)](https://imgchr.com/i/ySp7m6)

`大端架构`的会报错
[![yS99nP.png](https://s3.ax1x.com/2021/01/28/yS99nP.png)](https://imgchr.com/i/yS99nP)

`./CloudflareSpeedTest: line 1: syntax error: unexpected "("`

**Comment by XIU2** [comment]
我编译出来了，但是我没办法测试（没有设备），你测试以下看看，如果没有问题了，我就添加到 Releases 中。
[CloudflareSpeedTest.zip](https://github.com/XIU2/CloudflareSpeedTest/files/5881635/CloudflareSpeedTest.zip)

**Comment by LetMeDecay** [comment]
跑是能跑了，但是速度都很低，只有0.07
默认参数跑的

**Comment by XIU2** [comment]
可能是性能问题？
下载测速时，都是将文件缓存到内存中丢弃，我没有设备，也无法测试。

**Comment by LetMeDecay** [comment]
我明天起来研究下吧

**Comment by LetMeDecay** [comment]
应该就是下载测速的问题，多线程只影响测试延迟吧

**Comment by XIU2** [comment]
不是很清楚，我没有设备，也无法测试。

**Comment by shyperwang** [comment]
> 我编译出来了，但是我没办法测试（没有设备），你测试一下看看，如果没有问题了，我就添加到 Releases 中。
> [CloudflareSpeedTest.zip](https://github.com/XIU2/CloudflareSpeedTest/files/5881635/CloudflareSpeedTest.zip)

用mipsle的应该不少，可能大家都是用你的脚本在软路由或者是windows平台的多，像newifi D2这一类都是mipsle结构，我用你现在的脚本就会出现“./CloudflareSpeedTest: line 1: syntax error: unexpected "("”，你这个编译是基于mips还是mipsle的？

**Comment by XIU2** [comment]
@shyperwang 

我选的是 mipsle 。

**Comment by shyperwang** [comment]
> @shyperwang
> 
> 我选的是 mipsle 。

好的，我今晚就去试一下，等我消息

**Comment by shyperwang** [comment]
@XIU2 晚上试了下，1.4.8代码在newifi d2上可用，这样看其他的路由器应该都没有问题。不过有下面几点要确认一下:
1..sh脚本我没有试，路由器改hosts效果不知道怎么样，尤其是openwrt下很多人用ddns和smartdns，建议考虑其他方法接管dns
2.cloudflarest的整体测试速度比较慢，我没有调测速时间，可能和这个有关，建议可以考虑把默认时间缩短
3.不清楚为什么输出是csv格式，可以转换成txt格式，只是建议，可能是习惯了
4.可能和运营商有关系，我测速下来只有一个ip速度还可以，但是我测这个ip/24网段的时候还是只有这一个ip可以，其他几乎为0，感觉有点怪怪的

**Comment by XIU2** [comment]
1. 自动更新 Hosts 的脚本只是附带了，只能算功能扩展，我能做的很有限，这类额外功能扩展过于**个性化**，适合大家自己折腾。
2. 这个信息太少无法判断，至于测速时间，是有**相关参数可以调整**的，没必要因此而调整整体默认参数的值。
3. 输出结果文件的内容格式是可以用表格软件打开的，你也可以输出为 1.txt（`-o "1.txt"`），文件名无所谓的，而 `.csv` 也能直接用记事本或 `cat` 查看，完全没影响。
4. 你提供的信息并不能说明什么，可能需要你在路由器和电脑上分别测速来分析问题。

**Comment by shyperwang** [comment]
对的，脚本的基本功能有就是很大的帮助，剩下的就要个人按需去摸索了，不可能全部都满足

**Comment by XIU2** [comment]
mipsle 架构的已经添加到 releases 了，先看看大家用了之后有没有问题，到时候信息丰富了也好排查。

这个 Issues 就先关闭了，有问题可以继续回复。

**Comment by LetMeDecay** [comment]
路由器速度跑不起来，我看了下CPU和内存，基本都没占太高
![image](https://user-images.githubusercontent.com/7452372/107044511-5d071a00-67ff-11eb-9167-ca93a7fe6231.png)


![image](https://user-images.githubusercontent.com/7452372/107044621-89bb3180-67ff-11eb-86f1-f72c15f01717.png)
跑完只有3m/s


同一时间点电脑可以跑40m/s
![image](https://user-images.githubusercontent.com/7452372/107044674-98094d80-67ff-11eb-8955-b5d8423175c6.png)

**Comment by XIU2** [comment]
@LetMeDecay 

我也不清楚是什么原因，完全没有头绪，最重要的是我没有设备就**只能靠猜**，而无法一点点实验排查。

**Comment by XIU2** [comment]
@LetMeDecay 

你需要对同一个 IP 在两个平台下多次对比测速结果。
写入单个 IP 到文件中，然后对其单独测速：

``` bash
echo "104.18.219.160/32" > 1.txt

./CloudflareST -f 1.txt
```

**Comment by LetMeDecay** [comment]
差不多刚好10倍 😂
![image](https://user-images.githubusercontent.com/7452372/107055055-d1e05100-680b-11eb-8137-fcc900a2c774.png)
就挺奇怪的

**Comment by XIU2** [comment]
@LetMeDecay 

那你将以下内容写入 hosts 文件：
```
104.18.219.160 cf.xiu2.xyz
```

然后直连下载该文件（默认的下载测速地址）看看速度如何：
```
wget https://cf.xiu2.xyz/Github/CloudflareSpeedTest.png
```

**Comment by shyperwang** [comment]
> @LetMeDecay
> 
> 那你将以下内容写入 hosts 文件：
> 
> ```
> 104.18.219.160 cf.xiu2.xyz
> ```
> 
> 然后直连下载该文件（默认的下载测速地址）看看速度如何：
> 
> ```
> wget https://cf.xiu2.xyz/Github/CloudflareSpeedTest.png
> ```

您的测速地址有通过cf没？

**Comment by XIU2** [comment]
@shyperwang 

这不是废话么...

**Comment by XIU2** [comment]
@LetMeDecay 

之所以让你用 wget 下载测速一遍。

是因为我前几天在给另一个人远程协助的时候，发现他的软路由上运行的测速结果基本**高于 10MB/s**，而电脑上**最高的也才 3MB/s**，差距非常大，起初那个人怀疑是 CloudflareST 问题。

然后我就把同一个 IP 写入 Hosts 文件（指向 cf.xiu2.xyz，即**手动模拟下载测速**），然后在软路由上和电脑上分别直连软件用的下载测速地址，发现 **CloudflareST 测速结果实际上是准确**的，手动测速和软件测速结果**相差不大**。

这就很奇怪了，是其他的什么原因导致了 软路由 和 电脑上 访问同一个 IP 的速度差异。

虽然我也没找到原因。。。

**Comment by LetMeDecay** [comment]
![image](https://user-images.githubusercontent.com/7452372/107109229-6c2aae00-6879-11eb-994a-54ab80a48f7e.png)
应该就是单纯mips平台的问题，这东西还是不适合在路由器上跑
有条件直接软路由或者电脑跑完之后ssh改路由器hosts好点

**Comment by XIU2** [comment]
@LetMeDecay 

也就是说，确实是**同一个 IP** 在路由器上和电脑上**速度不一致**？

和我前面远程协助那个例子一样，CloudflareST 测速结果是准的，速度差异是其他原因导致的。

**Comment by shyperwang** [comment]
> ![image](https://user-images.githubusercontent.com/7452372/107109229-6c2aae00-6879-11eb-994a-54ab80a48f7e.png)
> 应该就是单纯mips平台的问题，这东西还是不适合在路由器上跑
> 有条件直接软路由或者电脑跑完之后ssh改路由器hosts好点

你测试的路由是旁路由还是主路由？

**Comment by LetMeDecay** [comment]
@shyperwang 主路由，但是配置一般。红米ac2100 mt7621a的cpu

**Comment by XIU2** [comment]
@LetMeDecay 

我觉得和配置关系不大，如果是配置影响 CloudflareST 测速结果的话，那直连下载测速文件应该是正常速度的。

**Comment by pengkaiwei** [comment]
> @shyperwang 主路由，但是配置一般。红米ac2100 mt7621a的cpu

通用的mt7621 k2p padavan 速度也是很低
开始下载测速（下载速度下限：0.00 MB/s，下载测速数量：10，下载测速队列：10）：
10 / 10 [------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
104.18.15.87      4       4       0.00    183.30    0.15           
104.17.227.197    4       4       0.00    184.26    0.14           
172.67.65.166     4       4       0.00    181.67    0.10           
104.21.91.126     4       4       0.00    183.84    0.09

**Comment by ixinshang** [comment]
艾玛，我以为就只有我一个人遇到这样的情况！
XIAOMI R3G一样
