### ISSUE TITLE
下载速度全部为0

### ISSUE THREAD

**Issue by wysnuaa** [XIU2/CloudflareSpeedTest#431]
### 问题描述

下载速度全部为0，看issuse之前已經有人提過了呀，有点奇怪

### 软件版本

2.2.4

### 附加截图

![image](https://github.com/XIU2/CloudflareSpeedTest/assets/17687768/05819e38-e651-4db3-870f-c178173b1dec)

**Comment by XIU2** [comment]
该问题和软件自身无关，是下载测速地址或 IP 或其他的问题导致的。
