### ISSUE TITLE
dalao，有没有办法能将筛选出的IP，使用域名服务商提供的API（如DNSPod）解析到不同线路以达到加速的效果？

### ISSUE THREAD

**Issue by kokorobeats** [XIU2/CloudflareSpeedTest#44]
dalao，有没有办法能让程序每天定时自动运行并自动将筛选出的IP，使用域名服务商提供的API（如DNSPod）解析到不同线路以达到加速的效果？我搭了个Xray-WebSocket+TLS的代理，并套了Cloudflare的cdn，想要每天能自动更换自定义ip

**Comment by XIU2** [comment]
可以是可以，但是需要在**域名解析网站有域名**，才能测试 API 并写教程或脚本。

就像我前几天写的那个 Cloudflare CDN API 自动更新域名解析记录一样。

**Comment by kokorobeats** [comment]
那dalao能写一个吗.......我就想在DNSPod里能自动替换...........我这边有什么能帮到dalao的吗..........

**Comment by XIU2** [comment]
我没有托管在 DNSPod 的域名，所以我没办法去测试其 API，并写相关教程/脚本。

**Comment by KimiBear** [comment]
DNSPod，需求还是满多的，希望博主测试一下

**Comment by ren-CAT** [comment]
dalao我已经在iOS上测速成功了

**Comment by CrazyBoyFeng** [comment]
我写的脚本可以用 #56

**Comment by bbcbbcbbc-abc** [comment]
我一看 实名认证， 马上就放弃了。。。

**Comment by cxw620** [comment]
华为云的DNS可以做到分区域解析而且免费
