### ISSUE TITLE
UDP testing

### ISSUE THREAD

**Issue by asterriya** [XIU2/CloudflareSpeedTest#45]
Right now tool allow scanning only TCP ipv4 so is it possible to add additionally for testing UDP ipv4?

**Comment by XIU2** [comment]
UDP is different from TCP.

The UDP test requires both parties to install the corresponding software to receive and return messages.

**Comment by XIU2** [comment]
In addition, CDN currently does not support UDP protocol data transmission.

**Comment by asterriya** [comment]
Which one parties I need to install on win7 x64 or is there some way to get udp version testing? If it's not support UDP so need to remove mention of tcp ipv4

**Comment by XIU2** [comment]
The TCP in the output of the software means that the software is testing the delay with the TCP protocol.
In addition to the TCP protocol, there is also the common ICMP protocol (ping 1.1.1.1).

**Comment by XIU2** [comment]
If you want to perform a UDP delay speed test to the Cloudflare CDN server, you need the Cloudflare CDN server to receive and return UDP messages.

But obviously, Cloudflare CDN does not support this.

**Comment by XIU2** [comment]
It depends on your ISP's speed limit purpose.

Sorry, I can't help you.
