### ISSUE TITLE
相同网络环境下 Windows CMD 和 WSL 中出现不同的结果

### ISSUE THREAD

**Issue by Cunoe** [XIU2/CloudflareSpeedTest#450]
### 问题描述

很奇怪，之后也ping了一次 WSL 中输出的结果，能看出 Windows 这端正常 ping 是没问题的

### 软件版本

v2.2.4

### 附加截图

![image](https://github.com/XIU2/CloudflareSpeedTest/assets/90205430/1134b4eb-0f27-428a-90da-25065a55b047)

**Comment by charSLee013** [comment]
如果说是运气问题不知道你信不信（笑

从结果上看，因为两次都是选择随机IP的，window 主要集中在 `188.114.0.0/16`和`141.101.0.0/16` 这两个域内

而WSL 则集中在 `104.25.0.0/16` 这个域内，所得出的结果自然也就是不一样

**Comment by Cunoe** [comment]
> 如果说是运气问题不知道你信不信（笑
> 
> 从结果上看，因为两次都是选择随机IP的，window 主要集中在 `188.114.0.0/16`和`141.101.0.0/16` 这两个域内
> 
> 而WSL 则集中在 `104.25.0.0/16` 这个域内，所得出的结果自然也就是不一样

好吧，今天用 `--allip` 测试了一下，确实是你提到的 `运气原因` ，感谢你的帮助
