### ISSUE TITLE
建将优选的ip保留，下一次筛选，优先从这些保留ip中测速

### ISSUE THREAD

**Issue by iyzh635428** [XIU2/CloudflareSpeedTest#454]
### 功能需求

我设置每天优选一次ip，程序每次都要从一个大的地址范围中随机选择ip测速，我遇到的情况是，优选出5个符合条件的ip，经常要花费一个多小时，甚至有些时候，几个小时优选不出5个符合条件的ip。有时候，昨天还好好的，今天就无法访问，为什么？因为程序还没优选完，昨天优选出来的ip全都被丢掉了。这样子，效率就不是很高。
很多时候，这些已经测速过，优选出来的ip，很长一段时间，都能在我这个地区的网络保持稳定高速，那每次优选，都将上一次优选出来的ip抛弃，是极大的浪费。
所以，建议改进一下！将已测速，优选出来的ip，保留在“优选地址库”，每次优选，优先从“优选地址库”中测速，这样子应该可以大大提升优选效率。同时只需做到少量的“优选地址库”更新，失速的ip即时抛弃，高速的ip即时更新。

### 预期目标

每次优选，我希望5分钟之内完成，而不是现在的1个多小时，甚至是几个小时。

**Comment by XIU2** [comment]
像这种能用外置脚本实现的功能，是不会添加进软件里的，否则会很麻烦且不灵活，也无法根据需求随意改动。
