### ISSUE TITLE
只要使用 -httping模式，就会被cloudflare封ip

### ISSUE THREAD

**Issue by plmsuper8** [XIU2/CloudflareSpeedTest#460]
### 问题描述

使用-httping后，可用ip直接为0，即便切回tcp模式，一段时间内也不可用。

本地ip连CF的CDN都会连不上，而换个ip（手机流量）就可以连，证明确实是被CF封了ip。

如果无法修复，希望能更明确的标注该模式潜在危险，只是我这边是完全不能用的。

### 软件版本

v2.2.4

**Comment by XIU2** [comment]
HTTPing 使用说明中写的很清楚：

https://github.com/XIU2/CloudflareSpeedTest#-httping
