### ISSUE TITLE
蓝奏云下载的win_amd64版本运行后会后台安装360安全卫士，我想知道是否是作者有意为之？

### ISSUE THREAD

**Issue by DeeepMind** [XIU2/CloudflareSpeedTest#465]
### 问题描述

蓝奏云下载的win_amd64版本运行后会后台安装360安全卫士，我想知道是否是作者有意为之？

### 软件版本

CloudflareST_windows_amd64.zip 2.4MB

**Comment by XIU2** [comment]
离谱，确定清楚原因了再发 Issues 。。。

**Comment by DeeepMind** [comment]
感谢作者回复，我重新检查后没有发现问题，该情况也没有再次复现，后面我会进一步排查出现的原因

**Comment by DeeepMind** [comment]
感谢作者回复，我重新检查后没有发现问题，该情况也没有再次复现，后面我会进一步排查出现的原因
