### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by ghzxs** [XIU2/CloudflareSpeedTest#466]
### 问题描述

按步骤无法运行
![IMG_0005](https://github.com/XIU2/CloudflareSpeedTest/assets/54847264/5c528372-2bc1-434d-98e6-649f2c479888)

### 软件版本

ios ish  V2.2.5

**Comment by XIU2** [comment]
这是 iSH 的问题，从某次更新后就这样了，这种问题我无法解决，你只能期待 iSH 解决掉该问题。 #321
