### ISSUE TITLE
在“开始下载测速”的过程没做完就自动停止

### ISSUE THREAD

**Issue by bobwang3** [XIU2/CloudflareSpeedTest#467]
### 问题描述

命令是这样写的 -url https://xxx/xx.zip -tl 250 -sl 10 -tlr 0.10 -f xxx.txt
开始延迟测速（模式tcp 端口443 范围0~250ms 丢包0.10），一切正常。
开始下载测速（下限10MB 数量10 队列158 ），这一步比较慢，有时做到4/10就结束了，箭头停在当中，-----→_________
下面会给出四五个测试出来的IP。有时候做到2/10就停了，每次都不一样

### 软件版本

v2.2.5

**Comment by XIU2** [comment]
https://github.com/XIU2/CloudflareSpeedTest#界面解释

这里解释的很清楚了，你去看看吧。
