### ISSUE TITLE
写出result.csv中文乱码

### ISSUE THREAD

**Issue by jwwsjlm** [XIU2/CloudflareSpeedTest#475]
### 问题描述

问题修复方案
`w.Write([]string{"\xEF\xBB\xBF"})`
写出BOM头即可

### 软件版本

2.2.5

### 附加截图

![QQ截图20231214235040](https://github.com/XIU2/CloudflareSpeedTest/assets/48446617/ab3ab286-c48f-489f-b8f9-7859ea9e69dc)

**Comment by XIU2** [comment]
#277
