### ISSUE TITLE
希望在ping测试完保存一次测试结果

### ISSUE THREAD

**Issue by siyuan797** [XIU2/CloudflareSpeedTest#477]
### 功能需求

希望在ping完保存一次测试结果，测速之后再保存一次测试结果

### 预期目标

比如花了很长时间测ping，但在测速时的发现url无法访问，只需修改测速url之后用已经测试了ping的ip重新测速，不需要再重新ping

**Comment by XIU2** [comment]
像这种能用其他方式（如脚本）实现的功能，我是不会添加到软件里的。
我将这个软件做成 命令行程序 的愿意之一就是为了这个，可以通过脚本自由组合实现各种需求。

****

你就先仅延迟测速一次（`-dd` 禁用下载测速），输出结果到 `-o 1.txt` 文件内
然后从 `1.txt` 文件中提取第一列的 IP 地址，再次开始延迟测速（不指定延迟条件，并且把测试次数调成 `-t 1`，这样就大大减少时间了）及下载测速。

你的需求和 #470 比较类似，这种简单的脚本需求，你可以问下 ChatGPT。
