### ISSUE TITLE
所在路径有叹号会导致 bat 启动失败

### ISSUE THREAD

**Issue by yfdyh000** [XIU2/CloudflareSpeedTest#491]
### 问题描述

工具放在例如 `!2024` 文件夹中，启动cfst_hosts.bat
获取管理员权限的vbs会给出找不到路径的提示。观察可见，`"%~s0"`路径中的`!`字符消失。

经测，脚本中的`Setlocal Enabledelayedexpansion`改为`Setlocal disabledelayedexpansion`后，问题消失。

### 软件版本

v2.2.5

### 附加截图

cfst_hosts.bat

[Content]
Windows 找不到文件 '[省略]\2024\cfst_hosts.bat'。请确定文件名是否正确后，再试一次。

**Comment by XIU2** [comment]
那你就改个文件夹名字呗。
你把这个脚本扩展选项关了，脚本中部分代码可能会出问题（时间太长我也记不清了）。
