### ISSUE TITLE
点开页面后迅速闪退

### ISSUE THREAD

**Issue by moqianbing** [XIU2/CloudflareSpeedTest#493]
### 问题描述

ipv4部分我是自己找的，然后点开cloudflarest.exe后开了就秒闪退开了就秒闪退，我是win11系统，没有弹出任何提示就没了。

### 软件版本

2.2.5

**Comment by XIU2** [comment]
多半是你写的 IP 格式的问题。

因为 CloudflareST 是命令行程序，因此报错后就会直接终止运行，导致你看不到错误信息（直接双击运行的情况下），想要看到错误信息就要改成通过命令行方式运行，参考 [# CMD 带参数运行 CloudflareST](https://github.com/XIU2/CloudflareSpeedTest#-cmd-带参数运行-cloudflarest)

> 如果是因为 IP 格式错误导致的，那么报错内容大概是 `...ParseCIDR err invalid CIDR address...`

这样即使软件报错终止，或者你手动终止，依然可以看到 CloudflareST 输出的任何信息，因为 CMD 本身还在运行。
