### ISSUE TITLE
新版本的测速功能好像没用

### ISSUE THREAD

**Issue by ritech** [XIU2/CloudflareSpeedTest#5]
所有的速度都是0.00

**Comment by ritech** [comment]
Error 1102 2020-11-06 14:28:13 UTC
Worker exceeded resource limits

**Comment by ritech** [comment]
没问题了，自己的ip问题

**Comment by XIU2** [comment]
该情况和 #2 一样。  

都是官方测速地址超出上限（我不清楚是所有人共享上限还是每个 IP 单独计算，我需要蹲点看看）。

**Comment by XIU2** [comment]
@ritech  我自己带头写了一些可以用下载测速的地址，你可以去 Issues #6 里看看。
