### ISSUE TITLE
手机开热点导致软件运行不起来，再次连接WIFI也没有用

### ISSUE THREAD

**Issue by M15055510Xx** [XIU2/CloudflareSpeedTest#502]
### 问题描述

手机开热点导致软件运行不起来，再次连接WIFI也没有用

### 软件版本

v2.2.4，v2.2.5

### 附加截图

![Uploading Snipaste_2024-02-29_15-12-19.png…]()

**Comment by M15055510Xx** [comment]
![Snipaste_2024-02-29_15-12-19](https://github.com/XIU2/CloudflareSpeedTest/assets/75202334/317fffc4-233f-4159-8abb-53c1c01f8bc1)

**Comment by M15055510Xx** [comment]
虽然可以再重新开一个程序，但是好奇怪啊

**Comment by XIU2** [comment]
你有没有注意到，你截图里的 `CloudflareST.exe` 右边显示的文件大小是 `0 KB`，这显然不正常，因此你遇到的问题并不是 CloudflareST 程序本身的导致的，而是因为其他问题导致 `CloudflareST.exe` 文件出现了问题（比如被篡改被删除什么的各种可能的原因，具体就需要你自行排查了）

> “虽然可以再重新开一个程序”

不清楚你描述的具体情况是什么，但这显然也侧面印证了 CloudflareST 程序本身是可以在你电脑上正常运行的，只是你截图里的那个 `CloudflareST.exe` 文件是有问题的。

**Comment by M15055510Xx** [comment]
手机流量给电脑开热点

**Comment by XIU2** [comment]
和 WIFI、热点 什么的显然无关，可能是你在搞这些的时候做了什么，或者系统、其他软件干了什么导致的。
难道连个 WIFI 还会导致 `CloudflareST.exe` 文件变成 `0 KB`？

**Comment by M15055510Xx** [comment]
![image](https://github.com/XIU2/CloudflareSpeedTest/assets/75202334/63de5da2-7976-4338-b5e3-b2d3c39b5f23)
又好了，电脑关机开机后又好了，手机热点正常了，我不知道怎么回事，可能上午连了一个失败的WIFI。
