### ISSUE TITLE
MAC 系统下如果遇到提示：open ip.txt: no such file or directory 

### ISSUE THREAD

**Issue by jingzhaohui** [XIU2/CloudflareSpeedTest#503]
### 问题描述

放进目录下还是提示：open ip.txt: no such file or directory 
![WX20240308-104350@2x](https://github.com/XIU2/CloudflareSpeedTest/assets/153159765/0c44b406-5994-4c07-ba98-d137cc230acc)

### 软件版本

V2rayU 4.1.0

**Comment by XIU2** [comment]
你要先进入 CloudflareST 及 ip.txt 所在目录下，再去运行 CloudflareST，这样才是相对路径，CloudflareST 的工作目录就是其自身所在的目录，才会找到 ip.txt 文件。
你用绝对路径去运行 CloudflareST（也就是 /xxx/xxx/CloudflareST 这样带着绝对路径），这是 CloudflareST 的工作目录是根目录，自然找不到根目录 /ip.txt 文件了。

这属于命令行操作的常识，建议你了解一下。

MAC 下命令行操作方式和 Linux 基本一样，你看我写的 Linux 操作步骤是怎么干的（你已经下载了，所以下载解压步骤可以省略了）：https://github.com/XIU2/CloudflareSpeedTest#下载运行
