### ISSUE TITLE
mac反代ip

### ISSUE THREAD

**Issue by hhhr1** [XIU2/CloudflareSpeedTest#505]
### 问题描述

你好博主！可以出个mac的反代ip教程视频吗？看win的实在是学不会啊
不会操作命令 实在抱歉。或者有同胞可以帮忙解答下吗？ 
卡在了测速筛选ip那里

### 软件版本

无

**Comment by XIU2** [comment]
#504 请勿滥用 Issues 。
另外，本软件和 "反代ip" 没啥关系。
