### ISSUE TITLE
速度限制单位 MB/s 太粗且不支持小数

### ISSUE THREAD

**Issue by CrazyBoyFeng** [XIU2/CloudflareSpeedTest#51]
https://github.com/XIU2/CloudflareSpeedTest/blob/873200de803334aeb6ae2b985c95f1a43e9058d6/main.go#L45

该参数使用的`IntVar`只能是整数，而不支持小数。如果以 MB/s 为单位进行速度筛选，那么只能设置 1MB/s 2MB/s 这样。这个单位太粗糙了，无法对 1.5MB/s 和 0.5MB/s 进行精细筛选。因此建议让该参数支持小数`Float64Var`，或者将该参数单位变更为`KB/s`。

**Comment by XIU2** [comment]
因为我觉得这个意义不大，下载速度下限没有必要过于精细的筛选。

- 如果你与 Cloudflare CDN **速度友好**，轻松能跑 几十MB/s，那么下载速度下限只需要写 10、20 这样就行了。
- 如果你与 Cloudflare CDN **速度不友好**，只能跑个 几MB/s，那么下载速度下限写的过于精细也没什么用，**差距太小**了。

> **注意**：对同一个 IP 进行多次测速，会发现**每次得到的结果都不一样**，存在上下波动，有时候波动还很大，这就是**受各种因素影响后**的测速结果，这是正常的，所以精细化测速**意义不大**。

**Comment by CrazyBoyFeng** [comment]
我估计因为你用的是联通所以才会有几十MB到几MB的差距。联通的出口众多，自动的负载均衡（限速）不是很积极，所以不同线路差异巨大。  
而电信，只要是家宽，即使是千兆入户，在线路没有特别优化，服务器没买电信带宽的情况下（CF的国际节点肯定都没买针对国内的专门的优化线路），基本上都是1MB左右上下浮动。带宽小是因为CN1本来出口就不大，建成之后就一直没扩容。电信用户用户又多，因此平分的出口带宽就小。还因为电信有积极的负载均衡，不同的线路会遵循一样的限速策略。加上BGP，导致电信不同线路的利用率差不多。所以不同线路之间的差异不是很大。不过差异毕竟还是有的。会有1.xMB/s的，也会有0.0xMB/s的。可能不用的人觉得差异不大，但是对于电信用户来说，1000KB/s和10KB/s的差异还是蛮大的，跨两个数量级呢。

给电信用户的提示：某个时段测速很快的不代表它一直很快，只是因为这个时段这个IP所在线路空闲了而已，过段时间就会被电信QOS过来，调整的周期也不好说。所以电信用户要经常测经常换。  
联通好像也会调整线路，但是没有电信这么积极。所以联通用户如果发觉变慢了也要换。

**Comment by XIU2** [comment]
这依然无法改变我的想法，我个人还是感觉**差别太小**。

**精细的过滤适用于较低的速度**，例如 **0.X MB/s、1.X MB/s** 这样的，如果超过 4、5 MB/s 时，用户就用不上精细的过滤条件了。

而如果测速结果**最快的也才 1.X MB/s**，那应该考虑的是放弃 Cloudflare CDN 了。。。

****

我这边联通是白天是无论什么时候都能轻松跑个 20~39 MB/s 的平均速度。  

晚上也大概是 5~19 MB/s 的平均速度。

而 Cloudflare CDN 默认分配的给我的 IP 测速结果大都在 50 KB/s~5 MB/s 之间浮动。

**Comment by CrazyBoyFeng** [comment]
这样吧，我给改成`Float64Var`，不影响以前的用法，而想要用小数的就可以用小数。

> 而如果测速结果最快的也才 1.X MB/s，那应该考虑的是放弃 Cloudflare CDN 了。。。

电信不是cf限速，而是国际出口限速。只要服务器没买优化线路，连什么都很慢。毫不夸张，1.xMB/s真的是加速了。这里有篇文介绍[各运营商出口带宽](https://zhuanlan.zhihu.com/p/64467370)：

> 163 网(民用电信宽带都属于这种)，是全中国用户数量最大，访问国际网络体验最差的线路，国外网站用浏览器打开需要转圈等上个十来分钟，PC、PS、Xbox 连接外服下载极慢(十几 kb / 秒)，玩游戏卡顿(丢包)等现象屡见不鲜；

为什么不选择直连CN2的服务器呢？当然是因为贵。而且如果觉得1.xMB/s够用的话，确实也没必要去买CN2啊。
其次，使用CDN当然是因为安全了，可以隐藏IP。流量特征也不明显。IP不好用了还能直接换。

**Comment by XIU2** [comment]
对于个性化的需求，可以自行修改并编译使用（或者 Fork 也是可以的）。

**Comment by XIU2** [comment]
那我就先关闭该 Issues 了。

目前只有你一个人提出这类需求，如果以后再有人提出类似需求，我会考虑的 👌。

**Comment by CrazyBoyFeng** [comment]
我已改好，提交了pr。
（你审核pr通过或拒绝会自动关闭这个issue。）

**Comment by XIU2** [comment]
已经合并，并发布 v1.4.8 版本了。
