### ISSUE TITLE
能不能新增一个可以登录ChatGPT的专属优选方式？

### ISSUE THREAD

**Issue by xingyeyeyeye** [XIU2/CloudflareSpeedTest#520]
### 功能需求

新增一个可以登录ChatGPT的专属优选方式

### 预期目标

普通的优选方式优选出来的不能登录ChatGPT，希望可以增加一个ChatGPT专属优选。

**Comment by XIU2** [comment]
部分 Cloudflare CDN 网站可能限制了只能通过特定 IP 访问（一般就是这些网站域名解析的那些 IP）

这种网站是无法随意指定 CF IP 访问的。

至于 OpenAI 是不是这样我不清楚，不过，可以肯定的是不存在 专属优选方式 这种玩意，要么能，要么不能，没有其他选项。
