### ISSUE TITLE
获取到cloudflare最快的ip后使用问题

### ISSUE THREAD

**Issue by kejunsun** [XIU2/CloudflareSpeedTest#521]
### 问题描述

我的cloudflare warp无法连接了，请问下我获取的这个最快ip该怎么使用，才能让warp丝滑连接上

### 软件版本

v1.1

**Comment by XIU2** [comment]
项目介绍里都写了，为什么都不看？

> [!NOTE]
> 注意！本软件仅适用于网站，**不支持给使用 UDP 协议的 Cloudflare WARP 优选 IP**，具体见：[#392](https://github.com/XIU2/CloudflareSpeedTest/discussions/392)
