### ISSUE TITLE
6.27突发，多位置多运营无法连接

### ISSUE THREAD

**Issue by Wodksk** [XIU2/CloudflareSpeedTest#522]
### 问题描述

使用了新的ip和公开ip皆无法使用其他工具（也是ip优选）全都超时

### 软件版本

2.2.5

**Comment by XIU2** [comment]
什么意思？没看懂

**Comment by XIU2** [comment]
Issues 只用来反馈 CloudflareST 软件自身问题，其他问题请使用 Discussions
