### ISSUE TITLE
下载的Linux_arm版本的CloudflareST可执行文件是x86架构的

### ISSUE THREAD

**Issue by ByxwStar** [XIU2/CloudflareSpeedTest#526]
### 问题描述

下载的Linux_arm版本的CloudflareST可执行文件是x86架构的，
按照教程：wget -N https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_linux_amd64.tar.gz
解压后是x86架构
![image](https://github.com/user-attachments/assets/93a60842-a491-4d44-9870-dd05f4e278b7)

### 软件版本

什么软件

**Comment by XIU2** [comment]
你有没有看你到底在说什么？。。。

你说的这个文件地址，你仔细看，这就是 amd64 的啊，amd64 就是 x86-64 架构的。

你要下载的是 arm64 的吧？你下错文件了。

我写的 Linux 使用示例仅仅是示例，里面也写了 `（自行根据需求替换 URL 中 [版本号] 和 [文件名]）`，其他架构的系统需要自行修改 URL 里的文件名，我只是用最常见的 x86-64 做了个示例。

**Comment by ByxwStar** [comment]
噢噢噢噢，不好意思看错了，看成是arm的了，原来是amd
