### ISSUE TITLE
另一种方式匹配指定地区

### ISSUE THREAD

**Issue by shulng** [XIU2/CloudflareSpeedTest#527]
### 功能需求

可以通过将IP传 (f'http://ip-api.com/json/{ip}')
来获取(country或countryCode)指定地区

### 预期目标

可以通过将IP传 (f'http://ip-api.com/json/{ip}')
来获取(country或countryCode)指定地区

**Comment by cnthunder** [comment]
不是有三字码么

**Comment by muyiacc** [comment]
三字码测出来不太对头，假使使用韩国或者日本的三字码，测出来的也不是这两个地区的ip

**Comment by muyiacc** [comment]
> 不是有三字码么

三字码测出来不太对头，假使使用韩国或者日本的三字码，测出来的也不是这两个地区的ip

**Comment by XIU2** [comment]
@muyiacc Anycast IP 是不能通过这些在线 IP 地址位置查询来判断其实际位置的。

只有机场三字码才能表明实际路由给你的节点服务器物理位置。

[# 匹配指定地区(colo 机场三字码)](https://github.com/XIU2/CloudflareSpeedTest#-%E5%8C%B9%E9%85%8D%E6%8C%87%E5%AE%9A%E5%9C%B0%E5%8C%BAcolo-%E6%9C%BA%E5%9C%BA%E4%B8%89%E5%AD%97%E7%A0%81)
