### ISSUE TITLE
能否扩大使用范围，可在配置文件 或 命令行参数上 自定义DNS,  而非仅限 Cloudflare ?

### ISSUE THREAD

**Issue by Waiman-app** [XIU2/CloudflareSpeedTest#532]
### 功能需求

能不能用在其它DNS上？  

现在有一个SaaS网站，有时超慢，我需要在CMD中 nslookup xxx.cdn.dnsv1.com , 得到几个IP,  再去ping 这些IP, 把最快的 更新到hosts文件中去

作者能否对软件做些扩展， 比如 参数 可 自定DNS,  "CloudflareST.exe  -dns  xxx.cdn.dnsv1.com"  ,  得到ip 列表， 自动测试延时和丢包率，自动选择最佳IP, 更新到hosts.      

### 预期目标

update software for add  private dns feature.

**Comment by XIU2** [comment]
谁跟你说 CloudflareST 只能测速 Cloudflare CDN 的了？
你说的这个需求和 CloudflareST 无关，CloudflareST 也没有限制你不能这样做啊。

想要得到某个域名的所有解析 IP，只在你设备上是不行的，只有在全球各个地区去解析该域名才行，所以你只需要找个在线 Ping 的网站（要支持国外的），如： https://ping.sx/dig 就可以得到该域名的绝大部分解析 IP 了。
然后搭配我的 [Ping.Sx 增强](https://github.com/XIU2/UserScript) 油猴脚本，可以 `一键复制所有 IP`，然后就写入到文件中，让 CloudflareST 延迟测速这些 IP 即可（CloudflareST 默认的下载测速地址是 Cloudflare CDN 的，因此只能测速 Cloudflare，如果要下载测速其他网站/CDN，那就要你自己去寻找相应的下载测速地址）。

我平时给一些速度慢的国外网站优选 IP，都是这样操作的，现在我家网络里各个能优选的主流 CDN 都会返回最快的 IP，包括一些我常用的网站也都会返回最快的 IP。
