### ISSUE TITLE
使用cfst_hosts.bat后 无法访问网络

### ISSUE THREAD

**Issue by ssomoss** [XIU2/CloudflareSpeedTest#534]
### 问题描述

使用cfst_hosts.bat后 无法访问网络 

提示网络配置器没有启动TCP/IP服务

使用批处理命令修复
chcp 65001
@echo off
echo 正在重置网络设置...

echo 重置 Winsock 目录...
netsh winsock reset
echo 完成。

echo 重置 IP 配置...
netsh int ip reset
echo 完成。

echo 释放当前 IP 配置...
ipconfig /release
echo 完成。

echo 更新 IP 配置...
ipconfig /renew
echo 完成。

echo 重置 WinHTTP 代理设置...
netsh winhttp reset proxy

echo 清除 DNS 缓存...
ipconfig /flushdns

echo 重置 IP 设置...
netsh int ip reset resetlog.txt

echo 重启网络服务...
net stop dnscache
net start dnscache
echo 完成。

echo 所有操作已完成，请重新启动计算机。
pause

网络断断续续可用 ping各种网站 提示一般故障

![22222](https://github.com/user-attachments/assets/195041c8-bb7e-47a4-b14b-97fc26b45367)

### 软件版本

CloudflareST_windows_amd64.zip v2.2.5

**Comment by XIU2** [comment]
你确定用的是我的脚本？

你这输出的内容我脚本里可没有。。。
