### ISSUE TITLE
能否跳过延迟测速，直接进入下载测速

### ISSUE THREAD

**Issue by AllCheeks** [XIU2/CloudflareSpeedTest#537]
### 问题描述

RT，谢谢。

### 软件版本

master

**Comment by XIU2** [comment]
目前不行，因为正常来说，先延迟测速的目的是为了过滤掉不可用的 IP，再对剩下可用的 IP 进行下载测速。

你这个需求，我能想到的适用环境是，**你已知你要下载测速的 IP 都是可用的，且数量不会太多**，就想着省略掉延迟测速的步骤。

不过这种需求还是偏小众一些，毕竟延迟测速比下载测速要快多了。
如果你确实是我描述的这种情况，我建议你直接调低延迟测速次数 `-t 1`，这样就能大幅缩短延迟测速的时间。

但如果你要测速的 IP 可用性是未知的，且数量很多，那么这种情况下，你省略了延迟测速步骤并不能节省多少时间，因为 IP 可用性未知的原因，这会导致下载测速得到满意结果的时间也变得更加不可控，如果倒霉可能开头就遇到大量超时不可用的 IP，这会大幅增加测速时间。
而且因为不是从最低延迟的 IP 开始下载测速的，因此遇到速度更快 IP 的概率也会更低（延迟低不一定速度快，但是更容易遇到速度快的，因为延迟越高，影响速度的因素就越多）。

**Comment by AllCheeks** [comment]
在对 IP 进行测速时，我发现对方阻止了 TCPPing，但我也不想使用HTTP测速。我知道该 IP 是可用的，但我发现如果不通过延迟测速，就无法进行下一步的下载测速。我尝试过添加 -allping 参数，但没有效果。我的需求确实比较小众，但我可以自己解决，感谢你的回复。

**Comment by XIU2** [comment]
禁止了 TCPing ？这确实很罕见。。。
