### ISSUE TITLE
第一次使用，请先将 Hosts 中所有 Cloudflare CDN IP 统一改为一个 IP。

### ISSUE THREAD

**Issue by zhaozhejun** [XIU2/CloudflareSpeedTest#54]
第一次使用，请先将 Hosts 中所有 Cloudflare CDN IP 统一改为一个 IP。
没太理解这是什么意思，，
1.1.1.1  yan.shengzi221.tk  
我host原本这样写的，那就是第一次输1.1.1.1  然后就可以吗还是？

**Comment by XIU2** [comment]
脚本每次运行后，都会替换对应的 IP。
这样做是为了让脚本知道要替换哪个 IP。

你这种情况，填写 `1.1.1.1` 就行了。
脚本运行测速后，就会把 hosts 中的所有 1.1.1.1 替换为新的最快 IP。

**Comment by zhaozhejun** [comment]
![捕获](https://user-images.githubusercontent.com/22097252/106870486-23a1b200-670c-11eb-8176-7d22a18a33d8.PNG)
还有个问题，默认扫出来的，出来结果后 为什么 路由器上所有ip都ping不通呢？

**Comment by XIU2** [comment]
你的路由器上面是不是有代理？

你这个延迟代表 CloudflareST 测速过程走代理了，否则不可能是这么低的延迟。

**Comment by zhaozhejun** [comment]
![捕获111](https://user-images.githubusercontent.com/22097252/106871473-3cf72e00-670d-11eb-9859-8551963a0f00.PNG)
 是有代理，但是奇怪的是ping都不通，是开了hello world，但节点是台湾的ip，没任何转换

**Comment by XIU2** [comment]
如果你的代理用的是 Cloudflare CDN，那么就会出现测速结果不可用的情况（等于说是让 Cloudflare 去测速 Cloudflare）。

**Comment by XIU2** [comment]
你需要先关闭代理工具，再去运行 CloudflareST，得到的测速结果才是正确且可用的（对于下载测速为 0.00 的说明不可用）。

**Comment by XIU2** [comment]
如果没有其他问题，就先关闭该 Issues 了。当然有问题的话，还可以继续回复。

如果觉得 CloudflareST 对你有帮助，就点个 ⭐ 鼓励一下吧！
