### ISSUE TITLE
多加个cfdns自动同步功能呗

### ISSUE THREAD

**Issue by star8618** [XIU2/CloudflareSpeedTest#541]
### 功能需求

多加个cfdns自动同步功能呗，密钥域名什么的从key获取，获取最快的ip同步下，同步前先删除原有的ip地址，再同步！

### 预期目标

加个参数-cf 默认关闭 如果开启-cf y ,保存文件后就执行cfdns同步功能。这样就全自动了

**Comment by XIU2** [comment]
这种能用外部脚本实现的功能，是不会考虑添加到 CloudflareST 内的。

**Comment by star8618** [comment]
厉害了我的哥，搞成全自动，加个web，支持定时以及变量配置，那就牛逼了
