### ISSUE TITLE
新手小白，问下cfcolo的问题

### ISSUE THREAD

**Issue by pink8888** [XIU2/CloudflareSpeedTest#542]
### 问题描述

我选择的都是日本的机场三字码，在终端输入./CloudflareST -cfcolo FUK,OKA,KIX,NRT后，在result.csv中输出的为什么都是美国或者加拿大的ip，应该怎么才能获得cloudflare服务器的日本ip

### 软件版本

v2.2.5

**Comment by XIU2** [comment]
> `在result.csv中输出的为什么都是美国或者加拿大的ip`

你是如何判断这些 IP 是美国/加拿大的？

如果你是通过各种网页查 IP 的归属地的话，那是不准的，因为 Cloudflare 这些 IP 都是 Anycast 的，每个 IP 的实际位置不是固定的，不同时间，不同地区访问的位置都是不一样的。

你可以这样访问该 IP，就能看到你访问该 IP 时实际访问的 colo 是什么地区的了。
```
http://Cloudflare的IP/cdn-cgi/trace
```
