### ISSUE TITLE
增加超时选项

### ISSUE THREAD

**Issue by 362227** [XIU2/CloudflareSpeedTest#547]
### 功能需求

增加超时选项

### 预期目标

我设置的是筛选出5个ip的时候，在下载测速的时候经常卡在2/5、3/5这样，几小时都走不动（很可能永远卡住了），能不能增加超时选项，比如10分钟，10分钟后就强行停止，只筛选出这2、3个ip

**Comment by XIU2** [comment]
软件本身就有：
```
    -dt 10
        下载测速时间；单个 IP 下载测速最长时间，不能太短；(默认 10 秒)
```

你说的这个问题，不是因为某几个 IP 卡住了，而是因为这时 CloudflareST 正在挨个下载测速，只有找到满足条件的 IP 后（下载速度 -sl 参数条件），这个进度条才会动，你看着进度条不动好像卡住了一样，但实际上只是 CloudflareST 一直找不到满足条件的 IP。

不信你把只单拎 5 IP，对这 5 个 IP 进行测速，不设置下载速度条件，你看是否就正常很快就完成了？

这其实就已经代表，你设置的下载速度条件对你来说已经高于实际了，你需要适当调低预期。

你需要详细看一下 [#界面解释](https://github.com/XIU2/CloudflareSpeedTest#%E7%95%8C%E9%9D%A2%E8%A7%A3%E9%87%8A)

**Comment by 362227** [comment]
但也需要这个功能，我已经设置很低的预期了，但确实有时候有1、2个可以用，有时候一直是0，有时候很快就有5个了，感觉增加超时设置就灵活多了

**Comment by 362227** [comment]
我刚刚设置最低速度1M/s，卡在4/5了，低速ip对我没有意义

**Comment by XIU2** [comment]
我不都说了吗？

```
    -dt 10
        下载测速时间；单个 IP 下载测速最长时间，不能太短；(默认 10 秒)
```

这个就是超时时间，也就是每个 IP 进行下载测速时最多测速这么长时间，时间到了不管什么情况都会终止，这不叫超时叫什么？

****

你只能测速得到低速的 IP，这和 CloudflareST 无关，这是你网络环境的原因，CloudflareST 只是个测速的软件，把测速结果告诉你罢了，是什么样就是什么样。

**Comment by 362227** [comment]
你没有理解我的意思。不是说怪CloudflareST，是确实可以优化，针对的是网络不稳定的用户 
我的意思是总的超时时间，不是单个ip的超时时间。就是因为网络波动太大，所以需要这样的超时时间，这样反而是可以解决问题。我举例子，鉴于我的网络，我是每30分钟就扫一次ip，比如某一次扫出900个ip，测速的时候可能第1-第100个中有3个ip满足条件，但101-900没有，那我只需要这3个就可以了，101-900如果一直测速，可能要几小时。也可能过了一会儿，扫出的ip没一个满足条件的，那不可能一直测速。也可能过了2小时，扫出的ip有几十个满足条件的ip，如果这时候设置的预期很低很低，那就更亏了。设置超时确实是最优的方法了。

**Comment by XIU2** [comment]
我觉得，如果你连接 Cloudflare CDN 的速度这么差了，也就没必要搞优选了，选来选去都是那样，区别不大。

如果连保底 1MB/s 都没有，那代表你不适合使用 Cloudflare CDN 了，不更换运营商的情况下，这基本是无解的。

**Comment by 362227** [comment]
其实每次运行CloudflareST前杀掉还是可以的，能用还是能用的，估计极少人像我这样的

**Comment by XIU2** [comment]
有两种人使用 CloudflareST 不需要下载测速，一种是随便测速都能很快的，一种无论怎么测速都很慢的。

就像我平时压根都不下载测速（直接 `-dd` 禁用了），只需要延迟测速随便挑个延迟低的就行了（当然为了避免不稳定，我是这些年长期测速慢慢筛选出适合自己的 IP 段，直接在这几个 IP 段里测速，数量更少，测速时间很短，质量也很稳定）

**Comment by 362227** [comment]
其实我可以用的，我需要高速下载东西（其实也就偶尔下下，大多数时候是闲置的，但随时需要），设置超时确实是最优的方法，现在我运行前杀掉也可以用。还是谢谢你
