### ISSUE TITLE
下载速度慢

### ISSUE THREAD

**Issue by 573648656** [XIU2/CloudflareSpeedTest#548]
### 问题描述

测试后下载速度不会超过1M，望告知解决方法，能不能把exe换成bat，我们就可以自己修改一些参数，谢谢！

### 软件版本

v2.2.5

### 附加截图

![image](https://github.com/user-attachments/assets/1c8db056-7ffd-4a9f-ba8a-110f282e0135)

**Comment by XIU2** [comment]
。。。
速度快慢取决于你的网络环境连接 Cloudflare CDN 的质量。

CloudflareST 只是一个测速工具，网络质量是什么样，测速结果就是什么样，速度快慢和 CloudflareST 本身无关。

#547 里我解释的很清楚，你自己看。

****

软件运行参数见：
[# 进阶使用](https://github.com/XIU2/CloudflareSpeedTest#-%E8%BF%9B%E9%98%B6%E4%BD%BF%E7%94%A8)

[# CMD 带参数运行 CloudflareST](https://github.com/XIU2/CloudflareSpeedTest#-cmd-%E5%B8%A6%E5%8F%82%E6%95%B0%E8%BF%90%E8%A1%8C-cloudflarest)

[# Windows 快捷方式带参数运行 CloudflareST](https://github.com/XIU2/CloudflareSpeedTest#-windows-%E5%BF%AB%E6%8D%B7%E6%96%B9%E5%BC%8F%E5%B8%A6%E5%8F%82%E6%95%B0%E8%BF%90%E8%A1%8C-cloudflarest)
