### ISSUE TITLE
报错：“找不到D:\osurunas”求解

### ISSUE THREAD

**Issue by Ruiuiuiuiuiui** [XIU2/CloudflareSpeedTest#550]
### 问题描述

如图

### 软件版本

我试过的几个版本都不行

### 附加截图

![QQ截图20241013160147](https://github.com/user-attachments/assets/26ab2f84-aa0e-49c5-9780-beb1e1f3de63)

**Comment by XIU2** [comment]
这是你的使用方式有问题，你这是在 CMD 里指定参数来运行 CloudflareST 的吗？

你把你的整个操作过程描述一下，我才能知道你具体是哪里操作有误。

**Comment by Ruiuiuiuiuiui** [comment]
应该是我自己的方式有误我是直接双击"1osu请打开此文件.bat"打开的
现在试试用cmd打开，谢谢提醒！
&nbsp;


3467915835
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月13日(星期天) 下午4:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XIU2/CloudflareSpeedTest] 报错：“找不到D:\osurunas”求解 (Issue #550)














 
这是你的使用方式有问题，你这是在 CMD 里指定参数来运行 CloudflareST 的吗？
 
你把你的整个操作过程描述一下，我才能知道你具体是哪里操作有误。

**Comment by XIU2** [comment]
我发布的版本中，压缩包里是没有 `1osu请打开此文件.bat` 之类文件的，你确定是从我这里下载的？

**Comment by Ruiuiuiuiuiui** [comment]
![QQ截图20241013162132](https://github.com/user-attachments/assets/a5debcdd-7eaf-4aa3-ba1e-01ad77239cb4)
确实不是从您这下载的，用的是一个up发的，如图。可能我下了两个版本，一个是改过的版本，一个是您这边的原项目，然后解压后把他们混到同一个文件夹并合并了，从而导致报错。
视频链接：【教你加速osu的网络】 https://www.bilibili.com/video/BV1WM4y1w71u/?share_source=copy_web

**Comment by XIU2** [comment]
既然是这个人写的脚本，运行脚本出现问题，那你应该问这个人。。
