### ISSUE TITLE
请问能不能做一个测速的安卓app？

### ISSUE THREAD

**Issue by Davidasx** [XIU2/CloudflareSpeedTest#552]
### 功能需求

感觉中国移动网络比较特殊，连接Cloudflare慢，请问能不能做一个安卓app？
主要是我的代理节点运行在Cloudflare CDN后面（防止被墙），手机上延迟比电脑上大的多，所以需要看看能不能提速。

### 预期目标

一个安卓app，不用做得太好看，就是一键测速等功能

**Comment by Davidasx** [comment]
看到了那个Termux方案，但是不是很方便，求app

**Comment by Davidasx** [comment]
看到了termux方案，但是不是特别方便，求独立app

**Comment by Davidasx** [comment]
还有一种办法是做网页版，网页版可以使用Javascript进行测速。

**Comment by XIU2** [comment]
既然你看到了 termux 方案教程，那么该教程开头写的 安卓 APP 链接为啥看不到。。。

**Comment by Davidasx** [comment]
纯眼瞎……犯唐了，抱歉
