### ISSUE TITLE
奇怪，连着测试两次怎么都不一样

### ISSUE THREAD

**Issue by Davidasx** [XIU2/CloudflareSpeedTest#554]
### 问题描述

连着测试两次（间隔五分钟不到），发现结果完全变了，似乎之前最好的节点，现在都没有进入前10.
网络环境应该没有任何变化。

### 软件版本

XIU2/CloudflareSpeedTest v2.2.5

### 附加截图

![image](https://github.com/user-attachments/assets/a6da4f7e-01aa-41fa-a39f-d29d395a5703)
![image](https://github.com/user-attachments/assets/8a3f2033-d880-4d5e-b218-72d1e20d7cf2)

**Comment by XIU2** [comment]
很常见的情况，这是正常的。

而且你的两次测速结果并没有什么问题，还是集中在那几个 IP 段中。

**Comment by Davidasx** [comment]
所以其实是很多个非常接近的结果，最后再带上随机性是吗？

**Comment by XIU2** [comment]
默认测速 IP 是随机的（IPv4 最后一段，IPv6 则是后面每段），测速结果当然也因此是随机的。
