### ISSUE TITLE
似乎TCPping线程数限制不生效

### ISSUE THREAD

**Issue by hogum** [XIU2/CloudflareSpeedTest#556]
### 问题描述

用./CloudflareST -n 1照样会跑满CPU且测试进度不是一个个跳的，但是用./CloudflareST -httping -n 1就正常了

### 软件版本

linux arm64最新版

**Comment by hogum** [comment]
且TCP模式下Clash内不会显示Process，Http则正常分流

**Comment by XIU2** [comment]
我这边测试正常，无法复现你描述的情况。

我也是专门在 linux arm64 系统环境下测试的。

> 至于 Clash 相关问题，这不属于 CloudflareST 的问题，是你分流规则等配置的问题。

**Comment by hogum** [comment]
好吧，补充一下环境看看有没有类似的案例
Lean-LEDE R24.11.11 / LuCI openwrt-23.05 branch git-24.320.56478-5e65af3
AX1800Pro路由器 qualcommax/ipq60xx
内核版本6.1.112

Clash那个主要是我在yacd面板里都看不到默认参数下对应连接的Process Name，但用了-httping就可以看得到了
