### ISSUE TITLE
README.md 存在错误拼写

### ISSUE THREAD

**Issue by NuoFang6** [XIU2/CloudflareSpeedTest#558]
### 问题描述

![image](https://github.com/user-attachments/assets/8170af45-4d31-4eb5-b0d8-af1047b90a57)
可能误将`-tll` 错误拼写为了`-ttl`
如果使用参数-ttl会报错：`flag provided but not defined: -ttl`

### 软件版本

master Commit 1d9d742

### 附加截图

![image](https://github.com/user-attachments/assets/fd1000a2-2cf8-4bac-8d25-bba4afa0446e)

**Comment by XIU2** [comment]
OK，感谢捉虫，已修正~
