### ISSUE TITLE
-p parameter doesn't work

### ISSUE THREAD

**Issue by AliM1988** [XIU2/CloudflareSpeedTest#562]
### 问题描述

-p parameter doesn't work. It still shows max 10 results.

### 软件版本

2.2.5

**Comment by XIU2** [comment]
There is no problem with this parameter. If you specify `-p 20` but still display 10, then there is a high probability that the speed measurement results are only 10, so only 10 can be displayed.

**Comment by AliM1988** [comment]
You are right. The default number of speed test is default 10. I must change it with `-dn xx` parameter or entirely disable speed test by `-dd` parameter. So, `-p xx` parameter works fine.
