### ISSUE TITLE
mp里面遇到的问题

### ISSUE THREAD

**Issue by hk906801250** [XIU2/CloudflareSpeedTest#564]
### 问题描述

mp里面运行了这个cf优选ip后日志里面是这样的？为什么获取不到正常的优选ip？

### 软件版本

2.2.5

### 附加截图

![QQ20241222-153500](https://github.com/user-attachments/assets/d29d6c7c-65d6-41b4-9d7a-3029fc942453)
![QQ20241222-153626](https://github.com/user-attachments/assets/aa1006be-d9bb-4ea7-aec0-4441d30de864)
![QQ20241222-153731](https://github.com/user-attachments/assets/a922052a-1f9f-4509-a3fc-de4049cfca09)

**Comment by XIU2** [comment]
我没用过这玩意，你截图里的这个虽然调用的是 CloudflareST，但这玩意并不是我写的，建议你联系该作者。

**Comment by hk906801250** [comment]
感谢大佬，还是按照你的教程搞定了!!!就是最下面这个.sh这个要用ssh进去给他权限让他运行一次就好了

**Comment by hk906801250** [comment]
感谢大佬，还是按照你的教程搞定了!!!

**Comment by XIU2** [comment]
好吧，虽然我不懂具体什么情况，但问题解决了就好~

**Comment by hk906801250** [comment]
![Q](https://github.com/user-attachments/assets/177c535c-fd8f-459f-a221-6080957ffad5)
大佬我的问题是这个.sh不知道为什么没有权限，要用ssh进去给它权限按照你这个教程搞定的，感谢哈！！！
