### ISSUE TITLE
能增加个结果按照移动最快IP，电信最快IP的筛选吗？

### ISSUE THREAD

**Issue by klmahua** [XIU2/CloudflareSpeedTest#63]
能增加个结果按照移动最快IP，电信最快IP的筛选吗？因为用户来至不同网络，当前测试的时候网络只是当前网络最快

**Comment by XIU2** [comment]
无法实现，因为同一个 IP 在不同地区、不同运营商的网络环境下测速，结果也是不同的。

**Comment by XIU2** [comment]
因此，只有在当前网络环境下测速获得的最快 IP，才能确定适合于当前网络。

**Comment by klmahua** [comment]
那想要测试移动最快IP，要把当前网络切换到移动？要测电信最快要把当前网络切换到电信。。。。可实际测试的时候只有一个电信网络。。。没有什么好的办法测试出不同网络最快的IP吗？？如果可以的话，，，能分流解析的

**Comment by XIU2** [comment]
在电信网络下测速就只能获得对电信友好的 IP，在移动网络下就只能获得移动友好的 IP。

而且即使是同一个运营商，不同地区也会存在差异。

除非你有三个不同运营商网络的设备或服务器（单线）去分别测速，才会得到你想要的结果。

****

说实话，我这个工具可能并不适合使用 Cloudflare CDN 的站长去提速网站，因为局限性太多。

毕竟我一开始写 CloudflareST 的目的只是为了扫描出最快 IP，然后**改 Hosts** 来提高使用 Cloudflare CDN 的**网站访问速度**。

**Comment by XIU2** [comment]
如果没有其他问题的话，我就先关闭该 Issues 了。当然有问题的话，还可以继续回复。

另外，如果觉得 CloudflareST 对你有帮助，就点个 ⭐ 鼓励一下吧！
