### ISSUE TITLE
我有一个骚想法，希望帮我实现。 

### ISSUE THREAD

**Issue by huanx9** [XIU2/CloudflareSpeedTest#65]
一般情况下 我们用  -f "ip.txt"

我们能不能采用两种方式

一种使用本地的ip.txt 

然后我们再给他一个参数   用来 https:// ..../ip.txt

**Comment by XIU2** [comment]
什么情况下才会需要通过 URL 来读取 Cloudflare IP 段？

****

Cloudflare CDN IP 段是固定的，基本上不会变动了。大家使用时：
- _要么是用全 IP 段的 ip.txt 文件（默认）。_
- _要么就是单独针对某些 IP 或 IP 段进行测速（将这些 IP 段写入到 xxx.txt 文件中使用）。_

无论是哪种，都不太需要使用 URL 来读入要测速的 IP 段。
