### ISSUE TITLE
有办法一直持续运行吗，一直运行到响应有100ms内的IP结束？

### ISSUE THREAD

**Issue by klmahua** [XIU2/CloudflareSpeedTest#67]
有办法一直持续运行吗，一直运行到响应有100ms内的IP结束？每次运行都找不到理想的响应IP，一直点运行。。。偶尔出现一个差不多的IP，太费时间了

**Comment by XIU2** [comment]
这种需求应该用脚本去解决，即循环运行 CloudflareST，每次运行完毕后分析结果（运行时加上 100ms 延迟条件）。
只需要判断一下 `result.csv` 文件中结果数量就知道是否找到 100ms 以下的 IP 了。

> 因为在设定延迟条件后，如果没有找到 100ms 以下的 IP，软件会直接输出完整测速结果（上千条结果），反之则只会输出满足条件的 IP（默认 20 条，即 `-dn XX` 参数）。

> 不过现在软件不支持单独使用 [延迟测速上限] 条件（如果只考虑延迟的话，只延迟测速明显速度更快、效率更高），后续我可能需要优化一下。

**Comment by XIU2** [comment]
刚刚更新了下，现在支持仅指定 [平均延迟上限] 条件了。

详细使用方法可以看：https://github.com/XIU2/CloudflareSpeedTest#-自定义下载测速地址

**Comment by klmahua** [comment]
非常感谢大佬的更新，。，，立马去体验一下

**Comment by XIU2** [comment]
如果你只考虑延迟的话，就可以只指定 `-tl 100` 参数，并禁用下载测速 `-dd`，这样延迟测速速度更快，效率更高。

**Comment by XIU2** [comment]
如果你对编写脚本不熟的话，也可以把需求详细的告诉我，我来帮你写个 Linux 或 Windows 脚本。

**Comment by klmahua** [comment]
感谢大佬帮忙
windows写法
100ms延迟内的写法是不是：  CloudflareST.exe -tl 100
100ms延迟并禁用下载的写法是不是：CloudflareST.exe -tl 100 -dd

**Comment by klmahua** [comment]
晕，测了延迟100ms内的IP，得到的数量竟然是零

**Comment by XIU2** [comment]
这种情况很正常，就像你一开始说的 **“偶尔出现一个差不多的IP”** ，这本身就意味着在大部分时间下，难以找到低于 100ms 的 IP。

****

就像我的联通，平时能找到的延迟最低的 IP 也才 130ms+，除了前段时间我意外扫到一个略带丢包的日本 CDN 节点 IP 段：
```
172.64.228.0/24
```
这个延迟有时候能低至 60ms+，有时候能高至 150ms+，主要是这个日本 IP 段线路用的是 NTT 垃圾线路，质量太差了，一到高峰期就拥堵...

**Comment by klmahua** [comment]
是啊这个日本IP我也偶尔扫到过。。当天延迟的确很低100ms内，。，第二天就突然飙升到300ms以外了。。还丢包严重。。。。大佬能分享下香港的IP段吗

**Comment by XIU2** [comment]
我也不清楚香港 IP 段是哪个，因为 Cloudflare CDN 用了 **Anycast** 技术，因此任何 IP 对应的物理位置都可能随时变动。

就像这个日本 IP 也不是永久的，指不定哪天就变了。

****

你去找香港 IP 是没用的，因为软件默认已经对 Cloudflare CDN 的**所有 IP 段**进行延迟测速了，既然你没有找到延迟更低的 IP，那很显然你链接香港 IP 的网络质量不行（绕道），这种情况下你去找香港 IP，得到的也是绕道后的高延迟。

> 绕道指的是：你 -> 美国/新加坡/日本 -> 香港 -> 美国/新加坡/日本 -> 你
> 你要链接香港，还需要去**美国/新加坡/日本**跑一圈，这样你还不如**直接使用**美国/新加坡/日本，这样反而**延迟更低，更稳定**。

而如果你是移动用户，那么在直连香港 IP 的情况下，直接运行 CloudflareST 就能获得香港 IP 了，完全不需要任何操作。

> 一般来说移动大都是直连 Cloudflare CDN 香港节点的，但不排除部分地区运营商走不同的出口路线。

**Comment by klmahua** [comment]
哦。。。。好的感谢大佬耐心的帮助

**Comment by XIU2** [comment]
如果没有其他问题的话，我就先关闭该 Issues 了。当然有问题的话，还可以继续回复。

另外，如果觉得 CloudflareST 对你有帮助，就点个 ⭐ 鼓励一下吧！
