### ISSUE TITLE
English language

### ISSUE THREAD

**Issue by asterriya** [XIU2/CloudflareSpeedTest#68]
Need English Language for the interface, please. I'm not Chinese citizenship, and it's hard to use all the time Google Translate

**Comment by XIU2** [comment]
According to the statistics provided by Cloudflare CDN (`-url https://cf.xiu2.xyz/Github/CloudflareSpeedTest.png`), Chinese users account for **97.25%** of the global users currently using CloudflareST.

The development purpose of CloudflareST is because the default CDN IP assigned to Chinese users by Cloudflare CDN is not friendly, so some methods are needed to obtain the fastest IP.

My English level is very ordinary, so even if I want to add English language, I need to use Google Translate. . .

**Comment by CrazyBoyFeng** [comment]
Do you live in China? This software is used to optimize the speed of Chinese users accessing Cloudflare.

**Comment by asterriya** [comment]
> Do you live in China? This software is used to optimize the speed of Chinese users accessing Cloudflare.

No, I'm not. But living in Turkmenistan. Still looking the way how to bypass throttling. But this tool helping me to bypass only censorship.

**Comment by CrazyBoyFeng** [comment]
This tool is used to find the fastest Cloudflare CDN IP. Using this tool alone will not bypass the censorship. Maybe what you need are Shadowsocks, V2Ray, or Psiphon, Lantern, Tor...

**Comment by asterriya** [comment]
> This tool is used to find the fastest Cloudflare CDN IP. Using this tool alone will not bypass the censorship. Maybe what you need are Shadowsocks, V2Ray, or Psiphon, Lantern, Tor...

I know about them and using it, but the main problem is to bypass throttling which isn't their main benefits at all.

**Comment by CrazyBoyFeng** [comment]
I didn't understand what you said, can you say it again with other words? Or in your native language, I can try to use a translator.

**Comment by hoseinnikkhah** [comment]
I will create an English fork of this tool, meanwhile you can use another forked tool I finalized some while ago. both tool are similar and offer nice features so an English version for such thing is a great idea.

**Comment by XIU2** [comment]
@hoseinnikkhah I've added instructions for manual compilation in README that might help you.
https://github.com/XIU2/CloudflareSpeedTest#手动编译

**Comment by hoseinnikkhah** [comment]
Thanks @XIU2 for the help, your README was really helpful, for now I released an alpha version for 64bit windows. feel free testing it, I will translate all script files later, they need a little more work except translation, seems like when I translate them into English .bat files won't open which is because of UTF-8 standard, there's an easy fix for this issue which I will apply it, for now I need a little rest :)

**Comment by XIU2** [comment]
@hoseinnikkhah 
I have added the repository address for this English language version in README.
https://github.com/XIU2/CloudflareSpeedTest#衍生项目

Also, the v2.3.3 I used in the manual compilation instructions is just an example, the latest version of CloudflareST is currently v2.2.2. In order to avoid user confusion, it is recommended to unify the version number.

****

Because I mainly use Windows system, I wrote a simple bat script for my convenience:

> When I update the version, I will first modify the value of the version variable at the beginning of the script, and then run the script.

> The first time you run the script, you don't need to create these folders, Golang will automatically create folders and write files at compile time, you just need to put all additional files (such as `ip.txt`) into each folder after compile is complete.

<details>
<summary><code><strong> Click to expand to view </strong></code></summary>

****

``` bat
@echo off

SET version=v2.2.2

CD ..

echo "CloudflareST_darwin_amd64..."
SET CGO_ENABLED=0
SET GOOS=darwin
SET GOARCH=amd64
go build -o Releases\CloudflareST_darwin_amd64\CloudflareST -ldflags "-s -w -X main.version=%version%"

echo "CloudflareST_darwin_arm64..."
SET CGO_ENABLED=0
SET GOOS=darwin
SET GOARCH=arm64
go build -o Releases\CloudflareST_darwin_arm64\CloudflareST -ldflags "-s -w -X main.version=%version%"

echo "CloudflareST_linux_386..."
SET CGO_ENABLED=0
SET GOOS=linux
SET GOARCH=386
go build -o Releases\CloudflareST_linux_386\CloudflareST -ldflags "-s -w -X main.version=%version%"

echo "CloudflareST_linux_amd64..."
SET CGO_ENABLED=0
SET GOOS=linux
SET GOARCH=amd64
go build -o Releases\CloudflareST_linux_amd64\CloudflareST -ldflags "-s -w -X main.version=%version%"

echo "CloudflareST_linux_arm64..."
SET CGO_ENABLED=0
SET GOOS=linux
SET GOARCH=arm64
go build -o Releases\CloudflareST_linux_arm64\CloudflareST -ldflags "-s -w -X main.version=%version%"

echo "CloudflareST_linux_armv5..."
SET CGO_ENABLED=0
SET GOOS=linux
SET GOARCH=arm
SET GOARM=5
go build -o Releases\CloudflareST_linux_armv5\CloudflareST -ldflags "-s -w -X main.version=%version%"

echo "CloudflareST_linux_armv6..."
SET CGO_ENABLED=0
SET GOOS=linux
SET GOARCH=arm
SET GOARM=6
go build -o Releases\CloudflareST_linux_armv6\CloudflareST -ldflags "-s -w -X main.version=%version%"

echo "CloudflareST_linux_armv7..."
SET CGO_ENABLED=0
SET GOOS=linux
SET GOARCH=arm
SET GOARM=7
go build -o Releases\CloudflareST_linux_armv7\CloudflareST -ldflags "-s -w -X main.version=%version%"

echo "CloudflareST_linux_mips..."
SET CGO_ENABLED=0
SET GOMIPS=softfloat
SET GOOS=linux
SET GOARCH=mips
go build -o Releases\CloudflareST_linux_mips\CloudflareST -ldflags "-s -w -X main.version=%version%"

echo "CloudflareST_linux_mips64..."
SET CGO_ENABLED=0
SET GOMIPS=softfloat
SET GOOS=linux
SET GOARCH=mips64
go build -o Releases\CloudflareST_linux_mips64\CloudflareST -ldflags "-s -w -X main.version=%version%"

echo "CloudflareST_linux_mipsle..."
SET CGO_ENABLED=0
SET GOMIPS=softfloat
SET GOOS=linux
SET GOARCH=mipsle
go build -o Releases\CloudflareST_linux_mipsle\CloudflareST -ldflags "-s -w -X main.version=%version%"


echo "CloudflareST_linux_mips64le..."
SET CGO_ENABLED=0
SET GOMIPS=softfloat
SET GOOS=linux
SET GOARCH=mips64le
go build -o Releases\CloudflareST_linux_mips64le\CloudflareST -ldflags "-s -w -X main.version=%version%"

echo "CloudflareST_windows_386..."
SET CGO_ENABLED=0
SET GOOS=windows
SET GOARCH=386
go build -o Releases\CloudflareST_windows_386\CloudflareST.exe -ldflags "-s -w -X main.version=%version%"

echo "CloudflareST_windows_amd64..."
SET CGO_ENABLED=0
SET GOOS=windows
SET GOARCH=amd64
go build -o Releases\CloudflareST_windows_amd64\CloudflareST.exe -ldflags "-s -w -X main.version=%version%"

echo "CloudflareST_windows_arm64..."
SET CGO_ENABLED=0
SET GOOS=windows
SET GOARCH=arm64
go build -o Releases\CloudflareST_windows_arm64\CloudflareST.exe -ldflags "-s -w -X main.version=%version%"

ECHO.
ECHO Compilation complete...
ECHO.
PAUSE
```
</details>

****

Again, I would use a script for batch compression:

> It should be noted that the decompression software I usually use is Bandizip, so my script also calls Bandizip to achieve compression through commands. You can try to replace other decompression software (such as 7zip).

<details>
<summary><code><strong> Click to expand to view </strong></code></summary>

****
``` bat
@echo off
:: Delete old files
del /q ^
CloudflareST_darwin_amd64.zip ^
CloudflareST_darwin_arm64.zip ^
CloudflareST_windows_386.zip  ^
CloudflareST_windows_amd64.zip  ^
CloudflareST_windows_arm64.zip  ^
CloudflareST_linux_386.tar.gz ^
CloudflareST_linux_amd64.tar.gz ^
CloudflareST_linux_arm64.tar.gz ^
CloudflareST_linux_armv5.tar.gz ^
CloudflareST_linux_armv6.tar.gz ^
CloudflareST_linux_armv7.tar.gz ^
CloudflareST_linux_mips.tar.gz ^
CloudflareST_linux_mips64.tar.gz ^
CloudflareST_linux_mipsle.tar.gz ^
CloudflareST_linux_mips64le.tar.gz

:: Create a zip archive
"D:\Program Files\Bandizip\Bandizip.exe" bc -l:9 -fmt:zip ^
CloudflareST_darwin_amd64 ^
CloudflareST_darwin_arm64 ^
CloudflareST_windows_386 ^
CloudflareST_windows_amd64 ^
CloudflareST_windows_arm64

:: Create a tar archive
"D:\Program Files\Bandizip\Bandizip.exe" bc -fmt:tar ^
CloudflareST_linux_386 ^
CloudflareST_linux_amd64 ^
CloudflareST_linux_arm64 ^
CloudflareST_linux_armv5 ^
CloudflareST_linux_armv6 ^
CloudflareST_linux_armv7 ^
CloudflareST_linux_mips ^
CloudflareST_linux_mips64 ^
CloudflareST_linux_mipsle ^
CloudflareST_linux_mips64le

:: Create tar.gz archive
"D:\Program Files\Bandizip\Bandizip.exe" bc -l:9 -fmt:gz ^
CloudflareST_linux_386.tar ^
CloudflareST_linux_amd64.tar ^
CloudflareST_linux_arm64.tar ^
CloudflareST_linux_armv5.tar ^
CloudflareST_linux_armv6.tar ^
CloudflareST_linux_armv7.tar ^
CloudflareST_linux_mips.tar ^
CloudflareST_linux_mips64.tar ^
CloudflareST_linux_mipsle.tar ^
CloudflareST_linux_mips64le.tar

:: Delete tar archive
del /q ^
CloudflareST_linux_386.tar ^
CloudflareST_linux_amd64.tar ^
CloudflareST_linux_arm64.tar ^
CloudflareST_linux_armv5.tar ^
CloudflareST_linux_armv6.tar ^
CloudflareST_linux_armv7.tar ^
CloudflareST_linux_mips.tar ^
CloudflareST_linux_mips64.tar ^
CloudflareST_linux_mipsle.tar ^
CloudflareST_linux_mips64le.tar
```
</details>

****

With these two scripts, your list of Releases files will be the same as mine~

**Comment by hoseinnikkhah** [comment]
Thanks for the info, I will fix version asap and will compile rest of the files.
