### ISSUE TITLE
感觉脚本某一些地方还可以优化。

### ISSUE THREAD

**Issue by huanx9** [XIU2/CloudflareSpeedTest#69]
比如添加一个 "下载速度下限 5" 即 `-sl 5` 的时候，进度条就不会走了。 但是可以返回最终结果。
如果设置了SL ，就不知道进度跑到什么位置了，他只会告诉你，我现在拿到了几个IP。

还有就是不能边测边返回结果，只能等所有跑完了才可以显示结果。（这个应该做不到）

**Comment by XIU2** [comment]
以前就是你说的情况，但是那样的话，就不知道到底找到没有，找到了多少个。

**Comment by XIU2** [comment]
总之，你提到的这几点，目前都已经是近乎最优方式了。

除非把整个软件重写为 GUI 程序，否则就是现在这样了。

**Comment by huanx9** [comment]
那就算我已经找到了10个IP，但是进度没有跑完也不能提取这10个IP阿 。。 提前结束不能输出结果。
除非预先就设置 只返回10个结果。

**Comment by XIU2** [comment]
你使用 -dn 10 参数时（默认 20），一旦找到 10 个满足条件的 IP，就会停止下载测速，输出结果。

**Comment by huanx9** [comment]
我是本项目重度使用者， 你说的这些，我明白。  但是我还是觉得显示进度比较好

**Comment by XIU2** [comment]
除非有更多的人，认为需要改回去。

**Comment by huanx9** [comment]
表示理解，感谢开发者。

-n 这个参数是不是 默认为 4  就是延迟测四次 。

**Comment by XIU2** [comment]
参数 `-t` 默认就是 4 次，你不加 -t 参数就代表为 4 次。

参数 `-n` 最多 1000，太多的话，会导致结果不准确（同一时间的链接数太多了）。

**Comment by huanx9** [comment]
那 800应该还算比较安全的数值。谢谢了。
