### ISSUE TITLE
为什么我测出来的结果都是0呢？

### ISSUE THREAD

**Issue by jasonwang1203** [XIU2/CloudflareSpeedTest#70]
<img width="796" alt="截屏2021-02-27下午7 53 11" src="https://user-images.githubusercontent.com/50603517/109387159-a77d4180-793a-11eb-9567-2521becd9827.png">
一定要添加自定义参数吗？

**Comment by XIU2** [comment]
你是不是在**国外服务器**上面测速的？（你这延迟也太低了吧）
或者是本地测速**走了代理**？（比如在路由器里开了代理功能）

看 IP，你这种情况，扫到的延迟低的似乎是**回源 IP**（Cloudflare CDN 中分为任播 IP 和回源 IP，后者是专门去网站服务器回源用的，因此无法用于用户指向任意网站，即无法下载测速，只能是 0.00）。

建议加上 `-sl 0.01` （下载速度下限最低值）来排除掉这些回源 IP（即 0.01 MB/s 以下的 IP）。

**Comment by jasonwang1203** [comment]
哦，我这是在广移nat上测试的，昨晚测得没有速度，应该是昨晚被打了，刚才我重新跑了一遍脚本，正常了，谢谢大佬的分享。
