### ISSUE TITLE
3.Proxy_x64   安装，重启，卸载 均无法正常完成 

### ISSUE THREAD

**Issue by goodluckwxl** [XIU2/CloudflareSpeedTest#73]
![1](https://user-images.githubusercontent.com/79687546/111060932-76287800-84db-11eb-8b82-5fa425296155.png)
![2](https://user-images.githubusercontent.com/79687546/111060949-93f5dd00-84db-11eb-9ac2-a35e3811f467.png)
![3](https://user-images.githubusercontent.com/79687546/111060951-95bfa080-84db-11eb-82ed-44b74532453d.png)

**Comment by XIU2** [comment]
你这个是一开始就没有安装服务成功，双击脚本时默认会申请管理员权限（用来安装/重启/卸载服务）。
你尝试过**右键脚本 - 以管理员身份运行**吗？

**Comment by CrazyBoyFeng** [comment]
> 尝试过**右键脚本 - 以管理员身份运行**吗？

要不批处理加个申请管理员身份运行？  
```
%1 start "" mshta vbscript:CreateObject("Shell.Application").ShellExecute("cmd.exe","/c ""%~s0"" ::","","runas",1)(window.close)&&exit
```

**Comment by XIU2** [comment]
怎么不回复咧。。。问题解决了么？

**Comment by goodluckwxl** [comment]
不知道怎么取消订阅，这几天邮箱炸了，全是这个问题的相关邮件信息，包含许多像您一样热心 朋友，&nbsp; 请允许我向你说句对不起，没能及时回复，让您久候了，。很多方法都按照大家说的都试过了，很遗憾都没能解决，我仍然没有打算放弃，直到我找到原因



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月18日(星期四) 中午12:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XIU2/CloudflareSpeedTest] 3.Proxy_x64   安装，重启，卸载 均无法正常完成  (#73)





 
怎么不回复咧。。。问题解决了么？

**Comment by XIU2** [comment]
@goodluckwxl 可是这个 Issues 除了你只有两个人参与，共三个回复呀（不包括你这个，还有一个人回复后自己删了），就三个回复怎么会把你的邮箱炸了。。。
我的项目中的所有 Issues 我都默认会收到通知，完全正常呀，就三个回复邮件通知。

**Comment by BiuZero** [comment]
这个问题，我感觉最大的原因可能是没有改3proxy.cfg默认的ip，默认的XXX不替换ip运行就会提示这个🤣

**Comment by XIU2** [comment]
@BiuZero 确实有可能，因为默认的 xxx 不是 IP，所以**不修改就启动肯定会报错**。

然后楼主再运行 <kbd>停止服务.bat</kbd> 就会因为没有启动而停止失败，再运行 <kbd>卸载服务.bat</kbd> 又会因为没有成功启动(=安装)而失败。

我稍后把默认的 xxx 改成一个**有效的 Cloudflare CDN IP** 吧！

> 这样的话，哪怕该 IP 在部分地区不可用，起码也不会启动失败~

****

问问题的发个问题就跑，也没有后续交流，就很烦（强迫症）。。。
