### ISSUE TITLE
在 IPv6 单栈机器上无法运行

### ISSUE THREAD

**Issue by chengziorange** [XIU2/CloudflareSpeedTest#76]
System: Debian 10

![QQ截图20210316171355](https://user-images.githubusercontent.com/30137964/111284392-09e47a80-867b-11eb-8341-68dfb72fa124.jpg)

**Comment by CrazyBoyFeng** [comment]
还需要加 `-ipv6` 参数

**Comment by chengziorange** [comment]
> 还需要加 `-ipv6` 参数

是我疏忽了
