### ISSUE TITLE
这脚本我算是不能用了，以前电信没问题，自从换了移动。 

### ISSUE THREAD

**Issue by huanx9** [XIU2/CloudflareSpeedTest#78]
线程改成100 都没用。  一跑就炸 。 

有没有一样是移动的，求解脱。

尝试自己解决很多天了，毫无进展。 翻遍了整个百度和google ，发现偶尔有那么几个人和我一样。但是没有解决方案。 

之前电信大概改到800 都不会炸  ，1000可能会炸， 现在移动 100都炸， 没法用了。

**Comment by CrazyBoyFeng** [comment]
移动家宽可以试试 ipv6。

**Comment by XIU2** [comment]
100 就炸是什么意思？

**Comment by XIU2** [comment]
如果是遇到了延迟异常过低（20ms 左右），且下载速度只有 0.00、0.01 的情况，说明你遇到了被运营商或某墙劫持的 CDN IP。

这种情况下你可以加上 `-sl 0.1` 这个参数再去跑（过滤掉下载速度低于 0.1 MB/s 的 IP），这样能过滤掉这些 “不可用” 的 IP。

**Comment by huanx9** [comment]
就是原来电信用 -n 800 网络都不会断网 ，现在换移动 -n 100 都会断网，就是你之前所说的网络拥堵，我现在换移动了 堵的飞起，我估计这个问题应该也解决不了了， 还是算了。

**Comment by XIU2** [comment]
如果你只是更换了运营商，而没有更换、修改任何设备，那看来就是 移动 做了什么限制导致的（比如限制网络链接数）。

**Comment by CrazyBoyFeng** [comment]
如果是连接数限制，那么没有别的办法，只能进一步减少并发线程数。  
不过如果能用 ipv6 也可以试试。ipv6 用的人少，不拥挤，限制也少。
