### ISSUE TITLE
测速结果中 [平均延迟] 异常过低 20ms+ 且 [下载速度] 为 0.01、0.00 怎么办？

### ISSUE THREAD

**Issue by micleuu** [XIU2/CloudflareSpeedTest#79]
消失啦?全部测速都是0.0.1?

**Comment by XIU2** [comment]
什么鬼？截个图看下。

**Comment by micleuu** [comment]
![image](https://user-images.githubusercontent.com/45659357/111570997-edfae900-87e0-11eb-8054-a043beae861c.png)

**Comment by XIU2** [comment]
你这不是我的软件。

**Comment by micleuu** [comment]
![image](https://user-images.githubusercontent.com/45659357/111571031-0539d680-87e1-11eb-8f64-774ab138299f.png)

**Comment by micleuu** [comment]
我拿的你DDNS的脚本

**Comment by XIU2** [comment]
可是你用别的软件出问题了找我干嘛。。。

**Comment by micleuu** [comment]
稍等 稍等

**Comment by micleuu** [comment]
****
![image](https://user-images.githubusercontent.com/45659357/111571241-62358c80-87e1-11eb-971a-88a52038fcf3.png)

**Comment by XIU2** [comment]
凡是这些延迟异常过低的 IP 全都是被运营商或某墙劫持了的（最近开会后才出现的）。

你可以加上 -sl 0.1 这个参数再去跑，这样能过滤掉这些 “不可用” 的 IP。

**Comment by micleuu** [comment]
好的 感谢

**Comment by micleuu** [comment]
换了个网络跑也是一样所以想不通了 非常感谢

**Comment by XIU2** [comment]
自从月初开会后，部分 Cloudflare CDN IP 就被劫持了（表现特征为延迟异常过低，且不可用），可能是某些 XX 网站被 CDN 默认分配了这些 IP 的，导致 IP 被劫持，连带着误伤了我们。

**Comment by micleuu** [comment]
完美解决 感谢

**Comment by XIU2** [comment]
OK，那我就先关闭问题了~

**Comment by XIU2** [comment]
似乎进入 4 月后，就没有 Cloudflare CDN IP 的 TCP 劫持事件了（敏感时期过去了）。
具体时间我也不清楚，这两星期都没有遇到过几十 ms 的异常 IP 测速结果了。
