### ISSUE TITLE
最新版 v1.4.10 被杀软直接删除

### ISSUE THREAD

**Issue by super-yan86** [XIU2/CloudflareSpeedTest#82]
用 v1.4.9 版本就没事！

**Comment by XIU2** [comment]
哪个杀毒软件？

v1.4.10 我就改了几行代码，这都能被报毒么？https://github.com/XIU2/CloudflareSpeedTest/commit/85546abb23d2173e10041ea97c360ccb430d38e6

**Comment by XIU2** [comment]
我去 VirusTotal 查毒发现还真有个别报毒的，于是我就写了个 `Hello, World!` 结果也[报毒](https://www.virustotal.com/gui/file/5e71ccdcfe58c758c0c7fa3cd702c7d2cec5220df9022d5561756cff5e7a2deb/detection)。。。

只要是 Go 语言编译的都报毒，我想起来我另外几个开源 C# 软件也是这样，严重怀疑准确性。。。

``` golang
package main

import "fmt"

func main() {
	fmt.Println("Hello, World!")
}
```

**Comment by XIU2** [comment]
怎么都是发个 Issues 后就完全不吭声、不回复了呢？

**Comment by ulifuqiang** [comment]
![Uploading Snipaste_2021-03-24_14-48-26.png…]()

**Comment by XIU2** [comment]
@ulifuqiang 淦，Defender 上午还不报毒呢，下午就报毒了。。。
我已经向微软提交申诉了，顺利的话估计明天就不报毒了。

目前我发现报毒主要针对的是 Windows 64位 版本，32位版本则都不报毒（其它系统版本也一样）。

**Comment by XIU2** [comment]
@ulifuqiang 今天微软处理速度还算快，我记得以前起码要大半天。。。

我在清除缓存并更新到最新病毒库后，扫描 Windows 64位 版本已经不再报毒了。

![02](https://user-images.githubusercontent.com/54703944/112316389-06d63380-8ce6-11eb-9c08-8b9377ca478d.png)

**Comment by super-yan86** [comment]
> 试了下向 卡巴斯基 提交误报申诉，经过人工检查**确实是误报**。
> 
> 一开始我刚申诉没几分钟，卡巴斯基就回复我说不是误报。
> 然后我回复说 **32 位版本没有报毒，且这是个开源软件**（附链接），于是卡巴斯基时隔半个小时后回复我**确实是误报！**
> 
> ![01](https://user-images.githubusercontent.com/54703944/112101976-82e75300-8be2-11eb-997d-11c1c50228ca.png)

好的，多谢！

**Comment by XIU2** [comment]
我尝试过向 **McAfee、360** 申诉误报，但是几天了也没收到回复。。。

目前因为很多安全厂商**滥用 AI 查毒**，导致误报率大大提高（写个 `Hello, World!` 都能报毒），再加上各安全厂商都会**共享病毒库**，这意味着一旦某个 “大厂” 误报，很快就会扩散到其他安全软件中，然后就会导致**大范围误报**。

然而这么多安全软件，要么**没有提供**误报申诉渠道（或者隐藏太深），要么就是误报申诉后**石沉大海**，唉。。。

**Comment by jimmyxiaoz** [comment]
最近运行 1.4.10  1.4.9时系统直接卡死，于是到virustotal.com查了一下结果
![image](https://user-images.githubusercontent.com/76069968/115038006-af506f80-9f01-11eb-988c-f9e91e608510.png)

**Comment by jimmyxiaoz** [comment]
最近运行 1.4.10 和 1.4.9时 系统直接卡死，到virustotal.com查了一下结果
![image](https://user-images.githubusercontent.com/76069968/115038347-07877180-9f02-11eb-8e21-b9fa490e14cd.png)

**Comment by CrazyBoyFeng** [comment]
go 写的东西很容易误报的，主要是因为用 go 写病毒木马的实在太多。

**Comment by XIU2** [comment]
@jimmyxiaoz 如果运行软件后出现网络卡顿甚至卡死的情况，请减少**测速线程数量**（默认 `-n 500`）。
这是正常现象，一般是因为路由器性能不足，导致处理不过来大量连接~

**Comment by XIU2** [comment]
如果再出现微软 Defender 误报的情况，请告诉我~

**Comment by blueb0ne** [comment]
请问怎么向微软申诉？我也遇到类似问题 @XIU2

**Comment by XIU2** [comment]
@blueb0ne 去这里提交申诉：https://www.microsoft.com/en-us/wdsi/submissionhistory
写上报毒的名称，以及病毒库版本号（在[这里](https://www.microsoft.com/en-us/wdsi/defenderupdates)可以看到最新的病毒库版本号），简单描述一下软件作用，然后上传报读软件文件，一般一个工作日就会解决了。

**Comment by blueb0ne** [comment]
![image](https://github.com/XIU2/CloudflareSpeedTest/assets/12727943/d709cb48-8cc5-400e-bcbe-cb525750ca3a)
@XIU2 感谢回复，但是这个链接https://www.microsoft.com/en-us/wdsi/submissionhistory好像没有内容，是否是另外的页面？

**Comment by XIU2** [comment]
@blueb0ne 嗯确实。。。发错网址了，给你的那个是我用来看申诉提交记录及处理状态的。。。

就是你发的第二个网址，选择第一个 [Home customer] 这个，第三个选项不是给个人开发者用的。
