### ISSUE TITLE
300M宽带怎么测算出与实际宽带不符的速度了呢

### ISSUE THREAD

**Issue by 793354162** [XIU2/CloudflareSpeedTest#83]

**Comment by 793354162** [comment]
![image](https://user-images.githubusercontent.com/19319464/111936509-c5d0fa00-8b00-11eb-9064-ec3a7975182b.png)

**Comment by 793354162** [comment]
./CloudflareST -n 1000 -t 20 -dt 3 -tl 160 --sl 20 -dn 3用的这个配置

**Comment by XIU2** [comment]
我的 250M 宽带（200M 宽带+多出来的 50M）平时也最多能跑到 30MB/s，没有遇到过超出宽带速度上限的情况。

**Comment by 793354162** [comment]
我又用（./CloudflareST -n 1000 -t 20 -dt 3 -tl 160 --sl 20 -dn 3）测试了一次 超出宽带情况依然存在
# XIU2/CloudflareSpeedTest v1.4.10

开始延迟测速（模式：TCP IPv4，端口：443，平均延迟上限：160.00 ms）：
106660 / 106660 [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
开始下载测速（下载速度下限：20.00 MB/s，下载测速数量：3，下载测速队列：106）：
3 / 3 [---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
104.25.49.70      20      20      0.00    150.50    65.59          
104.16.242.253    20      20      0.00    151.29    51.91          
104.21.98.76      20      20      0.00    151.47    48.57          

我把超出宽带的IP重新放入1.txt重新测速三次
第一次：
# XIU2/CloudflareSpeedTest v1.4.10

开始延迟测速（模式：TCP IPv4，端口：443，平均延迟上限：9999.00 ms）：
12 / 12 [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
开始下载测速（下载速度下限：0.00 MB/s，下载测速数量：3，下载测速队列：3）：
3 / 3 [---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
104.16.242.253    4       4       0.00    150.22    46.33          
104.21.98.76      4       4       0.00    144.71    30.84          
104.25.49.70      4       4       0.00    151.73    18.58          

第二次：

# XIU2/CloudflareSpeedTest v1.4.10

开始延迟测速（模式：TCP IPv4，端口：443，平均延迟上限：9999.00 ms）：
12 / 12 [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
开始下载测速（下载速度下限：0.00 MB/s，下载测速数量：3，下载测速队列：3）：
3 / 3 [---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
104.16.242.253    4       4       0.00    150.29    37.49          
104.21.98.76      4       4       0.00    146.74    36.85          
104.25.49.70      4       4       0.00    151.44    27.15          

第三次：
# XIU2/CloudflareSpeedTest v1.4.10

开始延迟测速（模式：TCP IPv4，端口：443，平均延迟上限：9999.00 ms）：
12 / 12 [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
开始下载测速（下载速度下限：0.00 MB/s，下载测速数量：3，下载测速队列：3）：
3 / 3 [---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
IP 地址           已发送  已接收  丢包率  平均延迟  下载速度 (MB/s)
104.21.98.76      4       4       0.00    148.62    43.34          
104.25.49.70      4       4       0.00    152.59    31.10          
104.16.242.253    4       4       0.00    150.89    22.99          

超出情况没有出现

**Comment by XIU2** [comment]
你去掉 -dt 3 参数试试。
然后再用默认参数直接运行试试。

**Comment by ulifuqiang** [comment]
你们本地都什么网络啊，能跑这么快? 我四川电信就能跑13MB/s

**Comment by CrazyBoyFeng** [comment]
> 你们本地都什么网络啊，能跑这么快? 我四川电信就能跑13MB/s

你这电信还算快的，华东电信和华中电信基本上限速 100kb/s 左右。

**Comment by XIU2** [comment]
已更新 v2.2.1 版本，修复 一些情况下下载测速数值过大的问题，有兴趣的话你可以试试。
https://github.com/XIU2/CloudflareSpeedTest/releases/tag/v2.2.1
