### ISSUE TITLE
管理1.4.9版本被360报告是木马，直接给删除了

### ISSUE THREAD

**Issue by klmahua** [XIU2/CloudflareSpeedTest#84]
管理1.4.9版本被360报告是木马，直接给删除了，，，咋回事，，，求解决

**Comment by XIU2** [comment]
我用的 **Microsoft Defender、火绒、[腾讯](https://habo.qq.com/file/showdetail?pk=ADcGY11lB2MIOFs7U2U%3D)** 扫描后都**没有**报毒，一切正常。

**Comment by klmahua** [comment]
哦。。。相信程序应该是安全的，，，希望管理能解决误报问题。。。总是误报也很烦人

**Comment by XIU2** [comment]
没办法，小软件没人权，很容易被误报，大厂的软件都购买的有数字签名（保护费似的）来避免误报。
我会去申诉，但不一定保证通过。
> 比如卡巴斯基的我申诉没几分钟就回复说不是误报，我又提供了一些信息后，卡巴斯基**才确认为误报**。。。

**Comment by XIU2** [comment]
对了，被误报的是 32 位还是 64 位的？还是都误报？其他版本呢？

能不能提供一张误报截图方便我去申诉？

**Comment by ulifuqiang** [comment]
> 对了，被误报的是 32 位还是 64 位的？还是都误报？其他版本呢？
> 
> 能不能提供一张误报截图方便我去申诉？

![Snipaste_2021-03-24_14-48-26](https://user-images.githubusercontent.com/25083314/112267748-e0e26c00-8cb0-11eb-819f-9c53946379ce.png)

**Comment by soap-man** [comment]
![微信截图_20210324145301](https://user-images.githubusercontent.com/33997593/112267843-04a5b200-8cb1-11eb-9924-af3fd3f32962.png)

**Comment by soap-man** [comment]
> 对了，被误报的是 32 位还是 64 位的？还是都误报？其他版本呢？
> 
> 能不能提供一张误报截图方便我去申诉？

![微信截图_20210324145301](https://user-images.githubusercontent.com/33997593/112267897-1ab37280-8cb1-11eb-838f-fb4b461b3945.png)

**Comment by soap-man** [comment]
1.4.8不报啊

**Comment by XIU2** [comment]
@ulifuqiang @soap-man 淦，Defender 上午还不报毒呢，下午就报毒了。。。
我已经向微软提交申诉了，顺利的话估计明天就不报毒了。

目前我发现报毒主要针对的是 Windows 64位 版本，32位版本则都不报毒（其它系统版本也一样）。

**Comment by XIU2** [comment]
@ulifuqiang @soap-man 今天微软处理速度还算快，我记得以前起码要大半天。。。

我在清除缓存并更新到最新病毒库后，扫描 Windows 64位 版本已经不再报毒了。

![02](https://user-images.githubusercontent.com/54703944/112316389-06d63380-8ce6-11eb-9c08-8b9377ca478d.png)

**Comment by XIU2** [comment]
我尝试过向 **McAfee、360** 申诉误报，但是几天了也没收到回复。。。

目前因为很多安全厂商**滥用 AI 查毒**，导致误报率大大提高（写个 `Hello, World!` 都能报毒），再加上各安全厂商都会**共享病毒库**，这意味着一旦某个 “大厂” 误报，很快就会扩散到其他安全软件中，然后就会导致**大范围误报**。

然而这么多安全软件，要么**没有提供**误报申诉渠道（或者隐藏太深），要么就是误报申诉后**石沉大海**，唉。。。

**Comment by google-mirror** [comment]
> 我尝试过向 **McAfee、360** 申诉误报，但是几天了也没收到回复。。。
> 
> 目前因为很多安全厂商**滥用 AI 查毒**（报毒名称末尾有数字/字母组成的 ID），导致误报率大大提高（写个 `Hello, World!` 都能报毒），再加上各安全厂商都会**共享病毒库**，这意味着一旦某个 “大厂” 误报，很快就会扩散到其他安全软件中，然后就会导致**大范围误报**（报毒名称都一样）。
> 
> 然而这么多安全软件，要么**没有提供**误报申诉渠道（或者隐藏太深），要么就是误报申诉后**石沉大海**，唉。。。

360就是扯淡的, 文件名都能报毒

**Comment by XIU2** [comment]
如果再出现微软 Defender 误报的情况，请告诉我~
