### ISSUE TITLE
测速链接

### ISSUE THREAD

**Issue by hellodword** [XIU2/CloudflareSpeedTest#89]
官方有一个[测速](https://speed.cloudflare.com/)，抓包得到下载和上传的链接

`https://speed.cloudflare.com/__down?measId=0&bytes=102400`
和
`https://speed.cloudflare.com/__up?measId=0`

不知是否可用于 #19 所说的测速链接，如果可以，那么也可以考虑加一个测试上传的功能。

**Comment by XIU2** [comment]
下载我知道，因为该项目以前用的就是这个测速链接。
只不过后来 Cloudflare 限制了流量（或者说是用的人多了），导致一到晚上就无法使用了（提示资源超出上限...）

后来我就改成自建的了（生成一个大的空图片文件，让 Cloudflare CDN 缓存起来）。

****

至于上传，这个一般人都用不上吧？

大家无论是像我一样来**加速访问使用 Cloudflare CDN 的网站**，要么就是**加速代理**的，都只需要关注**下载速度**（下载速度足够快的话，上传速度也不会慢到哪里，当然国内基本都是上下行不对等的）。

**Comment by hellodword** [comment]
> 这个我知道，因为该项目以前用的就是这个官方测速链接。
> 只不过后来 Cloudflare 限制了流量（或者说是用的人多了），导致一到晚上就无法使用了（提示资源超出上限...）
> 
> 后来我就改成自建的了（生成一个大的空图片文件，让 Cloudflare CDN 缓存起来）。
> 
> 至于上传，这个一般人都用不上吧？
> 
> 大家要么是像我一样来**加速访问使用 Cloudflare CDN 的网站**，要么是**站长加速自己网站**的，要么就是**加速代理**的，都只需要重点关注**下载速度**（毕竟下载速度足够快的话，上传速度也不会慢到哪里，当然国内基本都是上下行不对等的）。

原来如此，谢谢(๑•̀ㅂ•́)و✧
