### ISSUE TITLE
建议生成result文件的时候，文件名带一个时间戳后缀

### ISSUE THREAD

**Issue by HoldOnBro** [XIU2/CloudflareSpeedTest#96]

**Comment by HoldOnBro** [comment]
这样方便本地留存多份不同时间段的测速结果

**Comment by XIU2** [comment]
这种需求不应该由软件自身实现，因为软件提供的有自定义输出结果文件名的参数 `-o "xxx.txt"`，用户完全可以自己指定，或者写个简单的脚本去运行时自动指定当前世界。
