### ISSUE TITLE
result.csv 用Excel 2016打开时中文乱码

### ISSUE THREAD

**Issue by exLuLu** [XIU2/CloudflareSpeedTest#97]
IP 鍦板潃 | 宸插彂閫?宸叉帴鏀?涓㈠寘鐜?骞冲潎寤惰繜 | 涓嬭浇閫熷害 (MB/s) |   |  
-- | -- | -- | -- | --

用记事本或者Notepad++打开却没有问题，虽然对使用没有什么影响，但还是希望能修复

**Comment by XIU2** [comment]
这是你的软件编码问题，不是 BUG，默认的结果文件是全系统通用的 UTF-8 编码。
如果打开编码，说明你的软件编码设置有问题。

**Comment by qcgzxw** [comment]
Windows下确实有这个问题
默认生成的是标准的UTF-8编码没问题，但是由于Windows是使用utf-8-bom编码，所以这里会有中文乱码的问题
但是这里可以考虑优化下 在Windows下编译时加入BOM标识

```golang
"\xEF\xBB\xBF"
```

**Comment by XIU2** [comment]
@qcgzxw 这个无所谓了，因为我发现很多人是直接记事本打开的，感觉我还不如改成 .txt 算了。。。

**Comment by qcgzxw** [comment]
文本的话 不好展示吧 竖线空格分割？
