### ISSUE TITLE
测速结果IP为零，跳过测速结果

### ISSUE THREAD

**Issue by ipadwin** [XIU2/CloudflareSpeedTest#98]
系统debian10 软件为1.4.10 测试一直显示结果IP为零跳过测速，不知道哪里问题。权限也给了，也试过更换测速端口，还是没结果。

**Comment by XIU2** [comment]
这种提示，很有可能是你的服务器无法访问 Cloudflare CDN 导致的。

> 也有可能是防火墙（出）的问题？

这种情况，最好是用 **TCPing** 工具测试下看看是真连不上还是只是我的软件连不上（虽然我刚刚才用过 CloudflareST），或者你也可以用 **curl** 访问一下任意使用 Cloudflare CDN 的网站，看看能不能访问。
